/* Generated by Together */

#ifndef GAMESERVER_H
#define GAMESERVER_H
#include "DBCCommon.h"

#include "dstring.h"
#include "DataSocket.h"
#include <dstring.h>

class GameServer
{
public:
	GameServer():m_datasock(0),m_innerport(0),m_outerport(0){}
	void SetDataSock(dbc::DataSocket	*datasock)
	{
		m_datasock	=datasock;
		datasock->SetPointer(this);
	}

	dbc::dstring 		m_gamename;			//""
	dbc::dstring 		m_innerip;
	dbc::uShort			m_innerport;
	dbc::dstring 		m_outerip;
	dbc::uShort			m_outerport;
	dbc::DataSocket	*	m_datasock;
public:

};
#endif //GAMESERVER_H
