/* Generated by Together */
#include "stdafx.h"
#ifndef USE_IOCP

#include "GameServerApp.h"
#include <iostream>
#include <time.h>
#include "GameCommon.h"
#include "SubMap.h"
#include "GameApp.h"

extern BOOL	g_bGameEnd;

// ════════════════════════════════════════════════════════════
//  InfoServer (без изменений — использует InfoNet, не LIBDBC сеть)
// ════════════════════════════════════════════════════════════

long ToInfoServer::Process()
{
	if(m_gmsvr->m_IfServer.GetPort() == 0)
	{
		LG("Store_data", "not configure InfoServer!\n");
		return 0;
	}

	m_gmsvr->m_IfServer.InValid();
	LG("Store_data", "Connect InfoServer(%s, %d)...\n", m_gmsvr->m_IfServer.GetIP().c_str(), m_gmsvr->m_IfServer.GetPort());
	g_gmsvr->ConnectInfo(&m_gmsvr->m_IfServer);

	DWORD	dwCurTick;
	DWORD	dwInterval = m_dwTimeOut;

	dwCurTick = GetTickCount();

	while(!GetExitFlag())
	{
		dwCurTick = GetTickCount();

		static DWORD dwLastRunTick = 0;
		if(dwCurTick - dwLastRunTick < dwInterval)
		{
			Sleep(10);
			continue;
		}

		try
		{
			if(!m_gmsvr->m_IfServer.IsValid() && m_gmsvr->m_IfServer.IsConnect())
			{
				LG("Store_data", "Login InfoServer...\n");
				m_gmsvr->m_IfServer.Login();
			}
		}
		catch(...)
		{
			LG("Store_data", "Process Error!\n");
		}

		dwLastRunTick = dwCurTick;
	}

	LG("Store_data", "ToInfoServer Process Out!\n");

	return 0;
}

void InfoServer::Login()
{
	pNetMessage pNm = new NetMessage();
	char szPwd[33];
	cChar *szPassword = (cChar *)GetPassword();
	if(strlen(szPassword) > 32)
	{
		LG("Store_data", "Login password too long!\n");
		return;
	}
	strcpy(szPwd, szPassword);
	BuildNetMessage(pNm, INFO_LOGIN, 0, 0, 0, (unsigned char*)szPwd, long(strlen(szPwd) + 1));
	g_gmsvr->GetInfoServer()->SendData(pNm);
	FreeNetMessage(pNm);
}

long InfoServer::PeekMsg(unsigned long ms)
{
    if(ms < 10)
        ms = 10;

    while(ms-- > 0)
    {
        if(!m_MsgQueue.IsEmpty())
        {
            pNetMessage msg = m_MsgQueue.Pop();
            g_gmsvr->ProcessData(msg, CMD_FM_MSG);
        }
        else
            break;
    }
	return 0;
}

void InfoServer::OnConnect(bool result)
{
	if(result)
	{
		LG("Store_data", "InfoServer Connected!\n");
		g_gmsvr->ProcessData(NULL, CMD_FM_CONNECTED);
	}
	else
	{
		LG("Store_data", "InfoServer Connect Failed!\n");
	}
}

void InfoServer::OnDisconnect()
{
    InValid();
	LG("Store_data", "InfoServer Disconnected!\n");
    g_gmsvr->ProcessData(NULL, CMD_FM_DISCONNECTED);
}

// ════════════════════════════════════════════════════════════
//  GateHandler — callback'и от TcpClient (CorsairsNet)
// ════════════════════════════════════════════════════════════

void GateHandler::OnPacket(net::RPacket& packet)
{
    GateServer* gt = &_app->m_gtarray[_gateIndex];
    if (!gt->IsValid()) return;
    _app->ProcessData(gt, packet);
}

void GateHandler::OnDisconnected(int reason)
{
    // Из recv thread — только ставим флаг, обработка в game thread
    _app->m_pendingDisconnect.store(_gateIndex);
}

// ════════════════════════════════════════════════════════════
//  GameServerApp — конструктор / деструктор
// ════════════════════════════════════════════════════════════

GameServerApp::GameServerApp()
    : m_count(0)
{
	LG("init", "start init ServerApp\n");

	srand( (unsigned)time( NULL ) );

    m_strGameName = g_Config.m_szName;

    // Инициализация GateServer массива
    m_gtnum = min(MAX_GATE, g_Config.m_nGateCnt);
    for (int i = 0; i < m_gtnum; ++i)
    {
        m_gtarray[i].GetIP() = g_Config.m_szGateIP[i];
        m_gtarray[i].GetPort() = g_Config.m_nGatePort[i];
        m_gtarray[i].m_playerlist = NULL;
        m_gateHandlers[i].Init(i, this);
        m_gateClients[i].SetHandler(&m_gateHandlers[i]);
    }

    // Инициализация InfoServer
    m_IfServer.SetInfoServer(g_Config.m_szInfoIP, g_Config.m_nInfoPort, g_Config.m_szInfoPwd, g_Config.m_nSection);

    // Запуск фонового потока переподключения
    m_connectThread = std::thread(&GameServerApp::ConnectGateLoop, this);

	LG("init", "ServerApp init over\n");
}

GameServerApp::~GameServerApp()
{
	if(m_IfServer.IsConnect())
	{
		DisconnectInfo(&m_IfServer);
		LG("Store_data", "Disconnect InfoServer!\n");
	}

    // Остановка потока переподключения
    m_exitFlag.store(true);
    if (m_connectThread.joinable())
        m_connectThread.join();

    // Отключение всех GateServer'ов
    for (int i = 0; i < m_gtnum; ++i)
    {
        m_gateClients[i].Disconnect();
        m_gtarray[i].Invalid();
    }
}

// ════════════════════════════════════════════════════════════
//  ConnectGateLoop — фоновый поток переподключения (замена ConnectGateServer::Process)
// ════════════════════════════════════════════════════════════

void GameServerApp::ConnectGateLoop()
{
    DWORD dwInterval = 5000;

    while (!m_exitFlag.load())
    {
        for (int i = 0; i < 1; i++)
        {
            if (m_exitFlag.load()) return;

            if (!m_gtarray[i].IsValid() && !m_gateClients[i].IsConnected())
            {
                LG("Connect", "connecting to GateServer %s:%d...\n",
                    m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort());

                if (m_gateClients[i].Connect(m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort()))
                {
                    m_gtarray[i].SetClient(&m_gateClients[i]);
                    // Уведомляем game thread о новом подключении
                    m_pendingConnect.store(i);
                    LG("Connect", "GateServer connected: %s:%d\n",
                        m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort());
                }
                else
                {
                    LG("Connect", "connect to GateServer failed, ip = %s, port = %d.\n",
                        m_gtarray[i].GetIP().c_str(), m_gtarray[i].GetPort());
                }
            }
        }
        Sleep(dwInterval);
    }
}

// ════════════════════════════════════════════════════════════
//  HandlePendingEvents — обработка connect/disconnect из game thread
// ════════════════════════════════════════════════════════════

void GameServerApp::HandlePendingEvents()
{
    // Обработка pending connect
    int ci = m_pendingConnect.exchange(-1);
    if (ci >= 0 && ci < m_gtnum)
    {
        GateServer* gt = &m_gtarray[ci];
        // Синтезируем CMD_MM_GATE_CONNECT → OnGateConnected
        net::WPacket wpkt(64);
        wpkt.WriteCmd(CMD_MM_GATE_CONNECT);
        wpkt.WriteInt64(0);
        net::RPacket rpkt(wpkt.Data(), wpkt.GetPacketSize(), false);
        g_pGameApp->ProcessNetMsg(NETMSG_GATE_CONNECTED, gt, rpkt);
    }

    // Обработка pending disconnect
    int di = m_pendingDisconnect.exchange(-1);
    if (di >= 0 && di < m_gtnum)
    {
        auto const lock = std::lock_guard{m_mutdisconn};
        GateServer* gt = &m_gtarray[di];
        if (gt->IsValid() || gt->m_playerlist != nullptr)
        {
            // Синтезируем CMD_MM_GATE_RELEASE → OnGateDisconnect
            // playerlist передаётся через пакет (как в старом коде)
            net::WPacket wpkt(64);
            wpkt.WriteCmd(CMD_MM_GATE_RELEASE);
            wpkt.WriteInt64(ToAddress(gt->m_playerlist));
            net::RPacket rpkt(wpkt.Data(), wpkt.GetPacketSize(), false);
            g_pGameApp->ProcessNetMsg(NETMSG_GATE_DISCONNECT, gt, rpkt);
        }
    }
}

// ════════════════════════════════════════════════════════════
//  PeekPacket — опрос всех gate-подключений (замена PKQueue::PeekPacket)
// ════════════════════════════════════════════════════════════

void GameServerApp::PeekPacket(unsigned long ms)
{
    DWORD start = GetTickCount();

    do
    {
        HandlePendingEvents();

        int processed = 0;
        for (int i = 0; i < m_gtnum; i++)
        {
            if (m_gateClients[i].IsConnected())
                processed += m_gateClients[i].PollPackets(50);
        }

        DWORD elapsed = GetTickCount() - start;
        if (elapsed >= ms) break;

        if (processed == 0) Sleep(1);

    } while (true);
}

// ════════════════════════════════════════════════════════════
//  DisconnectGate — отключение GateServer
// ════════════════════════════════════════════════════════════

void GameServerApp::DisconnectGate(GateServer* pGate)
{
    if (pGate == nullptr) return;

    // Найти индекс GateServer
    for (int i = 0; i < m_gtnum; ++i)
    {
        if (&m_gtarray[i] == pGate)
        {
            m_gateClients[i].Disconnect();
            pGate->Invalid();
            return;
        }
    }
}

// ════════════════════════════════════════════════════════════
//  ProcessData — маршрутизация пакетов (замена PKQueue → ProcessData)
// ════════════════════════════════════════════════════════════

void GameServerApp::ProcessData(GateServer* gt, net::RPacket& pk)
{
    if (gt == nullptr) return;

    uint16_t cmd = pk.GetCmd();

    // OnServeCall-команды: SESS-echo (совместимость с C++ и .NET GateServer)
    if (cmd == CMD_TM_KICKCHA || cmd == CMD_TM_OFFLINE_MODE)
    {
        HandleServeCall(gt, pk);
        return;
    }

    int msg_id;
    switch (cmd)
    {
        case CMD_MM_GATE_CONNECT:
		    LG("Connect", "ProcessData Gate_Connect\n");
            msg_id = NETMSG_GATE_CONNECTED;
            break;

        case CMD_MM_GATE_RELEASE:
            msg_id = NETMSG_GATE_DISCONNECT;
            break;

        default:
            msg_id = NETMSG_PACKET;
            break;
    }

    g_pGameApp->ProcessNetMsg(msg_id, gt, pk);
}

void GameServerApp::ProcessData(pNetMessage msg, short sType)
{
    switch (sType)
    {
    case InfoServer::CMD_FM_CONNECTED:
        break;

    case InfoServer::CMD_FM_DISCONNECTED:
        break;

    case InfoServer::CMD_FM_MSG:
        break;

    default:
        break;
    }

    g_pGameApp->ProcessInfoMsg(msg, sType, GetInfoServer());
}

// ════════════════════════════════════════════════════════════
//  HandleServeCall — обработка sync-команд через SESS-echo
// ════════════════════════════════════════════════════════════

void GameServerApp::HandleServeCall(GateServer* gt, net::RPacket& pk)
{
    uint32_t sess = pk.GetSess();
    uint16_t cmd = pk.GetCmd();

    net::WPacket retpk(256);
    retpk.WriteSess(sess);

    switch (cmd)
    {
    case CMD_TM_KICKCHA:
    {
        auto const m = std::lock_guard{m_mutdisconn};
        long lChaDbID = pk.ReadInt64();
        CPlayer* pCOldPly = g_pGameApp->FindPlayerByDBChaID(lChaDbID);
        if (!pCOldPly || !pCOldPly->IsValid())
        {
            retpk.WriteInt64(0);
        }
        else
        {
            pCOldPly->GetCtrlCha()->BreakAction();
            pCOldPly->MisLogout();
            pCOldPly->MisGooutMap();
            g_pGameApp->ReleaseGamePlayer(pCOldPly);
            retpk.WriteInt64(1);
        }
        break;
    }
    case CMD_TM_OFFLINE_MODE:
    {
        auto player = ToPointer<CPlayer>((pk.ReverseReadInt64()));
        CCharacter* pCCha{};

        const auto return_code = [&]
        {
            if (!player)
                return ReturnCode::OfflineMode::Unknown;

            if (player->GetGateAddr() != pk.ReverseReadInt64())
                return ReturnCode::OfflineMode::Unknown;

            if (!player->IsValid())
                return ReturnCode::OfflineMode::Unknown;

            if (player->GetMainCha()->GetPlayer() != player)
                return ReturnCode::OfflineMode::Unknown;

            if (!g_Config.m_bOfflineMode)
                return ReturnCode::OfflineMode::Disabled;

            if (pCCha = player->GetCtrlCha(); !pCCha)
                return ReturnCode::OfflineMode::Unknown;

            if (!pCCha->IsLiveing())
                return ReturnCode::OfflineMode::Dead;

            if (auto map = pCCha->GetSubMap();
                map && !map->CanSavePos())
                return ReturnCode::OfflineMode::Refuse;

            if (pCCha->IsBoat())
                return ReturnCode::OfflineMode::Refuse;

            return ReturnCode::OfflineMode::Success;
        }();

        if (return_code != ReturnCode::OfflineMode::Success)
        {
            retpk.WriteInt64(static_cast<uint8_t>(return_code));
            break;
        }

        constexpr auto hour_in_ms = 60 * 60 * 1000;
        pCCha->_dwStallTick = GetTickCount() + (g_Config.m_dwStallTime * hour_in_ms);
        g_pGameApp->CanReceiveRequests(player->GetID(), false);
        player->SetCanReceiveRequests(false);
        retpk.WriteInt64(static_cast<uint8_t>(return_code));
        break;
    }
    default:
        return; // Неизвестная команда — не отправляем ответ
    }

    gt->SendData(retpk);
}

// ════════════════════════════════════════════════════════════
//  InfoServer — подключение
// ════════════════════════════════════════════════════════════

bool GameServerApp::ConnectInfo(InfoServer *pInfo)
{
    pInfo->RunInfoService(pInfo->GetIP().c_str(), pInfo->GetPort());
	return true;
}

void GameServerApp::DisconnectInfo(InfoServer *pInfo)
{
    pInfo->StopInfoService();
}

// ════════════════════════════════════════════════════════════
//  GateServer — управление
// ════════════════════════════════════════════════════════════

bool GameServerApp::IsValidGate(int i)
{
    if (i < 0 || i > m_gtnum) throw std::logic_error("gate index out of range!");

    return m_gtarray[i].IsValid();
}

GateServer* GameServerApp::FindGate(char const* gt_name)
{
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            if (m_gtarray[i].GetName().compare(gt_name) == 0)
                return &m_gtarray[i];
        }
    }

    return NULL;
}


// ════════════════════════════════════════════════════════════
//  Player список
// ════════════════════════════════════════════════════════════

bool GameServerApp::AddPlayer(GatePlayer* gtplayer, GateServer* gt, unsigned long gtaddr)
{
    if (gt == NULL || gtplayer == NULL) return false;
    if (!gt->IsValid()) return false;
	if (gtplayer->Next || gtplayer->Prev)
	{
		LG("character list error ", "when insert character, dbid %u, find it connect pointer is not empty!\n", gtplayer->GetDBChaId());
		return false;
	}

    gtplayer->SetGate(gt);
    gtplayer->SetGateAddr(gtaddr);

    gtplayer->Prev = NULL;
    gtplayer->Next = gt->m_playerlist;

    if (gtplayer->Next != NULL)
        gtplayer->Next->Prev = gtplayer;

    gt->m_playerlist = gtplayer;

	gt->AddPlayerCount();
    return true;
}

bool GameServerApp::DelPlayer(GatePlayer* gtplayer)
{
    if (gtplayer == NULL) return false;

    GateServer* gt = gtplayer->GetGate();
    if (gt == NULL || !gt->IsValid()) return false;

	if (gt->m_listcurplayer == gtplayer)
		gt->m_listcurplayer = gtplayer->Next;
    if ((gtplayer->Prev == NULL) && (gtplayer->Next == NULL))
        {
        if (gtplayer == gt->m_playerlist)
            {
				gt->m_playerlist = NULL;
            }
        else {
            return false;}
        }
    else if ((gtplayer->Prev == NULL) && (gtplayer->Next != NULL))
        {
			if (gtplayer != gt->m_playerlist) return false;

			gt->m_playerlist = gtplayer->Next;
			gt->m_playerlist->Prev = NULL;

        gtplayer->Next = NULL;
        }
    else if ((gtplayer->Prev != NULL) && (gtplayer->Next == NULL))
        {
        gtplayer->Prev->Next = NULL;

        gtplayer->Prev = NULL;
        }
    else {
        gtplayer->Prev->Next = gtplayer->Next;
        gtplayer->Next->Prev = gtplayer->Prev;

        gtplayer->Prev = NULL;
        gtplayer->Next = NULL;
        }

	gt->DecPlayerCount();
	return true;
}

bool GameServerApp::KickPlayer(GatePlayer* gtplayer, long lTimeSec)
{
	return KickPlayer2(gtplayer);
}

bool GameServerApp::KickPlayer2(GatePlayer *gtplayer)
{
	net::WPacket pkt(128);
	pkt.WriteCmd(CMD_MT_KICKUSER);
	pkt.WriteInt64(gtplayer->GetDBChaId());
	pkt.WriteInt64(gtplayer->GetGateAddr());
	pkt.WriteInt64(1);
	gtplayer->GetGate()->SendData(pkt);
	return true;
}

// ════════════════════════════════════════════════════════════
//  Сетевые интерфейсы отправки
// ════════════════════════════════════════════════════════════

bool GameServerApp::SendToGroup(net::WPacket& chginf)
{
    GateServer* pGate;

    for (int i = 0; i < m_gtnum; ++ i)
    {
        pGate = &m_gtarray[i];

        if (pGate->IsValid())
        {
			chginf.WriteInt64( 0 );
			pGate->SendData(chginf);
			return true;
        }
	}
    return true;
}

bool GameServerApp::SendToWorld(net::WPacket& chginf)
{
    net::WPacket CChginf;
    short        sCount;

    GatePlayer* pPlayer;
    GateServer* pGate;

    for (int i = 0; i < m_gtnum; ++ i)
    {
        pGate = &m_gtarray[i];

        if (pGate->IsValid())
        {
            sCount = 0;
            CChginf = chginf.Duplicate();

			pPlayer = pGate->m_playerlist;
            while (pPlayer != NULL)
            {
                CChginf.WriteInt64(pPlayer->GetDBChaId());
                CChginf.WriteInt64(pPlayer->GetGateAddr());
                sCount++;

                pPlayer = pPlayer->Next;
            }

            if (sCount > 0)
            {
                CChginf.WriteInt64(sCount);
                pGate->SendData(CChginf);
            }
        }
    }

    return true;
}

bool GameServerApp::SendToClient(GatePlayer* player, net::WPacket& pkt)
{
    if (player == NULL) return false;

    GateServer* pGate = player->GetGate();
    if (pGate != NULL)
    {
        pGate->SendData(pkt);
        return true;
    }
    else
    {
        return false;
    }
}

bool GameServerApp::SendToClient(net::WPacket& pkt, GatePlayer* playerlist)
{
    if (playerlist == NULL) return false;

    unsigned short usCount[MAX_GATE];
    net::WPacket   CChginf[MAX_GATE];
    GateServer*    pValidGate[MAX_GATE];
    short          sValidGateNum = 0;
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            pValidGate[sValidGateNum] = &m_gtarray[i];
            usCount[sValidGateNum] = 0;
            CChginf[sValidGateNum] = pkt.Duplicate();
            sValidGateNum++;
        }
    }

    GatePlayer* tmp = playerlist;
    while (tmp != NULL)
    {
        if (tmp->GetGate() == NULL)
        {
#ifdef defCOMMU_LOG
            LG("SendToClient", "WARNING! pGate = NULL, atorID=%d, gt_addr=0x%x\n",
                tmp->GetDBChaId(), tmp->GetGateAddr());
#endif
        }
        else
        {
            for (int i = 0; i < sValidGateNum; ++ i)
            {
                if (tmp->GetGate() == pValidGate[i])
                {
                    usCount[i]++;
                    CChginf[i].WriteInt64(tmp->GetDBChaId());
                    CChginf[i].WriteInt64(tmp->GetGateAddr());
                    break;
                }
            }
        }

        tmp = tmp->GetNextPlayer();
    }

    for (int i = 0; i < sValidGateNum; i++)
    {
        if (usCount[i] > 0)
        {
            CChginf[i].WriteInt64(usCount[i]);
            pValidGate[i]->SendData(CChginf[i]);
        }
    }

    return true;
}

bool GameServerApp::SendToClient(net::WPacket& pkt, int array_cnt, uplayer* uplayer_array)
{
    if (uplayer_array == NULL) return false;

    unsigned short usCount[MAX_GATE];
    net::WPacket   CChginf[MAX_GATE];
    GateServer*    pValidGate[MAX_GATE];
    short          sValidGateNum = 0;
    for (int i = 0; i < m_gtnum; ++ i)
    {
        if (m_gtarray[i].IsValid())
        {
            pValidGate[sValidGateNum] = &m_gtarray[i];
            usCount[sValidGateNum] = 0;
            CChginf[sValidGateNum] = pkt.Duplicate();
            sValidGateNum++;
        }
    }

    int j;
    for (int i = 0; i < array_cnt; ++ i)
    {
        if (uplayer_array[i].pGate == NULL)
        {
#ifdef defCOMMU_LOG
            LG("SendToClient", "WARNING! pGate = NULL, atorID=%d, gt_addr=0x%x\n",
                uplayer_array[i].m_dwDBChaId, uplayer_array[i].m_ulGateAddr);
#endif
            continue;
        }

        for (j = 0; j < sValidGateNum; ++ j)
        {
            if (uplayer_array[i].pGate == pValidGate[j])
            {
                usCount[j]++;
                CChginf[j].WriteInt64(uplayer_array[i].m_dwDBChaId);
                CChginf[j].WriteInt64(uplayer_array[i].m_ulGateAddr);
                break;
            }
        }
    }

    for (int i = 0; i < sValidGateNum; i++)
    {
        if (usCount[i] > 0)
        {
            CChginf[i].WriteInt64(usCount[i]);
            pValidGate[i]->SendData(CChginf[i]);
        }
    }

    return true;
}

bool GameServerApp::SendToGame(net::WPacket& pkt, uplayer* uplyr)
{
    return uplyr->pGate->SendData(pkt);
}


GameServerApp* g_gmsvr;

#endif
