/* Generated by Together */
#pragma once

#include <string>
#include "DBCCommon.h"

#include "Point.h"
#include "Identity.h"
#include "Usage.h"
#include "Config.h"
#include "gtplayer.h"
#include "util.h"

#include "CorsairsNet.h"

#include <mutex>
#include <thread>
#include <atomic>
#include <span>
#include <unordered_set>

// GateServer     GateServer
class GameServerApp;
class CPlayer;

class GateServer {
public:
	GateServer();
	~GateServer();

	void  SetClient(net::TcpClient* client);
	void  Invalid();
	bool  IsValid();

	std::string&    GetIP();
	unsigned short& GetPort();
	std::string&    GetName();

	bool  SendData(net::WPacket& pkt);

	//    Gate
	std::unordered_set<CPlayer*> m_playerlist;

	int   GetPlayerCount() const;

protected:
	std::string m_strIp;
	unsigned short m_usPort;
	std::string m_gtname;

	net::TcpClient* m_pClient;
};


// Callback-   GateServer
class GateHandler : public net::ITcpClientHandler {
public:
	GateHandler();

	void Init(int gateIndex, GameServerApp* app);

	void OnPacket(net::RPacket& packet) override;
	void OnDisconnected(int reason) override;

private:
	int _gateIndex;
	GameServerApp* _app;
};


//      (CorsairsNet)
class GameServerApp {
	friend class GateHandler;

public:
	GameServerApp();
	~GameServerApp();

	//
	char const* GetName() const;

	bool IsValidGate(int i);
	GateServer* FindGate(char const* gt_name);

	// Player  (GateServer  GatePlayer   )
	bool AddPlayer(GatePlayer* gtplayer, GateServer* gt, unsigned long gtaddr);
	bool DelPlayer(GatePlayer* gtplayer);

	void BeginGetGate(void);
	GateServer* GetNextGate(void);

	bool KickPlayer(GatePlayer* gtplayer, long lTimeSec = 0);
	bool KickPlayer2(GatePlayer* gtplayer);

	//
	bool SendToWorld(net::WPacket& pkt);
	bool SendToGroup(net::WPacket& chginf);
	bool SendToClient(GatePlayer* player, net::WPacket& pkt);
	bool SendToClient(net::WPacket& pkt, std::span<CPlayer* const> recipients);
	bool SendToClient(net::WPacket& pkt, int array_cnt, uplayer* uplayer_array);
	bool SendToGame(net::WPacket& pkt, uplayer* uplyr);

	// CorsairsNet
	void PeekPacket(unsigned long ms);
	void DisconnectGate(GateServer* pGate);

	net::WPacket GetWPacket();

	//   (  GateHandler::OnPacket  game thread)
	void ProcessData(GateServer* gt, net::RPacket& pk);

	//  OnServeCall- (CMD_TM_KICKCHA, CMD_TM_OFFLINE_MODE)  SESS-echo
	void HandleServeCall(GateServer* gt, net::RPacket& pk);

public:
	long m_count;
	Usage m_usage;

private:
	//     GateServer'
	void ConnectGateLoop();
	void HandlePendingEvents();

	std::recursive_mutex m_mutdisconn;

	net::TcpClient m_gateClients[MAX_GATE]{};
	GateHandler m_gateHandlers[MAX_GATE]{};
	GateServer m_gtarray[MAX_GATE]{};
	short m_gtnum{};
	short m_listcurgt{};

	std::thread m_connectThread;
	std::atomic<bool> m_exitFlag{false};
	// Atomic-  cross-thread  (connect/disconnect)
	// -1 =  , >= 0 =
	std::atomic<int> m_pendingConnect{-1};
	std::atomic<int> m_pendingDisconnect{-1};

	std::string m_strGameName;
};

extern GameServerApp* g_gmsvr;
