/* Generated by Together */
#pragma once

#ifndef USE_IOCP

#include <string>
#include "DBCCommon.h"
#include "PreAlloc.h"
#include "Point.h"
#include "Identity.h"
#include "Usage.h"
#include "Config.h"
#include "gtplayer.h"
#include "util.h"

#include "CorsairsNet.h"

#include <mutex>
#include <thread>
#include <atomic>

// GateServer     GateServer
class GameServerApp;

class GateServer {
public:
	GateServer() : m_pClient(nullptr), m_usPort(0), m_gtname(""), m_playerlist(NULL), m_playercount(0) {
	}

	~GateServer() {
		m_pClient = nullptr;
		m_gtname = "";
	}

	void SetClient(net::TcpClient* client) {
		m_pClient = client;
	}

	void Invalid() {
		m_pClient = nullptr;
	}

	bool IsValid() {
		return m_pClient != nullptr && m_pClient->IsConnected();
	}

	std::string& GetIP() {
		return m_strIp;
	}

	unsigned short& GetPort() {
		return m_usPort;
	}

	std::string& GetName() {
		return m_gtname;
	}

	bool SendData(net::WPacket& pkt) {
		if (IsValid()) {
			return m_pClient->Send(pkt);
		}
		return false;
	}

	GatePlayer* m_listcurplayer; //   

	// Player  
	GatePlayer* m_playerlist;
	int m_playercount;

	void AddPlayerCount() {
		++m_playercount;
	}

	void DecPlayerCount() {
		--m_playercount;
	}

	int GetPlayerCount() const {
		return m_playercount;
	}

protected:
	std::string m_strIp;
	unsigned short m_usPort;
	std::string m_gtname;

	net::TcpClient* m_pClient;
};


// Callback-   GateServer
class GateHandler : public net::ITcpClientHandler {
public:
	GateHandler() : _gateIndex(-1), _app(nullptr) {
	}

	void Init(int gateIndex, GameServerApp* app) {
		_gateIndex = gateIndex;
		_app = app;
	}

	void OnPacket(net::RPacket& packet) override;
	void OnDisconnected(int reason) override;

private:
	int _gateIndex;
	GameServerApp* _app;
};


//      (CorsairsNet)
class GameServerApp {
	friend class GateHandler;

public:
	GameServerApp();
	~GameServerApp();

	//  
	char const* GetName() const {
		return m_strGameName.c_str();
	}

	bool IsValidGate(int i);
	GateServer* FindGate(char const* gt_name);

	// Player  (GateServer  GatePlayer   )
	bool AddPlayer(GatePlayer* gtplayer, GateServer* gt, unsigned long gtaddr);
	bool DelPlayer(GatePlayer* gtplayer);
	bool BeginGetplayer(GateServer* gt);
	GatePlayer* const GetNextPlayer(GateServer* gt);

	void BeginGetGate(void);
	GateServer* GetNextGate(void);

	bool KickPlayer(GatePlayer* gtplayer, long lTimeSec = 0);
	bool KickPlayer2(GatePlayer* gtplayer);

	//   
	bool SendToWorld(net::WPacket& pkt);
	bool SendToGroup(net::WPacket& chginf);
	bool SendToClient(GatePlayer* player, net::WPacket& pkt);
	bool SendToClient(net::WPacket& pkt, GatePlayer* playerlist);
	bool SendToClient(net::WPacket& pkt, int array_cnt, uplayer* uplayer_array);
	bool SendToGame(net::WPacket& pkt, uplayer* uplyr);

	// CorsairsNet   
	void PeekPacket(unsigned long ms);
	void DisconnectGate(GateServer* pGate);

	net::WPacket GetWPacket() {
		return net::WPacket(256);
	}

	//   (  GateHandler::OnPacket  game thread)
	void ProcessData(GateServer* gt, net::RPacket& pk);

	//  OnServeCall- (CMD_TM_KICKCHA, CMD_TM_OFFLINE_MODE)  SESS-echo
	void HandleServeCall(GateServer* gt, net::RPacket& pk);

public:
	long m_count;
	Usage m_usage;

private:
	//     GateServer'
	void ConnectGateLoop();
	void HandlePendingEvents();

	std::recursive_mutex m_mutdisconn;

	net::TcpClient m_gateClients[MAX_GATE]{};
	GateHandler m_gateHandlers[MAX_GATE]{};
	GateServer m_gtarray[MAX_GATE]{};
	short m_gtnum{};
	short m_listcurgt{};

	std::thread m_connectThread;
	std::atomic<bool> m_exitFlag{false};
	// Atomic-  cross-thread  (connect/disconnect)
	// -1 =  , >= 0 =  
	std::atomic<int> m_pendingConnect{-1};
	std::atomic<int> m_pendingDisconnect{-1};

	std::string m_strGameName;
};

inline bool GameServerApp::BeginGetplayer(GateServer* gt) {
	if (gt == NULL) return false;
	if (!gt->IsValid()) return false;

	gt->m_listcurplayer = gt->m_playerlist;

	return true;
}

inline GatePlayer* const GameServerApp::GetNextPlayer(GateServer* gt) {
	GatePlayer* pretplayer = gt->m_listcurplayer;
	if (gt->m_listcurplayer)
		gt->m_listcurplayer = gt->m_listcurplayer->Next;

	return pretplayer;
}

inline void GameServerApp::BeginGetGate(void) {
	m_listcurgt = 0;
}

inline GateServer* GameServerApp::GetNextGate(void) {
	while (m_listcurgt < m_gtnum) {
		if (m_gtarray[m_listcurgt++].IsValid())
			return m_gtarray + (m_listcurgt - 1);
	}

	return 0;
}

extern GameServerApp* g_gmsvr;

inline void uplayer::Init(char const* gt_name, unsigned long gt_addr, DWORD atorID) {
	pGate = g_gmsvr->FindGate(gt_name);
	m_dwDBChaId = atorID;
	m_ulGateAddr = gt_addr;
}

#endif
