/* Generated by Together */

#include "Stdafx.h"
#include "SubMap.h"
#include "MoveAble.h"
#include "GameApp.h"
#include "CommFunc.h"
#include "Parser.h"

using namespace std;
_DBC_USING

const char* GetResPath(const char *pszRes);

SubMap::SubMap()
:m_pCEyeshotCell(0)
,m_pCStateCell(0)
,m_bIsRun(false)
{
	m_sCopyNO = 0;
	m_timeSpecialRun.Begin(300*1000);//5*60*1000

}

SubMap::~SubMap()
{
/*	for (short i = 0; i < GetEyeshotCellLin(); i++)
	{
		for (short j = 0; j < GetEyeshotCellCol(); j++)
		{
			delete [] m_pCEyeshotCell[i][j].m_pCStateCell;
		}
		delete [] m_pCEyeshotCell[i];
	}
	delete [] m_pCEyeshotCell;
	m_pCEyeshotCell = 0;

	for (short i = 0; i < GetStateCellLin(); i++)
		delete [] m_pCStateCell[i];
	delete [] m_pCStateCell;
	m_pCStateCell = 0;
*/
}

bool SubMap::Init(CMapRes *pCMapRes, dbc::Short sCopyNO)
{
	m_pCMapRes = pCMapRes;
	m_pCBaseRange = 0;

	// ״̬��Ԫ
	m_pCStateCell = new CStateCell**[GetStateCellLin()];
	if (!m_pCStateCell)
		//THROW_EXCP(excpMem,"��ͼ״̬��Ԫ����������з����ڴ�ʧ��");
		THROW_EXCP(excpMem,RES_STRING(GM_SUBMAP_CPP_00001));
	for (short i = 0; i < GetStateCellLin(); i++)
	{
		m_pCStateCell[i] = new CStateCell*[GetStateCellCol()];
		if (!m_pCStateCell[i])
			//THROW_EXCP(excpMem,"��ͼ״̬��Ԫ����������з����ڴ�ʧ��");
			THROW_EXCP(excpMem,RES_STRING(GM_SUBMAP_CPP_00001));
		for (short j = 0; j < GetStateCellCol(); j++)
			m_pCStateCell[i][j] = 0;
	}
	// ��Ұ��Ԫ
	m_pCEyeshotCell = new CEyeshotCell*[GetEyeshotCellLin()];
	if (!m_pCEyeshotCell)
		//THROW_EXCP(excpMem,"��ͼ��Ұ��Ԫ����������з����ڴ�ʧ��");
		THROW_EXCP(excpMem,RES_STRING(GM_SUBMAP_CPP_00002));
	short	sECellSX, sECellEX, sECellSY, sECellEY;
	short	sSCellNum;
	for (short i = 0; i < GetEyeshotCellLin(); i++)
	{
		m_pCEyeshotCell[i] = new CEyeshotCell[GetEyeshotCellCol()];
		if (!m_pCEyeshotCell[i])
			//THROW_EXCP(excpMem,"��ͼ��Ұ��Ԫ����������з����ڴ�ʧ��");
			THROW_EXCP(excpMem,RES_STRING(GM_SUBMAP_CPP_00002));
		// ��ʼ��
		for (short j = 0; j < GetEyeshotCellCol(); j++)
		{
			m_pCEyeshotCell[i][j].m_sPosX = j;
			m_pCEyeshotCell[i][j].m_sPosY = i;

			sECellSX = j * GetEyeshotCellWidth() / GetStateCellWidth();
			sECellEX = (j * GetEyeshotCellWidth() + GetEyeshotCellWidth() - 1) / GetStateCellWidth();
			sECellSY = i * GetEyeshotCellHeight() / GetStateCellHeight();
			sECellEY = (i * GetEyeshotCellHeight() + GetEyeshotCellHeight() - 1) / GetStateCellHeight();
			m_pCEyeshotCell[i][j].m_sStateCellNum = (sECellEX - sECellSX + 1) * (sECellEY - sECellSY + 1);
			m_pCEyeshotCell[i][j].m_pCStateCell = new CStateCell**[m_pCEyeshotCell[i][j].m_sStateCellNum];
			sSCellNum = 0;
			for (short m = sECellSY; m <= sECellEY; m++)
				for (short n = sECellSX; n <= sECellEX; n++)
					m_pCEyeshotCell[i][j].m_pCStateCell[sSCellNum++] = &m_pCStateCell[m][n];
		}
	}

	// װ�ظ�����Դ
	m_pCMapRes->m_pCMonsterSpawn->Load(this); // resok
	m_pCMapRes->m_pCMapSwitchEntitySpawn->Load(this); // resok
	LoadNpc(); // ע��NPCӦ�����װ�أ���������װ��ǰ�ȳ�ʼ��һЩNPC��Ҫ��������Ϣ,resok
	LoadEventEntity(); // װ���¼�ʵ����Ϣ,resok

	luaL_dofile(g_pLuaState, GetResPath(m_pCMapRes->m_szMonsterCofFile)); //resok

	m_bIsRun = false;
	m_sCopyNO = sCopyNO;
	m_timeScriptRun.Begin(1000);
	m_lPlayerNum = 0;
//	m_lActivePlayerNum = 0;
	memset(m_lInfoParam, 0, sizeof(dbc::Long) * defMAPCOPY_INFO_PARAM_NUM);

	return true;
}

//=============================================================================
// lFromEntityID ���ߴӸý�ɫ�����׳���
// lProtChaID��lProtTime �Ըý�ɫ����ʱ�䣬��lProtChaIDΪ0����������.��lProtTimeΪ0�������ϵͳĬ�ϱ���ʱ�䣬Ϊ-1�������ñ���
// lOnTick ���ߴ���ʱ�䣬Ϊ0�������ϵͳĬ�ϱ���ʱ�䣻Ϊ-1�������ô���
// usEventType��pEventRec �����������¼�
//=============================================================================
CItem* SubMap::ItemSpawn(const SItemGrid *pItemInfo, Long lPosX, Long lPosY, Char chSpawnType,
						 Long lFromEntityID, Long lProtChaID, Long lProtChaHandle, Long lProtTime, Long lOnTick,
						 CEvent	*pCEvent)
{
	CItem *pCItem;
	CItemRecord *pCItemRec;

	pCItemRec = GetItemRecordInfo(pItemInfo->sID);
	if (!pCItemRec)
		return 0;
	pCItem = g_pGameApp->GetNewItem();
	if (!pCItem)
		return 0;
	memcpy(&pCItem->m_SGridContent, pItemInfo, sizeof(SItemGrid));
	//if (pCItemRec->chExclusiveID) // ��Ҫ���浽���ݿ⣬����ǰ�����ݿ�ID��0������Ҫ����
	//{
	//	pItemInfo->SetDBParam(-1, 0);
	//}
	//else
	//	pItemInfo->SetDBParam(-1, 0);
	pCItem->m_pCItemRecord = pCItemRec;
	if (pCEvent)
		pCItem->SetEvent(*pCEvent);
	pCItem->SetName(pCItemRec->szName);
	pCItem->SetCat(pItemInfo->sID);
	pCItem->m_ID = g_pGameApp->m_Ident.GetID();
	pCItem->SetSpawnType(chSpawnType);
	pCItem->SetFromID(lFromEntityID);
	Square SShape = {{lPosX, lPosY}, 0};
	pCItem->SetAngle(rand() / 360);
	pCItem->SetEyeshotAbility(false);
	if (!Enter(&SShape, pCItem))
	{
		pCItem->Free();
		return 0;
	}
	pCItem->SetSpawnType(enumITEM_APPE_NATURAL);
	pCItem->SetProtCha(lProtChaID, lProtChaHandle);
	if (lProtTime == -1)
		pCItem->SetProtOnTick(0);
	else if (lProtTime > 0)
		pCItem->SetProtOnTick(lProtTime);
	if (lOnTick == -1)
		pCItem->SetOnTick(0);
	if (lOnTick > 0)
		pCItem->SetOnTick(lOnTick);


	Char szLogName[defLOG_NAME_LEN] = "";
	sprintf(szLogName, "%s+%u", pCItem->GetName(), pCItem->GetID());
	pCItem->SetLogName(szLogName);

	return pCItem;
}

//=============================================================================
// chCtrlType ��ɫ�������ͣ��ο�CompCommand.h EChaCtrlType
//=============================================================================
CCharacter* SubMap::ChaSpawn(Long lChaInfoID, Char chCtrlType, Short sAngle, Point *pSPos, bool bEyeshotAbility, dbc::cChar *cszChaName, const long clSearchRadius)
{
	CCharacter	*pCCha;
	CChaRecord	*pCChaRecord;

	if (!IsValidPos(pSPos->x, pSPos->y))
		return 0;

	pCChaRecord = GetChaRecordInfo(lChaInfoID);
	if (pCChaRecord == NULL)
		return 0;
	pCCha = g_pGameApp->GetNewCharacter();
	if (!pCCha)
		return 0;
	pCCha->m_CChaAttr.Init(lChaInfoID);
	if (chCtrlType == enumCHACTRL_NONE)
		chCtrlType = pCChaRecord->chCtrlType;
	pCCha->setAttr(ATTR_CHATYPE, chCtrlType);
	pCCha->m_pCChaRecord = pCChaRecord;
	pCCha->SetCat((short)(pCCha->m_pCChaRecord->lID));
	pCCha->SetID(g_pGameApp->m_Ident.GetID());
	pCCha->m_AIType = (BYTE)(pCChaRecord->lAiNo);
	pCCha->m_sChaseRange = (short)(pCChaRecord->lCDis);
	pCCha->SetAngle(sAngle);
	Square SShape = {*pSPos, pCCha->m_pCChaRecord->sRadii};
	if (!cszChaName)
		strcpy(pCCha->m_name, pCCha->m_pCChaRecord->szName);
	else
		strcpy(pCCha->m_name, cszChaName);
	pCCha->SetEyeshotAbility(bEyeshotAbility);
	if (pCChaRecord->sDormancy > 0)
		pCCha->SetExistState(enumEXISTS_SLEEPING);
	if (!Enter(&SShape, pCCha, clSearchRadius))
	{
		pCCha->Free();
		return 0;
	}
	Circle l_STerritory = {*pSPos, 500};
	pCCha->SetTerritory(l_STerritory);

	// ���뼼��
	pCCha->EnrichSkillBag();

	Char szLogName[defLOG_NAME_LEN] = "";
	sprintf(szLogName, "Cha-%s+%u", pCCha->GetName(), pCCha->GetID());
	pCCha->SetLogName(szLogName);

	// pCCha->ResetLifeTime(5000);
	
	return pCCha;
}

// ͨ�渱���ڵ��������
void SubMap::Notice(const char *szString)
{
	// Типизированная сериализация: системное уведомление карты
	auto WtPk = net::msg::serialize(net::msg::McSysInfoMessage{szString});

	CPlayer	*pHeadPlayer = 0, *pLastPlayer = 0;
	CEyeshotCell	*pCEyeCell;
	CCharacter		*pCCha;
	Long			lChaCount, lChaNum;
	m_CEyeshotCellL.BeginGet();
	while (pCEyeCell = m_CEyeshotCellL.GetNext())
	{
		lChaCount = 0;
		lChaNum = pCEyeCell->GetChaNum();
		pCCha = pCEyeCell->m_pCChaL;
		while (pCCha)
		{
			if (++lChaCount > lChaNum)
			{
				//LG("��Ұ�������", "��Ұ��Ԫ[%d,%d]ʵ��ʵ���� %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]fact entity nubmer{}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				break;
			}

			if(pCCha->IsPlayerFocusCha())
			{
				if (!pHeadPlayer)
				{
					pHeadPlayer = pCCha->GetPlayer();
					pLastPlayer = pHeadPlayer;
				}
				else
				{
					pLastPlayer->GetNextPlayer() = pCCha->GetPlayer();
					pLastPlayer = (CPlayer *)pLastPlayer->GetNextPlayer();
				}

				if (!pCCha->GetSubMap())
					//LG("��Ұ�������", "�ڽ��е�ͼͨ��ʱ��� %s(%s)[%d,%d] �ĵ�ͼΪ��\n",
					ToLogService("errors", LogLevel::Error, "in the wind map notify character {}({})[{},{}] 's map is empty",
						pCCha->GetLogName(), pCCha->GetPlyCtrlCha()->GetLogName(), pCCha->GetPos().x, pCCha->GetPos().y);
			}

			if (pCCha->m_pCEyeshotCellNext)
				pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
			else
				pCCha = 0;
		}
	}

	if (pLastPlayer)
		pLastPlayer->GetNextPlayer() = NULL;
	SENDTOCLIENT(WtPk, pHeadPlayer);
}

dbc::Long SubMap::CountEyeshotPlyActiveNum(dbc::Long lCellX, dbc::Long lCellY)
{
	Long	lActNum = 0;

	CCharacter		*pCCha;
	Long			lChaCount = 0, lChaNum;
	pCCha = m_pCEyeshotCell[lCellY][lCellX].m_pCChaL;
	lChaNum = m_pCEyeshotCell[lCellY][lCellX].GetChaNum();
	while (pCCha)
	{
		if (++lChaCount > lChaNum)
		{
			//LG("��Ұ�������", "������Ұ��Ԫ[%d,%d]�ļ����ɫ��ʱ��ʵ�ʽ�ɫ�� %d\n", lCellX, lCellY, lChaNum);
			ToLogService("errors", LogLevel::Error, "account eyeshot cell [{},{}]'s activation character number��practice character number{}", lCellX, lCellY, lChaNum);
			break;
		}

		if(pCCha->IsPlayerCha())
		{
			if (pCCha->GetEyeshotAbility())
				lActNum++;
		}

		if (pCCha->m_pCEyeshotCellNext)
			pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
		else
			pCCha = 0;
	}

	return lActNum;
}

// ���λ���Ƿ����ͨ��
bool SubMap::IsMoveAble(Entity *pCEnt, Long lPosX, Long lPosY)
{
	CFightAble	*pCCha = 0;
	if (!pCEnt || !(pCCha = pCEnt->IsFightAble()))
		return false;
	return g_IsMoveAble((char)pCCha->m_CChaAttr.GetAttr(ATTR_CHATYPE), pCCha->m_pCChaRecord->chTerritory, pCEnt->GetAreaAttr()); //�����ϰ�
}

BOOL SubMap::LoadEventEntity()
{
	g_pScriptMap = this;
	char szMapEntity[256];
	sprintf( szMapEntity, "%s\\%s%s", GetName(), GetName(), "entity.lua" );
	ReloadEntity( GetResPath(szMapEntity) );
	return TRUE;
}

BOOL SubMap::LoadNpc()
{
	if( m_pCMapRes->m_pNpcSpawn->Load( *this ) == -1 )
	{
		//THROW_EXCP( excpMem, "��ʼ����ͼNPC������Ϣ����!" );
		THROW_EXCP( excpMem, RES_STRING(GM_SUBMAP_CPP_00003) );
		return FALSE;
	}

	return TRUE;
}

CNpcRecord* SubMap::GetNpcInfo( USHORT sNpcID )
{
	if( m_pCMapRes->m_pNpcSpawn )
	{
		return m_pCMapRes->m_pNpcSpawn->GetNpcInfo( sNpcID );
	}
	return NULL;
}

// ������Ұ��Ԫ
void SubMap::Add(Entity* pCEnt)
{
	CCharacter	*pCCha = pCEnt->IsCharacter();
	CItem		*pCItem;
	Point		l_pt = pCEnt->GetPos();
	Rect		l_rect = GetEyeshot(l_pt);

	if (pCEnt->m_pCEyeshotHost)
	{
		//LG("��ͼ��ɫ��������", "���л�����ͼ %s ����Ұ��Ԫ[%d, %d]����ʵ�� %s ʱ��������û��������ǰ����Ұ��Ԫ[%d, %d]\n", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		ToLogService("errors", LogLevel::Error, "(switch) map {} to eyeshot cell [{}, {}]add entity {} ��find it is not break away foregone manage cell[{}, {}]", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		return;
	}
	pCEnt->m_pCEyeshotHost = &m_pCEyeshotCell[l_pt.y][l_pt.x];

	if (pCCha)
	{
		if (pCCha->IsPlayerCha())
		{
			pCCha->GetPlayer()->RefreshMapMask(GetName(), pCCha->GetPos().x / 100, pCCha->GetPos().y / 100);
			pCCha->Cmd_SetInGymkhana(CanPK());
			pCCha->Cmd_SetPKGuild(GetMapRes()->GetType() == 3);
		}

		if (pCCha->IsPlayerOwnCha())
		{
			m_lPlayerNum++;
//			m_lActivePlayerNum++;
		}
	}

	if (pCCha)
	{
		m_pCEyeshotCell[l_pt.y][l_pt.x].AddEntity(pCCha);

		Long l_radius = pCEnt->GetRadius();
		l_pt = pCEnt->GetPos();
		Rect l_range = GetHoldStateCell(l_pt, l_radius);
		for (long i = l_range.ltop.y; i <= l_range.rbtm.y; i++)
			for (long j = l_range.ltop.x; j <= l_range.rbtm.x; j++)
			{
				if (i != l_pt.y || j != l_pt.x)
				{
					//StateCellAddCha(j, i, pCCha, false);
				}
				else {
					StateCellAddCha(j, i, pCCha, true);
				}
			}
	}
	else if (pCItem = pCEnt->IsItem())
	{
		m_pCEyeshotCell[l_pt.y][l_pt.x].AddEntity(pCItem);
	}

	if( pCCha)
	{
		pCCha->EntryMapUnit( GetMapID(), WORD(l_pt.x), WORD(l_pt.y) );
	}
}

void SubMap::Delete(Entity* pCEnt)
{
	CCharacter	*pCCha = pCEnt->IsCharacter();
	Point		l_pt = pCEnt->GetPos();
	//const Rect	&m_area = GetRange();
	//if (l_pt.x < m_area.ltop.x || l_pt.x >= m_area.rbtm.x || l_pt.y < m_area.ltop.y || l_pt.y >= m_area.rbtm.y)
	//{
	//	LG("��ͼ��ɫ��������", "���л����ӵ�ͼ %s ɾ��ʵ�� %s ʱ�����ָ�ʵ���λ��[%d, %d]�Ƿ�\n", GetName(), pCEnt->GetLogName(), l_pt.x, l_pt.y);
	//	return;
	//}
	Rect		l_rect = GetEyeshot(l_pt);

	if (!pCEnt->m_pCEyeshotHost)
	{
		//LG("��ͼ��ɫ��������", "���л�����ͼ %s ����Ұ��Ԫ[%d, %d]ɾ��ʵ�� %s ʱ�����ֲ�����Ұ��Ԫ��\n", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName());
		ToLogService("errors", LogLevel::Error, "(switch)map {} from eyeshot[{}, {}] delete entity {} ��find it isn't in eyeshot cell.", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName());
		return;
	}
	if (pCEnt->m_pCEyeshotHost != &m_pCEyeshotCell[l_pt.y][l_pt.x])
	{
		//LG("��ͼ��ɫ��������", "���л�����ͼ %s ����Ұ��Ԫ[%d, %d]ɾ��ʵ�� %s ʱ�����������¼��Ұ��Ԫ[%d, %d]����\n", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		ToLogService("errors", LogLevel::Error, "(switch)map {} from eyeshot[{}, {}]delete entity {}��find it isn't agree with log eyeshot cell[{}, {}].", GetName(), l_pt.x, l_pt.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
		return;
	}
	pCEnt->m_pCEyeshotHost = 0;

	if (pCCha)
	{
		pCCha->Cmd_SetInGymkhana(false);
		pCCha->Cmd_SetPKGuild(false);

		if (pCCha->IsPlayerOwnCha())
		{
			m_lPlayerNum--;
			//if(pCCha->IsLiveing())
			//	m_lActivePlayerNum--;
		}
	}

	m_pCEyeshotCell[l_pt.y][l_pt.x].DelEntity(pCEnt);
	CStateCellNode	*pCNode = pCEnt->m_pCStateCellHead;
	if (pCCha)
	{
		while (pCNode)
		{
			StateCellDelCha(pCNode->m_pCStateCell->m_sPosX, pCNode->m_pCStateCell->m_sPosY, pCNode->m_pCChaNode);
			pCNode = pCNode->m_pCNext;
		}
	}
}

// ����ԭ״̬��Ԫ�������µ�״̬��Ԫ
void SubMap::MoveInStateCell(CCharacter* pCCha, const Point &SSrcPos, const Point &STarPos)
{
	Point	l_src = SSrcPos;
	Point	l_dst = STarPos;
	Long	lRadius = pCCha->GetRadius();
	const Rect l_srcTerr = GetHoldStateCell(l_src, lRadius);
	const Rect l_dstTerr = GetHoldStateCell(l_dst, lRadius);

	if (l_src == l_dst)
		return;

	Long		x, y;
	// ��Դ��Χɾ��
	CStateCellNode	*pCNode = pCCha->m_pCStateCellHead;
	if (pCCha)
	{
		while (pCNode)
		{
			StateCellDelCha(pCNode->m_pCStateCell->m_sPosX, pCNode->m_pCStateCell->m_sPosY, pCNode->m_pCChaNode);
			pCNode = pCNode->m_pCNext;
		}
	}
	// ��Ŀ�귶Χ����
	for (y = l_dstTerr.ltop.y; y <= l_dstTerr.rbtm.y; y++)
	{
		for (x = l_dstTerr.ltop.x; x <= l_dstTerr.rbtm.x; x++)
		{
			if (y != l_dst.y || x != l_dst.x)
			{
				//StateCellAddCha(x, y, pCCha, false); // ���뵽����������Ԫ
			}
			else
				StateCellAddCha(x, y, pCCha, true); // ���뵽���Ĺ�����Ԫ
		}
	}
}

void SubMap::MoveInMapMask(CCharacter* pCCha, const Point &SSrcPos, const Point &STarPos)
{
	if (!pCCha->IsPlayerCha())
		return;
	Point	l_src, l_dst;

	long	lStep = 4 * 100;
	l_src.x = SSrcPos.x / lStep;
	l_src.y = SSrcPos.y / lStep;
	l_dst.x = STarPos.x / lStep;
	l_dst.y = STarPos.y / lStep;
	if (l_src != l_dst)
		pCCha->GetPlayer()->RefreshMapMask(GetName(), STarPos.x / 100, STarPos.y / 100);
}

//void SubMap::Move(Entity* pCEnt, Point STarPos, Char chStep)
//{
//	Point	l_src = pCEnt->GetPos();
//	Point	l_dst = STarPos;
//	Long	lRadius = pCEnt->GetRadius();
//	const Rect l_srcTerr = GetTerritory(l_src, lRadius);
//	const Rect l_dstTerr = GetTerritory(l_dst, lRadius);
//
//	Long		x, y;
//	if (chStep == 1) // ��Դ��Χɾ��
//	{
//		//// log
//		//if (!strcmp("tty", pCEnt->GetName()))
//		//{
//		//	char	szPrint[512] = "";
//		//	LG("�ƶ��켣", "Դ  ��[%d,%d]--[%d,%d]��[%d,%d].\n",
//		//		l_srcTerr.ltop.x, l_srcTerr.ltop.y, l_srcTerr.rbtm.x, l_srcTerr.rbtm.y, l_src.x, l_src.y);
//		//	LG("�ƶ��켣", "Ŀ�꣺[%d,%d]--[%d,%d]��[%d,%d].\n",
//		//		l_dstTerr.ltop.x, l_dstTerr.ltop.y, l_dstTerr.rbtm.x, l_dstTerr.rbtm.y, l_dst.x, l_dst.y);
//
//		//	CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead;
//		//	while (pCNode)
//		//	{
//		//		pCNode = pCNode->m_pCNext;
//		//	}
//		//	LG("�ƶ��켣", "��ɫռ�õĵ�Ԫ��%s.\n", szPrint);
//		//}
//		////
//
//		CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead, *pCTempNode;
//		if (pCNode) // �׽ڵ�
//		{
//			pCTempNode = pCNode->m_pCNext;
//
//			x = pCNode->m_pCMgrUnit->m_sPosX;
//			y = pCNode->m_pCMgrUnit->m_sPosY;
//			if (x < l_dstTerr.ltop.x || x > l_dstTerr.rbtm.x
//				|| y < l_dstTerr.ltop.y || y > l_dstTerr.rbtm.y) // ����Ŀ�귶Χ��
//				pCNode->m_pCMgrUnit->DelEntity(pCNode->m_pCEntityNode);
//			else
//			{
//				if (l_src != l_dst) // ԭ�������ģ����ڲ���
//					m_pCMgrUnit[y][x]->SetEntityIn(pCNode->m_pCEntityNode, false);
//			}
//
//			pCNode = pCTempNode;
//		}
//		while (pCNode)
//		{
//			pCTempNode = pCNode->m_pCNext;
//
//			x = pCNode->m_pCMgrUnit->m_sPosX;
//			y = pCNode->m_pCMgrUnit->m_sPosY;
//			if (x < l_dstTerr.ltop.x || x > l_dstTerr.rbtm.x
//				|| y < l_dstTerr.ltop.y || y > l_dstTerr.rbtm.y) // ����Ŀ�귶Χ��
//				pCNode->m_pCMgrUnit->DelEntity(pCNode->m_pCEntityNode);
//			else
//			{
//				if (l_src != l_dst)
//				{
//					if (l_dst.x == x && l_dst.y == y) // ԭ���������ģ�������
//						m_pCMgrUnit[y][x]->SetEntityIn(pCNode->m_pCEntityNode);
//				}
//			}
//
//			pCNode = pCTempNode;
//		}
//
//		//// log
//		//if (!strcmp("tty", pCEnt->GetName()))
//		//{
//		//	char	szPrint[512] = "";
//		//	CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead;
//		//	while (pCNode)
//		//	{
//		//		pCNode = pCNode->m_pCNext;
//		//	}
//		//	LG("�ƶ��켣", "��Դɾ���󣬽�ɫռ�õĵ�Ԫ��%s.\n", szPrint);
//
//		//	LG("�ƶ��켣", "Դ��Χ��ɾ����ӵ�еĽ�ɫ��\n");
//		//	for (y = l_srcTerr.ltop.y; y <= l_srcTerr.rbtm.y; y++)
//		//		for (x = l_srcTerr.ltop.x; x <= l_srcTerr.rbtm.x; x++)
//		//		{
//		//			szPrint[0] = '\0';
//		//			CEntityListNode	*pCNode = m_pCMgrUnit[y][x]->m_pCChaIn;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("�ƶ��켣", "\t������[%d,%d]��%s\n", x, y, szPrint);
//		//			szPrint[0] = '\0';
//		//			pCNode = m_pCMgrUnit[y][x]->m_pCChaCross;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("�ƶ��켣", "\t������[%d,%d]��%s\n", x, y, szPrint);
//		//		}
//		//}
//		////
//	}
//	else if (chStep == 2) // ��Ŀ�귶Χ����
//	{
//		pCEnt->SetPos(STarPos);
//		if (l_src != l_dst)
//			pCEnt->RefreshArea();
//		for (y = l_dstTerr.ltop.y; y <= l_dstTerr.rbtm.y; y++)
//		{
//			for (x = l_dstTerr.ltop.x; x <= l_dstTerr.rbtm.x; x++)
//			{
//				if (x < l_srcTerr.ltop.x || x > l_srcTerr.rbtm.x
//					|| y < l_srcTerr.ltop.y || y > l_srcTerr.rbtm.y) // ����Դ��Χ��
//				{
//					if (y != l_dst.y || x != l_dst.x)
//						MgrUnitAddEntity(x, y, pCEnt, def_MGRUNIT_ENTITY_TYPE_CHACROSS); // ���뵽����������Ԫ
//					else
//						MgrUnitAddEntity(x, y, pCEnt, def_MGRUNIT_ENTITY_TYPE_CHAIN); // ���뵽���Ĺ�����Ԫ
//				}
//			}
//		}
//
//		//// log
//		//if (!strcmp("tty", pCEnt->GetName()))
//		//{
//		//	char	szPrint[512] = "";
//
//		//	CMgrNode	*pCNode = pCEnt->m_pCMgrNodeHead;
//		//	while (pCNode)
//		//	{
//		//		pCNode = pCNode->m_pCNext;
//		//	}
//		//	LG("�ƶ��켣", "��Ŀ�����Ӻ󣬽�ɫռ�õĵ�Ԫ��%s.\n", szPrint);
//
//		//	LG("�ƶ��켣", "Ŀ�귶Χ�����Ӻ�ӵ�еĽ�ɫ��\n");
//		//	for (y = l_dstTerr.ltop.y; y <= l_dstTerr.rbtm.y; y++)
//		//		for (x = l_dstTerr.ltop.x; x <= l_dstTerr.rbtm.x; x++)
//		//		{
//		//			szPrint[0] = '\0';
//		//			CEntityListNode	*pCNode = m_pCMgrUnit[y][x]->m_pCChaIn;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("�ƶ��켣", "\t������[%d,%d]��%s\n", x, y, szPrint);
//		//			szPrint[0] = '\0';
//		//			pCNode = m_pCMgrUnit[y][x]->m_pCChaCross;
//		//			while (pCNode)
//		//			{
//		//				pCNode = pCNode->m_pCNext;
//		//			}
//		//			LG("�ƶ��켣", "\t������[%d,%d]��%s\n", x, y, szPrint);
//		//		}
//		//	LG("�ƶ��켣", "\n");
//		//}
//		////
//	}
//}
//
//=============================================================================
// ���븱��������ɹ����������Ұ��Ԫ��������Ұͨ�棩
// bActiveMgr �Ƿ�ἤ�������Ԫ
//=============================================================================
bool SubMap::Enter(Square* pSEntShape, Entity * ent, cLong clSearchRadius)
{
	ent->SetInitShape(*pSEntShape);

	const	Point l_pt = pSEntShape->centre;
	bool	l_retval = true;
	Point	l_pt2, l_pt1;

	l_pt1 = l_pt;
	Rect	l_rect = GetEyeshot(l_pt1);
	long	lStep = pSEntShape->radius;

	if (lStep == 0) // ���������뾶Ϊ0�����
		lStep = 40;

	//ȷ����ʼλ��
	ent->m_submap	=this;
	long l_xdlt	=0,l_ydlt	=0;
	
	if (clSearchRadius > 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
		{
			long l_dist =0;
			bool l_overflag =true;
			while(l_overflag) //ֱ��ȷ��λ��Ϊֹ
			{
				l_dist++;
				for(short dir=0;dir<4;dir++){
					l_pt1	=l_pt;
					//long l_radius	=2 * lStep * l_dist;
					long l_radius	=GetBlockCellWidth() * l_dist;
					if(l_radius >clSearchRadius){
						l_retval	=false;
						l_overflag	=false;
						break;
					}
					l_pt1.move(dir*90,l_radius);
					l_pt2	=l_pt1;
					l_rect =GetEyeshot(l_pt2);

					ent->SetPos(l_pt1);
					l_xdlt	=l_ydlt		=0;

					if(!(l_overflag =ent->overlap(l_xdlt,l_ydlt))){
						l_retval	=true;
						break;
					}
				}
			}
		}
	}
	else if (clSearchRadius == 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
			l_retval = false;
	}
	else // ǿ�ƽ���
	{}
	//beginsee
	if(l_retval)
	{
		bool	bActive = ent->GetEyeshotAbility();

		for(long y =l_rect.ltop.y;y <=l_rect.rbtm.y;y++)
		{
			for(long x =l_rect.ltop.x;x <=l_rect.rbtm.x;x++)
			{
				if (bActive)
					ActiveEyeshotCell(x, y);

				m_pCEyeshotCell[y][x].EnterEyeshot(ent);
			}
		}

		//����
		ent->RefreshArea();
		Add(ent);		
		ent->m_lastpos	=ent->GetPos();
	}
	else
		ent->m_submap = 0;


	return l_retval;
}

// ģ��Enter���̣�ȷ������λ�ã�����ִ�н��븱������
bool SubMap::EnsurePos(Square* pSEntShape, Entity * ent, cLong clSearchRadius)
{
	ent->SetInitShape(*pSEntShape);

	const	Point l_pt = pSEntShape->centre;
	bool	l_retval = true;
	Point	l_pt2, l_pt1;

	l_pt1 = l_pt;
	long	lStep = pSEntShape->radius;

	if (lStep == 0) // ���������뾶Ϊ0�����
		lStep = 40;

	//ȷ����ʼλ��
	ent->m_submap	=this;
	long l_xdlt	=0,l_ydlt	=0;
	
	if (clSearchRadius > 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
		{
			long l_dist =0;
			bool l_overflag =true;
			while(l_overflag) //ֱ��ȷ��λ��Ϊֹ
			{
				l_dist++;
				for(short dir=0;dir<6;dir++){
					l_pt1	=l_pt;
					long l_radius	=2 * lStep * l_dist;
					if(l_radius >clSearchRadius){
						l_retval	=false;
						l_overflag	=false;
						break;
					}
					l_pt1.move(dir*60,l_radius);
					l_pt2	=l_pt1;

					ent->SetPos(l_pt1);
					l_xdlt	=l_ydlt		=0;

					if(!(l_overflag =ent->overlap(l_xdlt,l_ydlt))){
						l_retval	=true;
						break;
					}
				}
			}
		}
	}
	else if (clSearchRadius == 0)
	{
		if(ent->overlap(l_xdlt,l_ydlt))
			l_retval = false;
	}
	else // ǿ�ƽ���
	{}
	//beginsee
	if(!l_retval)
		ent->m_submap = 0;


	return l_retval;
}

//=============================================================================
// ��������������Ұ��Ԫ��������Ұͨ��
// bActiveMgr �Ƿ�Թ�����Ԫ�ļ�������Ӱ��
//=============================================================================
void SubMap::GoOut(Entity * ent)
{
	Point l_pt =ent->GetShape().centre;
	Rect l_rect =GetEyeshot(l_pt);
	//ɾ��
	Delete(ent);
	//endsee

	bool	bActive = ent->GetEyeshotAbility();

	for(long y =l_rect.ltop.y;y <=l_rect.rbtm.y;y++)
	{
		for(long x =l_rect.ltop.x;x <=l_rect.rbtm.x;x++)
		{
			if (bActive)
				InactiveEyeshotCell(x, y);

			m_pCEyeshotCell[y][x].OutEyeshot(ent);
		}
	}

	ent->m_submap =0;
}

// ��Ұ�ڵ�������Ұ��Ԫ������Ұˢ��
void SubMap::RefreshEyeshot(Entity *pCEnt, bool bEyeshot, bool bHide, bool bShow)
{
	Point l_pt = pCEnt->GetShape().centre;
	Rect l_rect = GetEyeshot(l_pt);

	for(long y =l_rect.ltop.y;y <=l_rect.rbtm.y;y++)
	{
		for(long x =l_rect.ltop.x;x <=l_rect.rbtm.x;x++)
		{
			m_pCEyeshotCell[y][x].RefreshEyeshot(pCEnt, bEyeshot, bHide, bShow);
		}
	}
}

Rect SubMap::GetEyeshot(Point &pt)const
{
	const Rect	&m_area = GetRange();
	Rect l_rect;
	pt.x	=(pt.x - m_area.ltop.x)/GetEyeshotCellWidth();
	pt.y	=(pt.y - m_area.ltop.y)/GetEyeshotCellHeight();
	l_rect.ltop.x	=max(pt.x -GetEyeshotWidth(),0);
	l_rect.ltop.y	=max(pt.y -GetEyeshotWidth(),0);
	l_rect.rbtm.x	=min(pt.x +GetEyeshotWidth(),GetEyeshotCellCol() -1);
	l_rect.rbtm.y	=min(pt.y +GetEyeshotWidth(),GetEyeshotCellLin() -1);
	return l_rect;
}

Rect SubMap::GetEyeshot(short sMgrUnitX, short sMgrUnitY)const
{
	Rect	l_rect;

	l_rect.ltop.x = max(sMgrUnitX - GetEyeshotWidth(), 0);
	l_rect.ltop.y = max(sMgrUnitY - GetEyeshotWidth(), 0);
	l_rect.rbtm.x = min(sMgrUnitX + GetEyeshotWidth(), GetEyeshotCellCol() -1);
	l_rect.rbtm.y = min(sMgrUnitY + GetEyeshotWidth(), GetEyeshotCellLin() -1);

	return l_rect;
}

void SubMap::GetEyeshotCenter(Point &pt)
{
	const Rect	&m_area = GetRange();
	pt.x	=(pt.x - m_area.ltop.x) / GetEyeshotCellWidth();
	pt.y	=(pt.y - m_area.ltop.y) / GetEyeshotCellHeight();
}

Rect SubMap::GetHoldStateCell(Point &pt, Long lRadius) const 
{
	const Rect	&m_area = GetRange();
	Rect l_rect;
	if (lRadius > 0)
	{
		l_rect.ltop.x = (pt.x - lRadius - m_area.ltop.x) / GetStateCellWidth();
		l_rect.ltop.y = (pt.y - lRadius - m_area.ltop.y) / GetStateCellHeight();
		l_rect.rbtm.x = (pt.x + lRadius - m_area.ltop.x) / GetStateCellWidth();
		l_rect.rbtm.y = (pt.y + lRadius - m_area.ltop.x) / GetStateCellHeight();

		if (l_rect.ltop.x < 0) l_rect.ltop.x = 0;
		if (l_rect.rbtm.x >= GetStateCellCol()) l_rect.rbtm.x = GetStateCellCol() -1;
		if (l_rect.ltop.y < 0) l_rect.ltop.y = 0;
		if (l_rect.rbtm.y >= GetStateCellLin()) l_rect.rbtm.y = GetStateCellLin() -1;
	}
	else
	{
		l_rect.ltop.x = pt.x / GetStateCellWidth();
		l_rect.ltop.y = pt.y / GetStateCellHeight();
		l_rect.rbtm.x = pt.x / GetStateCellWidth();
		l_rect.rbtm.y = pt.y / GetStateCellHeight();
	}
	pt.x = (pt.x - m_area.ltop.x) / GetStateCellWidth();
	pt.y = (pt.y - m_area.ltop.y) / GetStateCellHeight();

	return l_rect;
}

void SubMap::GetHoldStateCellCenter(Point &pt)
{
	const Rect	&m_area = GetRange();
	pt.x = (pt.x - m_area.ltop.x) / GetStateCellWidth();
	pt.y = (pt.y - m_area.ltop.y) / GetStateCellHeight();
}

//===============Search===================================================================================
CCharacter*	SubMap::FindCharacter( dbc::uLong ulID, const Point& point )
{
	CCharacter* pCha = NULL;
	Long	lRangeB[] = {point.x, point.y, 0};
	Long	lRangeE[] = {enumRANGE_TYPE_CIRCLE, 10 * 100};
	BeginSearchInRange(lRangeB, lRangeE);
	while (pCha = GetNextCharacterInRange())
	{
		if(pCha->GetID() == ulID)
			break;
	}

	return pCha;
}

//=============================================================================
// plRangeBParam ����������������� defSKILL_RANGE_BASEP_NUM�� ���� �����������꣬����
// plRangeEParam ������չ���������� defSKILL_RANGE_EXTEP_NUM�� ���� ��Χ���ͣ����Ͳ���
// bIncludeHideEnti �Ƿ����������ʵ��
//=============================================================================
void SubMap::BeginSearchInRange(Long *plRangeBParam, Long *plRangeEParam, bool bIncludeHideEnti)
{
    m_sRangeCurMgrUnit = -1;
	m_pRangeCurEntiNode = 0;
	m_bIncludeHideEnti = bIncludeHideEnti;

	Long	lCx = plRangeBParam[0];
	Long	lCy = plRangeBParam[1];
	Long	lAngle = plRangeBParam[2];
	Long	lRangeType = plRangeEParam[0];

	Long	lUnitSX, lUnitEX, lUnitSY, lUnitEY;
	Long	lMaxRadius;
	if (lRangeType == enumRANGE_TYPE_STICK)
	{
		Long	lRadius = plRangeEParam[1];
		Long	lWidth = plRangeEParam[2];

		m_pCBaseRange = &m_CStickRange;
		m_CStickRange.setPos(lCx, lCy);
		m_CStickRange.setAngle(lAngle);
		m_CStickRange.setRadius(lRadius);
		m_CStickRange.setWidth(lWidth);

		lMaxRadius = (Long)sqrt(double(lRadius * lRadius + (lWidth / 2) * (lWidth / 2)));
	}
	else if (lRangeType == enumRANGE_TYPE_FAN)
	{
		Long	lRadius = plRangeEParam[1];
		Long	lAngleD = plRangeEParam[2];

		m_pCBaseRange = &m_CFanRange;
		m_CFanRange.setPos(lCx, lCy);
		lAngle = lAngle - lAngleD / 2;
		if (lAngle < 0)
			lAngle += 360;
		m_CFanRange.setAngle(lAngle);
		m_CFanRange.setAngleStep(lAngleD);
		m_CFanRange.setRadius(lRadius);

		lMaxRadius = lRadius;
	}
	else if (lRangeType == enumRANGE_TYPE_SQUARE)
	{
		Long	lRadius = plRangeEParam[1];

		m_pCBaseRange = &m_CSquareCRange;
		m_CSquareCRange.setPos(lCx, lCy);
		m_CSquareCRange.setAngle(lAngle);
		m_CSquareCRange.setRadius(lRadius);

		lMaxRadius = lRadius;
	}
	else if (lRangeType == enumRANGE_TYPE_CIRCLE)
	{
		Long	lRadius = plRangeEParam[1];

		m_pCBaseRange = &m_CCircleRange;
		m_CCircleRange.setPos(lCx, lCy);
		m_CCircleRange.setRadius(lRadius);

		lMaxRadius = lRadius;
	}
	else
		m_pCBaseRange = 0;

	if (!m_pCBaseRange)
		return;

	m_lRangeCentUnit[0] = lCx / GetStateCellWidth();
	m_lRangeCentUnit[1] = lCy / GetStateCellHeight();

	lUnitSX = (lCx - lMaxRadius) / GetStateCellWidth();
	lUnitEX = (lCx + lMaxRadius) / GetStateCellWidth();
	lUnitSY = (lCy - lMaxRadius) / GetStateCellHeight();
	lUnitEY = (lCy + lMaxRadius) / GetStateCellHeight();
	lUnitSX = lUnitSX < 0 ? 0 : lUnitSX;
	lUnitEX = lUnitEX > GetStateCellCol() -1 ? GetStateCellCol() -1 : lUnitEX;
	lUnitSY = lUnitSY < 0 ? 0 : lUnitSY;
	lUnitEY = lUnitEY > GetStateCellLin() -1 ? GetStateCellLin() -1 : lUnitEY;

	m_sRangeMgrUnitNum = 0;
	Long	sx, sy, ex, ey;
	for (int i = lUnitSY; i <= lUnitEY; i++)
		for (int j = lUnitSX; j <= lUnitEX; j++)
		{
			sx = j * GetStateCellWidth();
			ex = sx + GetStateCellWidth() - 1;
			sy = i * GetStateCellHeight();
			ey = sy + GetStateCellHeight() - 1;
			if (m_pCBaseRange->RectHitTest(sx, sy, ex, ey)) // ������Ԫ�ڷ�Χ��
			{
				m_lRangeMgrUnit[m_sRangeMgrUnitNum][0] = j;
				m_lRangeMgrUnit[m_sRangeMgrUnitNum][1] = i;
				m_sRangeMgrUnitNum++;
				if (m_sRangeMgrUnitNum >= defRANGE_MGRUNIU_NUM)
				{
					//MessageBox(NULL, "���������ķ�Χ�����趨ֵ", "����", MB_OK);
					MessageBox(NULL, RES_STRING(GM_SUBMAP_CPP_00004), RES_STRING(GM_SUBMAP_CPP_00005), MB_OK);
					return;
				}
			}
		}
}

CCharacter* SubMap::GetNextCharacterInRange(void)
{
	if (!m_pCBaseRange)
		return 0;

Research:
	if (m_pRangeCurEntiNode)
		m_pRangeCurEntiNode = m_pRangeCurEntiNode->m_pCNext;

	while (!m_pRangeCurEntiNode)
	{
		m_sRangeCurMgrUnit++;
		if (m_sRangeCurMgrUnit >= m_sRangeMgrUnitNum)
			return 0;
		if (m_pCStateCell[m_lRangeMgrUnit[m_sRangeCurMgrUnit][1]][m_lRangeMgrUnit[m_sRangeCurMgrUnit][0]])
			m_pRangeCurEntiNode = m_pCStateCell[m_lRangeMgrUnit[m_sRangeCurMgrUnit][1]][m_lRangeMgrUnit[m_sRangeCurMgrUnit][0]]->m_pCChaIn;
	}

	if (m_pRangeCurEntiNode)
	{
		if (!m_bIncludeHideEnti)
		{
			CCharacter	*pCCha = m_pRangeCurEntiNode->m_pCCha;
			if (pCCha && pCCha->IsHide())
				goto Research;
			else
				return pCCha;
		}
		else
			return m_pRangeCurEntiNode->m_pCCha;
	}
	else
		return 0;
}

//=============================================================================
// ������BeginSearchInRange�趨�ķ�Χ������״̬
//=============================================================================
bool SubMap::RangeAddState(uChar uchFightID, uLong ulSrcWorldID, Long lSrcHandle,
						   Char chObjType, Char chObjHabitat, Char chEffType, Short *sStateParam)
{
	if (sStateParam[0] > AREA_STATE_MAXID || sStateParam[1] > SKILL_STATE_LEVEL)
		return false;

	if (!m_pCBaseRange)
		return false;

	CSkillStateRecord	*pSStateR = 0;
	pSStateR = GetCSkillStateRecordInfo(sStateParam[0]);
	if (!pSStateR)
		return false;

	Long	x, y;
	uLong	ulStartTick = GetTickCount();
	bool	bAddSuc;
	bool	bAlreadyHas;
	for (Short i = 0; i < m_sRangeMgrUnitNum; i++)
	{
		bAddSuc = false;
		bAlreadyHas = false;
		x = m_lRangeMgrUnit[i][0], y = m_lRangeMgrUnit[i][1];

		if (m_pCStateCell[y][x] && m_pCStateCell[y][x]->m_CSkillState.HasState((uChar)sStateParam[0]))
			bAlreadyHas = true;
		if (x == m_lRangeCentUnit[0] && y == m_lRangeCentUnit[1])
			bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (uChar)sStateParam[0], (uChar)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 1);
		else
			bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (uChar)sStateParam[0], (uChar)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 0);
		if (!bAlreadyHas && bAddSuc)
		{
			NotiStateCellToEyeshot((short)x, (short)y);
		}
	}

	return true;
}

bool SubMap::RangeAddState(Rect *pSRange, uChar uchFightID, uLong ulSrcWorldID, Long lSrcHandle,
						   Char chObjType, Char chObjHabitat, Char chEffType, Short *sStateParam)
{
	if (sStateParam[0] > AREA_STATE_MAXID || sStateParam[1] > SKILL_STATE_LEVEL)
		return false;

	CSkillStateRecord	*pSStateR = 0;
	pSStateR = GetCSkillStateRecordInfo(sStateParam[0]);
	if (!pSStateR)
		return false;

	Long	lUnitSX, lUnitEX, lUnitSY, lUnitEY, lUnitCX, lUnitCY;
	lUnitSX = pSRange->ltop.x / GetStateCellWidth();
	lUnitEX = pSRange->rbtm.x / GetStateCellWidth();
	lUnitSY = pSRange->ltop.y / GetStateCellHeight();
	lUnitEY = pSRange->rbtm.y / GetStateCellHeight();
	lUnitSX = lUnitSX < 0 ? 0 : lUnitSX;
	lUnitEX = lUnitEX > GetStateCellCol() -1 ? GetStateCellCol() -1 : lUnitEX;
	lUnitSY = lUnitSY < 0 ? 0 : lUnitSY;
	lUnitEY = lUnitEY > GetStateCellLin() -1 ? GetStateCellLin() -1 : lUnitEY;

	lUnitCX = lUnitSX + (lUnitEX - lUnitSX) / 2;
	lUnitCY = lUnitSY + (lUnitEY - lUnitSY) / 2;

	uLong	ulStartTick = GetTickCount();
	bool	bAddSuc;
	bool	bAlreadyHas;
	for (Long y = lUnitSY; y <= lUnitEY; y++)
		for (Long x = lUnitSX; x <= lUnitEX; x++)
		{
			bAddSuc = false;
			bAlreadyHas = false;

			if (m_pCStateCell[y][x] && m_pCStateCell[y][x]->m_CSkillState.HasState((uChar)sStateParam[0]))
				bAlreadyHas = true;
			if (y == lUnitCY && x == lUnitCX)
				bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (uChar)sStateParam[0], (uChar)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 1);
			else
				bAddSuc = AddCellState(uchFightID, ulSrcWorldID, lSrcHandle, chObjType, chObjHabitat, chEffType, x, y, (uChar)sStateParam[0], (uChar)sStateParam[1], ulStartTick, sStateParam[2], pSStateR->chAddType, 0);
			if (!bAlreadyHas && bAddSuc)
			{
				ActiveEyeshotCell(m_pCStateCell[y][x]->m_pCEyeshotCell->m_sPosX, m_pCStateCell[y][x]->m_pCEyeshotCell->m_sPosY); // ״̬���������Ԫ
				NotiStateCellToEyeshot((short)x, (short)y);
			}
		}

	return true;
}

void SubMap::NotiStateCellToEyeshot(Short sCellX, Short sCellY)
{
	if (!m_pCStateCell[sCellY][sCellX])
		return;

	// Типизированная сериализация: появление состояний ячейки
	auto pk = net::msg::serialize(net::msg::McAStateBeginSeeMessage{
		static_cast<int64_t>(sCellX), static_cast<int64_t>(sCellY),
		m_pCStateCell[sCellY][sCellX]->m_CSkillState.BuildStateEntries()
	});

	Rect	l_rect = GetEyeshot(m_pCStateCell[sCellY][sCellX]->m_pCEyeshotCell->m_sPosX, m_pCStateCell[sCellY][sCellX]->m_pCEyeshotCell->m_sPosY);
	Entity		*pCEnt;
	CCharacter	*pCCha;
	CPlayer	*pHeadPlayer = 0, *pLastPlayer = 0;
	for (long y = l_rect.ltop.y; y <= l_rect.rbtm.y; y++)
	{
		for (long x = l_rect.ltop.x; x <= l_rect.rbtm.x; x++)
		{
			pCEnt = m_pCEyeshotCell[y][x].m_pCChaL;
			while (pCEnt)
			{
				pCCha = pCEnt->IsCharacter();
				if(pCCha->IsPlayerFocusCha())
				{
					if (!pHeadPlayer)
					{
						pHeadPlayer = pCCha->GetPlayer();
						pLastPlayer = pHeadPlayer;
					}
					else
					{
						pLastPlayer->GetNextPlayer() = pCCha->GetPlayer();
						pLastPlayer = (CPlayer *)pLastPlayer->GetNextPlayer();
					}
				}
				pCEnt = pCEnt->m_pCEyeshotCellNext;
			}
		}
	}
	if (pLastPlayer)
		pLastPlayer->GetNextPlayer() = NULL;
	SENDTOCLIENT(pk, pHeadPlayer);
}

//=============================================================================
// �ƶ����ƶ�λ�ã���Ұ��
//=============================================================================
void SubMap::MoveTo(Entity *pCEnt, const Point &STar)
{
	if (pCEnt->GetPos() != pCEnt->m_lastpos)
	{
		Char	szMess[512];
		sprintf(szMess, "character %s move originality coordinate error��last time position[%d, %d]��current position[%d, %d]��aim position[%d, %d]",
			pCEnt->GetLogName(), pCEnt->m_lastpos.x, pCEnt->m_lastpos.y, pCEnt->GetPos().x, pCEnt->GetPos().y, STar.x, STar.y);
		//::MessageBox(0,szMess,"�����!",MB_OK);
		//LG("�ƶ�����", "%s\n", szMess);
		ToLogService("errors", LogLevel::Error, "{}", szMess);
		pCEnt->SetPos(pCEnt->m_lastpos);
	}
	Point	l_src = pCEnt->GetPos();
	Point	l_dst = STar;
	Point	SrcPos = l_src;
	const Rect l_srcEyeshot = GetEyeshot(l_src);
	const Rect l_dstEyeshot = GetEyeshot(l_dst);

	MPTimer tMoveState, tMoveMMask, tMoveEyeshot, tMoveArea;
	tMoveState.Begin();
	MoveInStateCell(pCEnt->IsCharacter(), pCEnt->GetPos(), STar);
	tMoveState.End();
	tMoveMMask.Begin();
	MoveInMapMask(pCEnt->IsCharacter(), pCEnt->GetPos(), STar);
	tMoveMMask.End();
	tMoveEyeshot.Begin();
	pCEnt->SetPos(STar);
	if (l_src != l_dst) // �ӽǲ��ص�
	{
		//��Դɾ��
		if (!pCEnt->m_pCEyeshotHost)
		{
			//LG("��ͼ��ɫ��������", "���ƶ�����ͼ %s ����Ұ��Ԫ[%d, %d]ɾ��ʵ�� %s ʱ�����ֲ�����Ұ��Ԫ��\n", GetName(), l_src.x, l_src.y, pCEnt->GetLogName());
			ToLogService("errors", LogLevel::Error, "(move)map  {} from eyeshot cell[{}, {}]delete entity {} ��find it isn't in the eyeshot cell.", GetName(), l_src.x, l_src.y, pCEnt->GetLogName());
			return;
		}
		if (pCEnt->m_pCEyeshotHost != &m_pCEyeshotCell[l_src.y][l_src.x])
		{
			//LG("��ͼ��ɫ��������", "���ƶ�����ͼ %s ����Ұ��Ԫ[%d, %d]ɾ��ʵ�� %s ʱ�����������¼��Ұ��Ԫ[%d, %d]����\n", GetName(), l_src.x, l_src.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			ToLogService("errors", LogLevel::Error, "(move)map {} from eyeshot cell[{}, {}]delete entity {} ,find it isn't agree with log eyeshot cell[{}, {}].", GetName(), l_src.x, l_src.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			return;
		}
		pCEnt->m_pCEyeshotHost = 0;
		m_pCEyeshotCell[l_src.y][l_src.x].DelEntity(pCEnt);

		bool	bActive = pCEnt->GetEyeshotAbility();

		////beginsee and endsee
		//long	lXDist, lYDist, lXStep, lYStep, lSrcXStart, lTarXStart, lSrcYStart, lTarYStart;
		//lXDist = abs(l_src.x - l_dst.x);
		//if (lXDist > GetEyeshotWidth() * 2 + 1)
		//	lXDist = GetEyeshotWidth() * 2 + 1;
		//if (lXDist > 0)
		//{
		//	if (l_src.x >= l_dst.x)
		//	{
		//		if (l_srcEyeshot.rbtm.x == GetEyeshotCellCol() - 1)
		//			lSrcXStart = l_src.x + GetEyeshotWidth() - lXDist + 1;
		//		else
		//			lSrcXStart = l_srcEyeshot.rbtm.x - lXDist + 1;
		//		if (l_dstEyeshot.ltop.x == 0)
		//			lTarXStart = l_dst.x - GetEyeshotWidth();
		//		else
		//			lTarXStart = l_dstEyeshot.ltop.x;
		//	}
		//	else
		//	{
		//		if (l_srcEyeshot.ltop.x == 0)
		//			lSrcXStart = l_src.x - GetEyeshotWidth();
		//		else
		//			lSrcXStart = l_srcEyeshot.ltop.x;
		//		if (l_dstEyeshot.rbtm.x == GetEyeshotCellCol() - 1)
		//			lTarXStart = l_dst.x + GetEyeshotWidth() - lXDist + 1;
		//		else
		//			lTarXStart = l_dstEyeshot.rbtm.x - lXDist + 1;
		//	}

		//	for (long x = 0; x < lXDist; x++)
		//	{
		//		lXStep = lSrcXStart + x;
		//		if ((lXStep >= 0) && (lXStep <= GetEyeshotCellCol() - 1))
		//		{
		//			for (long y = l_srcEyeshot.ltop.y; y <= l_srcEyeshot.rbtm.y; y++)
		//			{
		//				if (bActive)
		//					InactiveEyeshotCell(lXStep, y);
		//				m_pCEyeshotCell[y][lXStep].OutEyeshot(pCEnt);
		//			}
		//		}
		//		lXStep = lTarXStart + x;
		//		if ((lXStep >= 0) && (lXStep <= GetEyeshotCellCol() - 1))
		//		{
		//			for (long y = l_dstEyeshot.ltop.y; y <= l_dstEyeshot.rbtm.y; y++)
		//			{
		//				if (bActive)
		//					ActiveEyeshotCell(lXStep, y);
		//				m_pCEyeshotCell[y][lXStep].EnterEyeshot(pCEnt);
		//			}
		//		}
		//	}
		//}

		//lXDist = abs(l_src.x - l_dst.x);
		//lYDist = abs(l_src.y - l_dst.y);
		//if ((lYDist > 0) && (lXDist < GetEyeshotWidth() * 2 + 1))
		//{
		//	lXDist = GetEyeshotWidth() * 2 + 1 - lXDist;
		//	if (l_src.x >= l_dst.x)
		//	{
		//		if (l_srcEyeshot.ltop.x == 0)
		//		{
		//			lSrcXStart = 0;
		//			lXDist += l_src.x - GetEyeshotWidth();
		//		}
		//		else
		//			lSrcXStart = l_srcEyeshot.ltop.x;
		//	}
		//	else
		//	{
		//		if (l_dstEyeshot.ltop.x == 0)
		//		{
		//			lSrcXStart = 0;
		//			lXDist += l_dst.x - GetEyeshotWidth();
		//		}
		//		else
		//			lSrcXStart = l_dstEyeshot.ltop.x;
		//	}
		//	if (lYDist > GetEyeshotWidth() * 2 + 1)
		//		lYDist = GetEyeshotWidth() * 2 + 1;
		//	if (l_src.y >= l_dst.y)
		//	{
		//		if (l_srcEyeshot.rbtm.y == GetEyeshotCellLin() - 1)
		//			lSrcYStart = l_src.y + GetEyeshotWidth() - lYDist + 1;
		//		else
		//			lSrcYStart = l_srcEyeshot.rbtm.y - lYDist + 1;
		//		if (l_dstEyeshot.ltop.y == 0)
		//			lTarYStart = l_dst.y - GetEyeshotWidth();
		//		else
		//			lTarYStart = l_dstEyeshot.ltop.y;
		//	}
		//	else
		//	{
		//		if (l_srcEyeshot.ltop.y == 0)
		//			lSrcYStart = l_src.y - GetEyeshotWidth();
		//		else
		//			lSrcYStart = l_srcEyeshot.ltop.y;
		//		if (l_dstEyeshot.rbtm.y == GetEyeshotCellLin() - 1)
		//			lTarYStart = l_dst.y + GetEyeshotWidth() - lYDist + 1;
		//		else
		//			lTarYStart = l_dstEyeshot.rbtm.y - lYDist + 1;
		//	}
		//	for (long x = 0; x < lXDist; x++)
		//	{
		//		lXStep = lSrcXStart + x;
		//		for (long y = 0; y < lYDist; y++)
		//		{
		//			lYStep = lSrcYStart + y;
		//			if ((lYStep >= 0) && (lYStep <= GetEyeshotCellLin() - 1))
		//			{
		//				if (bActive)
		//					InactiveEyeshotCell(lXStep, lYStep);
		//				m_pCEyeshotCell[lYStep][lXStep].OutEyeshot(pCEnt);
		//			}

		//			lYStep = lTarYStart + y;
		//			if ((lYStep >= 0) && (lYStep <= GetEyeshotCellLin() - 1))
		//			{
		//				if (bActive)
		//					ActiveEyeshotCell(lXStep, lYStep);
		//				m_pCEyeshotCell[lYStep][lXStep].EnterEyeshot(pCEnt);
		//			}
		//		}
		//	}
		//}

		const long l_xmin = min(l_srcEyeshot.ltop.x, l_dstEyeshot.ltop.x);
		const long l_xmax = max(l_srcEyeshot.rbtm.x, l_dstEyeshot.rbtm.x);
		const long l_ymin = min(l_srcEyeshot.ltop.y, l_dstEyeshot.ltop.y);
		const long l_ymax = max(l_srcEyeshot.rbtm.y, l_dstEyeshot.rbtm.y);
		for (long y = l_ymin; y <= l_ymax; y++)
		{
			for(long x = l_xmin; x <= l_xmax; x++)
			{
				const long l_srcx = abs(x - l_src.x);
				const long l_srcy = abs(y - l_src.y);
				const long l_dstx = abs(x - l_dst.x);
				const long l_dsty = abs(y - l_dst.y);
				if (l_srcx <= GetEyeshotWidth() && l_srcy <= GetEyeshotWidth()
					&& l_dstx <= GetEyeshotWidth() && l_dsty <= GetEyeshotWidth()) //�ཻ����
					continue;
				else if ((l_srcx > GetEyeshotWidth() || l_srcy > GetEyeshotWidth())
					&& (l_dstx > GetEyeshotWidth() || l_dsty > GetEyeshotWidth())) //�޹�����
					continue;
				else if (abs(x - l_src.x) <= GetEyeshotWidth() && abs(y - l_src.y) <= GetEyeshotWidth()) //Դ�鸽���ģ�endsee
				{
					if (bActive)
						InactiveEyeshotCell(x, y);
					m_pCEyeshotCell[y][x].OutEyeshot(pCEnt);
				}
				else		//Ŀ��鸽���ģ�beginsee
				{
					if (bActive)
						ActiveEyeshotCell(x, y);
					m_pCEyeshotCell[y][x].EnterEyeshot(pCEnt);
				}
			}
		}

		//����Ŀ��
		if (pCEnt->m_pCEyeshotHost)
		{
			//LG("��ͼ��ɫ��������", "���ƶ�����ͼ %s ����Ұ��Ԫ[%d, %d]����ʵ�� %s ʱ��������û��������ǰ����Ұ��Ԫ[%d, %d]\n", GetName(), l_dst.x, l_dst.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			ToLogService("errors", LogLevel::Error, "(move)map {} from eyeshot cell[{}, {}] add entity {} ��find it is not break away foregone manage cell[{}, {}]", GetName(), l_dst.x, l_dst.y, pCEnt->GetLogName(), pCEnt->m_pCEyeshotHost->m_sPosX, pCEnt->m_pCEyeshotHost->m_sPosY);
			return;
		}
		pCEnt->m_pCEyeshotHost = &m_pCEyeshotCell[l_dst.y][l_dst.x];
		m_pCEyeshotCell[l_dst.y][l_dst.x].AddEntity(pCEnt->IsCharacter());
	}
	tMoveEyeshot.End();

	tMoveArea.Begin();
	pCEnt->RefreshArea(&SrcPos);
	pCEnt->m_lastpos = STar;
	tMoveArea.End();

	DWORD	dwAllTime = tMoveState.GetTimeCount() + tMoveMMask.GetTimeCount() + tMoveEyeshot.GetTimeCount() + tMoveArea.GetTimeCount();
	if (dwAllTime >= 50)
		//LG("map_time", "\t\t��ɫ[%s]��Ұ�ƶ����ѵ�ʱ����� time = %u������״̬����%u��̽���Ȼ���%u����Ұ����%u�����򻨷�%u��\n",
		ToLogService("common", "\t\tcharacter[{}] eyeshot move spend overabundance time time = {}��thereinto state spend {}��explore spend {}��eyeshot spend {}��area spend {}��",
			pCEnt->GetLogName(), dwAllTime, tMoveState.GetTimeCount(), tMoveMMask.GetTimeCount(), tMoveEyeshot.GetTimeCount(), tMoveArea.GetTimeCount());
}

void SubMap::LoadMonsterInfo(void)
{
}

// ���õر�״̬
void SubMap::ClearSurfaceState(void)
{
	CStateCell		*pCStateCell;
	m_CStateCellL.BeginGet();
	while (pCStateCell = m_CStateCellL.GetNext())
	{
		pCStateCell->DropState(this);
	}
}

// ��λ����ҽ�ɫ�����ڸ������¿���ʱ�Ľ�ɫ��ʼ��
void SubMap::ResetNotPlyCha()
{
	CCharacter	*pCCha;
	Long		lChaCount, lChaNum;
	CEyeshotCell	*pCEyeCell;
	for (Short y = 0; y < GetEyeshotCellLin(); y++)
	{
		for (Short x = 0; x < GetEyeshotCellCol(); x++)
		{
			pCEyeCell = &m_pCEyeshotCell[y][x];
			lChaCount = 0;
			lChaNum = pCEyeCell->GetChaNum();
			pCCha = pCEyeCell->m_pCChaL;

			while (pCCha)
			{
				if (++lChaCount > lChaNum)
				{
					//LG("��Ұ�������", "��Ұ��Ԫ[%d,%d]ʵ��ʵ���� %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}] practice entity numbers{}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					break;
				}

				if (!pCCha->IsPlayerOwnCha())
					pCCha->Reset();

				if (pCCha->m_pCEyeshotCellNext)
					pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
				else
					pCCha = 0;
			}
		}
	}
}

// ������ҽ�ɫ�����ڸ����ر�ʱ��������ҽ�ɫ������
void SubMap::ClearPlayerCha()
{
	CEyeshotCell	*pCEyeCell;
	CCharacter		*pCCha, *pCProcCha;
	long			lChaCount, lChaNum;
	//LG("enter_map", "��ͼ %s�������� %d������ʼ����������!\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}(copyID {}),start delete all character!", GetName(), GetCopyNO());
	m_CEyeshotCellL.BeginGet();
	while (pCEyeCell = m_CEyeshotCellL.GetNext())
	{
		lChaCount = 0;
		lChaNum = pCEyeCell->GetChaNum();
		pCCha = pCEyeCell->m_pCChaL;
		while (pCCha)
		{
			if (++lChaCount > lChaNum)
			{
				//LG("��Ұ�������", "��Ұ��Ԫ[%d,%d]ʵ��ʵ���� %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity numbers {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				break;
			}

			pCProcCha = pCCha;
			if (pCCha->m_pCEyeshotCellNext)
				pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
			else
				pCCha = 0;

			if(pCProcCha->IsPlayerFocusCha())
			{
				if (!pCProcCha->GetSubMap())
					//LG("��Ұ�������", "�ڽ��е�ͼͨ��ʱ��� %s(%s)[%d,%d] �ĵ�ͼΪ��\n",
					ToLogService("errors", LogLevel::Error, "in the wind map notify character {}({})[{},{}] 's map is empty",
						pCProcCha->GetLogName(), pCProcCha->GetPlyCtrlCha()->GetLogName(), pCProcCha->GetPos().x, pCProcCha->GetPos().y);

				//LG("enter_map", "��ͼ %s �رգ������� %s[%s]!\n", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				ToLogService("map", "map {} close��clean out {}[{}]!", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				if (!pCProcCha->IsLiveing())
				{
					g_CParser.DoString("Relive", enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, pCProcCha, DOSTRING_PARAM_END);

					pCProcCha->m_chSelRelive = enumEPLAYER_RELIVE_NONE;
					pCProcCha->m_chReliveLv = 0;
					pCProcCha->BackToCityEx(true);
				}
				else
					pCProcCha->BackToCityEx();
			}
		}
	}
	m_COutMapCha.Drop();
	//LG("enter_map", "��ͼ %s�������� %d�� �����ҳɹ�!\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}( copyID {})clean out character succeed!", GetName(), GetCopyNO());
}

void SubMap::ClearAllMonster(void)
{
	CCharacter	*pCCha;
	Long		lChaCount, lChaNum;
	CEyeshotCell	*pCEyeCell;
	for (Short y = 0; y < GetEyeshotCellLin(); y++)
	{
		for (Short x = 0; x < GetEyeshotCellCol(); x++)
		{
			pCEyeCell = &m_pCEyeshotCell[y][x];
			lChaCount = 0;
			lChaNum = pCEyeCell->GetChaNum();
			pCCha = pCEyeCell->m_pCChaL;

			while (pCCha)
			{
				if (++lChaCount > lChaNum)
				{
					//LG("��Ұ�������", "��Ұ��Ԫ[%d,%d]ʵ��ʵ���� %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity number {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					break;
				}

				if (!pCCha->IsPlayerOwnCha())
					pCCha->ResetLifeTime(1000);

				if (pCCha->m_pCEyeshotCellNext)
					pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
				else
					pCCha = 0;
			}
		}
	}
}

void SubMap::ClearAllMonsterByName(const char* szMonsName)
{
	CCharacter	*pCCha;
	Long		lChaCount, lChaNum;
	CEyeshotCell	*pCEyeCell;
	for (Short y = 0; y < GetEyeshotCellLin(); y++)
	{
		for (Short x = 0; x < GetEyeshotCellCol(); x++)
		{
			pCEyeCell = &m_pCEyeshotCell[y][x];
			lChaCount = 0;
			lChaNum = pCEyeCell->GetChaNum();
			pCCha = pCEyeCell->m_pCChaL;

			while (pCCha)
			{
				if (++lChaCount > lChaNum)
				{
					//LG("��Ұ�������", "��Ұ��Ԫ[%d,%d]ʵ��ʵ���� %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity number {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
					break;
				}

				if (!pCCha->IsPlayerOwnCha())
				{
					if (!strcmp(pCCha->GetName(), szMonsName))
						pCCha->ResetLifeTime(1000);
				}

				if (pCCha->m_pCEyeshotCellNext)
					pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
				else
					pCCha = 0;
			}
		}
	}
}

void SubMap::ClearAllCha()
{
	CEyeshotCell	*pCEyeCell;
	CCharacter		*pCCha, *pCProcCha;
	long			lChaCount, lChaNum;
	//LG("enter_map", "��ͼ %s�������� %d������ʼ������й���!\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}(copyID {})��start clean out all monsters", GetName(), GetCopyNO());
	m_CEyeshotCellL.BeginGet();
	while (pCEyeCell = m_CEyeshotCellL.GetNext())
	{
		lChaCount = 0;
		lChaNum = pCEyeCell->GetChaNum();
		pCCha = pCEyeCell->m_pCChaL;
		while (pCCha)
		{
			if (++lChaCount > lChaNum)
			{
				//LG("��Ұ�������", "��Ұ��Ԫ[%d,%d]ʵ��ʵ���� %d\n", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				ToLogService("errors", LogLevel::Error, "eyeshot cell[{},{}]practice entity numbers {}", pCEyeCell->m_sPosX, pCEyeCell->m_sPosY, lChaNum);
				break;
			}

			pCProcCha = pCCha;
			if (pCCha->m_pCEyeshotCellNext)
				pCCha = pCCha->m_pCEyeshotCellNext->IsCharacter();
			else
				pCCha = 0;

			if(!pCProcCha->IsPlayerFocusCha())
			{
				pCProcCha->Free();
			}
			else
			{
				if (!pCProcCha->GetSubMap())
					//LG("��Ұ�������", "�ڽ��е�ͼͨ��ʱ��� %s(%s)[%d,%d] �ĵ�ͼΪ��\n",
					ToLogService("errors", LogLevel::Error, "in the wind map notify character {}({})[{},{}] 's map is empty",
					pCProcCha->GetLogName(), pCProcCha->GetPlyCtrlCha()->GetLogName(), pCProcCha->GetPos().x, pCProcCha->GetPos().y);

				//LG("enter_map", "��ͼ %s �رգ������� %s[%s]!\n", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				ToLogService("map", "map {} close,clean out character {}[{}]!", GetName(), pCProcCha->GetName(), pCProcCha->GetPlyMainCha()->GetName());
				if (!pCProcCha->IsLiveing())
				{
					g_CParser.DoString("Relive", enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, pCProcCha, DOSTRING_PARAM_END);

					pCProcCha->m_chSelRelive = enumEPLAYER_RELIVE_NONE;
					pCProcCha->m_chReliveLv = 0;
					pCProcCha->BackToCityEx(true);
				}
				else
					pCProcCha->BackToCityEx();
			}
		}
		pCEyeCell->m_pCChaL = NULL;
	}
	//LG("enter_map", "��ͼ %s�������� %d�� �������ɹ�!\n", GetName(), GetCopyNO());
	ToLogService("map", "map {}(copyID {})clean out monster succeed!", GetName(), GetCopyNO());
}

void SubMap::EntryOpen()
{
	Open();
}

void SubMap::EntryClose()
{
}

void SubMap::Open()
{
	if (m_bIsRun)
		return;

	m_bIsRun = true;
}

void SubMap::Run(DWORD dwCurTime)
{
	if (!m_bIsRun)
		return;

	m_COutMapCha.Run(dwCurTime);

	if (m_timeScriptRun.IsOK(dwCurTime))
	{
		string	strScript = "map_copy_run_";
		strScript += GetName();
		g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, this, DOSTRING_PARAM_END);
	}

	if (m_timeSpecialRun.IsOK(dwCurTime))
	{
		string	strScript = "map_copy_run_special_";
		strScript += GetName();
		g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, this, DOSTRING_PARAM_END);

	}

}

void SubMap::Close()
{
	if (!m_bIsRun)
		return;
	string	strScript = "map_copy_before_close_";
	strScript += GetName();
	g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, this, DOSTRING_PARAM_END);

	ClearSurfaceState();

	ClearPlayerCha();
	m_COutMapCha.Drop();
	ResetNotPlyCha();

	strScript = "map_copy_close_";
	strScript += GetName();
	g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, this, DOSTRING_PARAM_END);

	m_bIsRun = false;
}

void SubMap::BeforePlyOutMap(CCharacter *pCCha)
{
	m_pCMapRes->SubEntryPlayer(GetCopyNO());

	string	strScript = "before_leave_";
	strScript += GetName();
	g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 2, pCCha, this, DOSTRING_PARAM_END);
}

void SubMap::AfterPlyEnterMap(CCharacter *pCCha)
{
	string	strScript = "after_enter_";
	strScript += GetName();
	g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 2, pCCha, this, DOSTRING_PARAM_END);
}

void SubMap::BeginGetPlyCha(void)
{
	m_CEyeshotCellL.BeginGet();
	CEyeshotCell	*pCEyeCell = m_CEyeshotCellL.GetCurrent();
	if (pCEyeCell)
		pCEyeCell->BeginGetCha();
}

CCharacter* SubMap::GetNextPlyCha(void)
{
	CCharacter	*pCCha = 0;

Research:
	CEyeshotCell	*pCEyeCell = m_CEyeshotCellL.GetCurrent();
	if (pCEyeCell)
	{
		pCCha = pCEyeCell->GetNextCha();
		while (!pCCha)
		{
			m_CEyeshotCellL.GetNext();
			pCEyeCell = m_CEyeshotCellL.GetCurrent();
			if (!pCEyeCell)
				break;
			pCEyeCell->BeginGetCha();
			pCCha = pCEyeCell->GetNextCha();
		}
	}
	if (pCCha)
		if (!pCCha->IsPlayerOwnCha())
			goto Research;

	return pCCha;
}

bool SubMap::CheckRun(void)
{
	if (IsRun())
		return true;
	if (!m_pCMapRes)
		return false;

	if (m_pCMapRes->GetCopyStartType() == enumMAPCOPY_START_CONDITION)
	{
		if (m_pCMapRes->GetCopyStartCdtType() == enumMAPCOPY_START_CDT_PLYNUM)
		{
			if (GetPlayerNum() >= m_pCMapRes->GetCopyStartCdtVal())
			{
				Open();

				string	strScript = "map_copy_first_run_";
				strScript += GetName();
				g_CParser.DoString(strScript.c_str(), enumSCRIPT_RETURN_NONE, 0, enumSCRIPT_PARAM_LIGHTUSERDATA, 1, this, DOSTRING_PARAM_END);

				return true;
			}
		}
	}

	return false;
}

void SubMap::DealActivePlayer(string& function)
{
	CCharacter * pCha;
	BeginGetPlyCha();

	while(pCha = GetNextPlyCha())
	{
		if(pCha->IsPlayerCha() && pCha->IsLiveing())
		{
			g_CParser.DoString(function.c_str(),enumSCRIPT_RETURN_NONE, 0,enumSCRIPT_PARAM_LIGHTUSERDATA, 1,pCha,DOSTRING_PARAM_END);
		}
	}
	

}

void SubMap::DealPlayer(string& function)
{
	CCharacter * pCha = NULL;
	BeginGetPlyCha();

	while(pCha = GetNextPlyCha())
	{
		if(pCha->IsPlayerCha())
		{
			g_CParser.DoString(function.c_str(),enumSCRIPT_RETURN_NONE, 0,enumSCRIPT_PARAM_LIGHTUSERDATA, 1,pCha,DOSTRING_PARAM_END);
		}
	}
}

//=============================================================================
COutMapCha::COutMapCha(unsigned short usFreq)
{
	m_ulTick = GetTickCount();
	m_usFreq = usFreq;
}

COutMapCha::~COutMapCha()
{
	/*
	SMgrUnit	*pSCarrier;
	pSCarrier = m_pSExecQueue;
	while (pSCarrier)
	{
		m_pSExecQueue = pSCarrier->pSNext;
		delete pSCarrier;
		pSCarrier = m_pSExecQueue;
	}

	pSCarrier = m_pSFreeQueue;
	while (pSCarrier)
	{
		m_pSFreeQueue = pSCarrier->pSNext;
		delete pSCarrier;
		pSCarrier = m_pSFreeQueue;
	}

	*/
	spawnQueue.clear();
}

void COutMapCha::Add(CCharacter *pCObj, dbc::uLong	ulChaID, SSwitchMapInfo *pSwitchInfo, Char chAction, Long lLeftTick1, Long lLeftTick2)
{
	if (!pCObj)
		return;

	auto pSCarrier = std::make_unique<SMgrUnit>();
	pSCarrier->pCCha = pCObj;
	pSCarrier->ulChaID = ulChaID;
	memcpy(&pSCarrier->SwitchInfo, pSwitchInfo, sizeof(SSwitchMapInfo));
	pSCarrier->chAction = chAction;
	pSCarrier->lLeftTick1 = lLeftTick1;
	pSCarrier->lLeftTick2 = lLeftTick2;
	pSCarrier->chStep = 1;

	spawnQueue.emplace_back(std::move(pSCarrier));
	
	// Spawn queue recoded - Mdr September 2020

}

void COutMapCha::Run(unsigned long ulCurTick)
{
	
	long	lTickDist = ulCurTick - m_ulTick;

	if (lTickDist < m_usFreq) {
	return;
	}
	m_ulTick = ulCurTick;

	spawnQueue.erase(
		std::remove_if(spawnQueue.begin(), spawnQueue.end(),
			[&](std::unique_ptr<SMgrUnit>& pSCarrier)
			{
				if (!pSCarrier)
				{
					return true;
				}

				if (!pSCarrier->IsValidCha())
				{
					return true;
				}

				switch (pSCarrier->chStep)
				{
				case 1:
				{
					pSCarrier->lLeftTick1 -= lTickDist;
					if (pSCarrier->lLeftTick1 <= 0)
					{
						ExecTimeCha(pSCarrier.get());
						return false;
					}
				}
				break;
				case 2:
				{
					pSCarrier->lLeftTick2 -= lTickDist;
					if (pSCarrier->lLeftTick2 <= 0)
					{
						ExecTimeCha(pSCarrier.get());
						return true;
					}
				}
				break;
				}

				return false;
			}
	), spawnQueue.end());

	//vector<SMgrUnit*>::iterator it = spawnQueue.begin();
	//int n = 0;
	//while (it != spawnQueue.end()) {
	//	it = spawnQueue.begin();
	//	SMgrUnit* pSCarrier = spawnQueue.at(n);
	//	
	//	if (!pSCarrier) 
	//	{
	//		it = spawnQueue.erase(it);
	//		continue;
	//	}
	//	if (!pSCarrier->IsValidCha()) 
	//	{
	//		it = spawnQueue.erase(it);
	//		continue;
	//	}
	//	if (pSCarrier->chStep == 1)
	//	{
	//		
	//		pSCarrier->lLeftTick1 -= lTickDist;
	//		if (pSCarrier->lLeftTick1 <= 0) {
	//			ExecTimeCha(pSCarrier);
	//			continue;
	//		}
	//	}
	//	else if (pSCarrier->chStep == 2)
	//	{
	//		pSCarrier->lLeftTick2 -= lTickDist;
	//		if (pSCarrier->lLeftTick2 <= 0) {
	//			ExecTimeCha(pSCarrier);
	//			it = spawnQueue.erase(it);
	//			continue;
	//		}
	//	}
	//	it++;
	//	n++;
	//}
	//
}

void COutMapCha::Drop()
{

	for (const auto& pSCarrier : spawnQueue)
	{
		if (pSCarrier)
		{
			ExecTimeCha(pSCarrier.get());
			ExecTimeCha(pSCarrier.get());
		}
	}
	spawnQueue.clear();

}

void COutMapCha::ExecTimeCha(SMgrUnit *pChaInfo)
{
	if (pChaInfo->chStep == 1)
	{
		pChaInfo->SwitchInfo.pSrcMap->GoOut(pChaInfo->pCCha);
		pChaInfo->pCCha->SetExistState(enumEXISTS_RESUMEING);
		pChaInfo->chStep++;
	}
	else if (pChaInfo->chStep == 2)
	{
		switch (pChaInfo->chAction)
		{
		case	enumCHA_TIMEER_ENTERMAP:
			{
				CCharacter	*pCCha = pChaInfo->pCCha;
				if (pCCha->IsPlayerCha()) // ��Ӧ�ó��ֵ����
				{
					//LG("������������", "�������� %s����ҽ�ɫ���� %s(%s)\n", pCCha->GetLogName(), pCCha->GetPlyMainCha()->GetLogName(), pCCha->GetPlyCtrlCha()->GetLogName());
					ToLogService("common", "monster name {}��character player name {}({})", pCCha->GetLogName(), pCCha->GetPlyMainCha()->GetLogName(), pCCha->GetPlyCtrlCha()->GetLogName());
					break;
				}
				
				
				if(pCCha->GetLifeTime()!=0)
				{
					break;
				}

				pCCha->SetInOutMapQueue(false);
				pCCha->m_chSelRelive = enumEPLAYER_RELIVE_NONE;

				g_ulCurID = pCCha->GetID();
				g_lCurHandle = pCCha->GetHandle();

				pCCha->setAttr(ATTR_HP, pCCha->m_CChaAttr.GetAttr(ATTR_MXHP));	// ��ǰHP
				pCCha->setAttr(ATTR_SP, pCCha->m_CChaAttr.GetAttr(ATTR_MXSP));	// ��ǰSP
				//pCCha->m_timerScripts.Reset();
				pCCha->SetExistState(enumEXISTS_NATALITY);
				
				pCCha->SwitchMap(pChaInfo->SwitchInfo.pSrcMap, pChaInfo->SwitchInfo.szTarMapName, pChaInfo->SwitchInfo.STarPos.x, pChaInfo->SwitchInfo.STarPos.y, false, enumSWITCHMAP_DIE, pChaInfo->SwitchInfo.pSrcMap->GetCopyNO());

				pCCha->ResetAIState();	// ����ai�����״̬��¼

				g_ulCurID = defINVALID_CHA_ID;
				g_lCurHandle = defINVALID_CHA_HANDLE;
			}
			break;
		}
		pChaInfo->chStep++;
	}
}

