#pragma once

/* Generated by Together */

#ifndef GUILD_H
#define GUILD_H
#include "PreAlloc.h"
#include "RunBiDirectChain.h"
#include "GuildMember.h"
_DBC_USING
class	Player;

/**
 * @alias  
 */
class Guild :public PreAllocStru , public RunBiDirectItem<Guild>, public RunBiDirectChain<GuildMember>
{
public:
	Guild(uLong size);
	void	Free(){PreAllocStru::Free();}
	static	Guild *Alloc();
	bool	BeginRun();
	bool	EndRun();
	Player *FindGuildMemByChaID(uLong id);

	uLong			m_id;
	char			m_name[17];				//
	char			m_motto[51];			//
	BitMaskStatus	m_stat;					//0x0-;0x1-;0x2-;0x4-
	uLong			m_remain_minute;		//
	uLong			m_tick;
	uLong			m_leaderID;

	/**
	 * @label  
	 */
	Player	*	m_leader;					//
private:
	~Guild();

	void Initially();
	void Finally();

};
class ChkGuild: public Timer
{
public:
	ChkGuild(uLong interval):Timer(interval){}
private:
	void Process();
};

#endif //GUILD_H
