/* Generated by Together */
#pragma once

#ifndef USE_IOCP

#include <string>
#include "DBCCommon.h"
#include "PreAlloc.h"
#include "ThreadPool.h"
#include "CommRPC.h"
#include "Point.h"
#include "Identity.h"
#include "Usage.h"
#include "DataSocket.h"
#include "PacketQueue.h"
#include "Config.h"
#include "gtplayer.h"
#include "util.h"

#include "MsgQueue.h"

#include <mutex>

// GateServer 
class GameServerApp;
class GateServer
{
public:
    GateServer() : m_pCDataSock(0), m_usPort(0), m_gtname(""), m_playerlist(NULL), m_playercount(0)
    {
    }

    ~GateServer()
    {
        m_pCDataSock = NULL;
        m_gtname = "";
    }

    void SetDataSock(dbc::DataSocket* datasock)
    {
        m_pCDataSock = datasock;
    }

    void Invalid()
    {
        m_pCDataSock = NULL;
    }

    bool IsValid() {return (m_pCDataSock != NULL) ? true : false;}

    std::string& GetIP() {return m_strIp;}
    unsigned short& GetPort() {return m_usPort;}
    std::string& GetName() {return m_gtname;}
    //GatePlayer*& GetPlayerList() {return m_playerlist;}
    dbc::DataSocket* GetDataSock() const {return m_pCDataSock;}

    long SendData(dbc::WPacket pkt)
    {
        if (IsValid()) {
            return m_pCDataSock->SendData(pkt);
        } else {
            return 0;
        }        
    }

	GatePlayer* m_listcurplayer;	// 

    // Player 
    GatePlayer* m_playerlist;
	int m_playercount;
	void AddPlayerCount() {++ m_playercount;}
	void DecPlayerCount() {-- m_playercount;}
	int GetPlayerCount() const {return m_playercount;}

protected:
    std::string m_strIp;
    unsigned short m_usPort;
    std::string m_gtname;

    dbc::DataSocket* m_pCDataSock;

};


//  GateServer 
class ConnectGateServer : public dbc::Task
    {
public:
    ConnectGateServer(GameServerApp* gmsvr) {m_gmsvr = gmsvr; dwTimeOut = 3000;}

private:
    virtual long Process();
    DWORD dwTimeOut;
    GameServerApp* m_gmsvr;};

// 
class GameServerApp : public dbc::TcpClientApp, public dbc::RPCMGR, public dbc::PKQueue
    {
    friend class ConnectGateServer;
    friend class ToInfoServer;

public:
	GameServerApp(dbc::ThreadPool *proc,dbc::ThreadPool *comm);
	virtual ~GameServerApp();

    // 
    char const* GetName() const {return m_strGameName.c_str();}
	void ConnectGate(GateServer *pGate);
    bool IsValidGate(int i);
    GateServer* FindGate(char const* gt_name);

    // Player  (GateServerGatePlayer)
    bool AddPlayer(GatePlayer* gtplayer, GateServer* gt, dbc::uLong gtaddr);
    bool DelPlayer(GatePlayer* gtplayer);
	// add by xuedong
	bool BeginGetplayer(GateServer* gt);
	GatePlayer* const GetNextPlayer(GateServer* gt);

	void BeginGetGate(void);
	GateServer* GetNextGate(void);
	//

    bool KickPlayer(GatePlayer* gtplayer, long lTimeSec = 0);
	bool KickPlayer2(GatePlayer *gtplayer);

    // 
    bool SendToWorld(dbc::WPacket& pkt);
	bool SendToGroup(dbc::WPacket& chginf);
    bool SendToClient(GatePlayer* player, dbc::WPacket& pkt);
    bool SendToClient(dbc::WPacket& pkt, GatePlayer* playerlist);
    bool SendToClient(dbc::WPacket& pkt, int array_cnt, uplayer* uplayer_array);
    bool SendToGame(dbc::WPacket& pkt, uplayer* uplyr);
    
protected:
	virtual bool OnConnect(dbc::DataSocket *datasock); //:true-,false-
	virtual void OnDisconnect(dbc::DataSocket *datasock,int reason); //reason:0--3--1-Socket;-5-.
	virtual void OnProcessData(dbc::DataSocket *datasock,dbc::RPacket &recvbuf);
	void ProcessData(dbc::DataSocket* datasock, dbc::RPacket& recvbuf);

public:
	// SyncCall Handler
	virtual	dbc::WPacket OnServeCall(dbc::DataSocket* datasock, dbc::RPacket& in_para);

	dbc::WPacket TM_KICKCHA(dbc::DataSocket* datasock, dbc::RPacket& pk);

	dbc::WPacket TM_OFFLINE_MODE(dbc::DataSocket* datasock, dbc::RPacket& rpk);

public:	
	long 				m_count;
	dbc::DataSocket	*	m_groupsock;
	Usage				m_usage;



private:
    std::recursive_mutex m_mutdisconn;

    GateServer m_gtarray[MAX_GATE];
    short m_gtnum;
	short m_listcurgt;

    std::string m_strGameName;};

inline bool GameServerApp::BeginGetplayer(GateServer* gt)
{
    if (gt == NULL) return false;
    if (!gt->IsValid()) return false;

	gt->m_listcurplayer = gt->m_playerlist;

	return true;
}

inline GatePlayer* const GameServerApp::GetNextPlayer(GateServer* gt)
{
	GatePlayer*	pretplayer = gt->m_listcurplayer;
	if (gt->m_listcurplayer)
		gt->m_listcurplayer = gt->m_listcurplayer->Next;

	return pretplayer;
}

inline void GameServerApp::BeginGetGate(void)
{
	m_listcurgt = 0;
}

inline GateServer* GameServerApp::GetNextGate(void)
{
	while (m_listcurgt < m_gtnum)
	{
	    if (m_gtarray[m_listcurgt++].IsValid())
			return m_gtarray + (m_listcurgt - 1);
	}

	return 0;
}

extern GameServerApp *g_gmsvr;

inline void uplayer::Init(char const* gt_name, unsigned long gt_addr, DWORD atorID)
{
    pGate = g_gmsvr->FindGate(gt_name);
    m_dwDBChaId = atorID;
    m_ulGateAddr = gt_addr;
}

#endif
