/* Generated by Together */

#ifndef GATESERVER_H
#define GATESERVER_H

#include <string>
#include "CorsairsNet.h"

class GateServer
{
	friend class GroupServerApp;
public:
	GateServer() : m_client(nullptr), m_bSync(false) {}

	bool SetClient(net::TcpClient* client)
	{
		bool l_retval = true;
		if (m_client && client)
		{
			l_retval = false;
		}
		else if (client)
		{
			l_retval = true;
			client->SetPointer(this);
		}
		if (l_retval)
		{
			if (m_client)
			{
				m_client->SetPointer(nullptr);
			}
			m_client = client;
		}
		return l_retval;
	}

	net::TcpClient* GetClient()
	{
		return m_client;
	}

	// Проверка валидности подключения
	bool IsValid() const { return m_client && m_client->IsConnected(); }

	// Отправка пакета через gate
	bool SendData(net::WPacket& pkt) { return IsValid() ? m_client->Send(pkt) : false; }

	// Add by lark.li 20081119 begin
	bool	IsSync(){ return m_bSync; }
	void	SetSync(bool sync = true) { m_bSync = sync; }
	// End

private:
	std::string			m_name;
	net::TcpClient*		m_client;
	// Add by lark.li 20081119 begin
	bool		m_bSync;		// GateServer←→GroupServer同步标志
	// End
};


// Add by lark.li 20081119 begin
class GroupServerAgent
{
	friend class GroupServerApp;
public:
	GroupServerAgent() : m_client(nullptr) {}

	bool SetClient(net::TcpClient* client)
	{
		bool l_retval = true;
		if (m_client && client)
		{
			l_retval = false;
		}
		else if (client)
		{
			l_retval = true;
			client->SetPointer(this);
		}
		if (l_retval)
		{
			if (m_client)
			{
				m_client->SetPointer(nullptr);
			}
			m_client = client;
		}
		return l_retval;
	}

	net::TcpClient* GetClient()
	{
		return m_client;
	}

	bool IsValid() const { return m_client && m_client->IsConnected(); }
	bool SendData(net::WPacket& pkt) { return IsValid() ? m_client->Send(pkt) : false; }

private:
	std::string			m_name;
	net::TcpClient*		m_client;
};
// End

#endif //GATESERVER_H
