/* Generated by Together */
#include "stdafx.h"
#include <iostream>
#include "GroupServerApp.h"
#include "GameCommon.h"
#include "DBConnect.h"
#include "Team.h"

void	GroupServerApp::CP_GM1SAY(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	auto		l_content	=pk.ReadString();
	if(l_content.empty() ||l_content.size() >500)return;
	//Modify by sunny.sun 20080821
	if( ply != NULL )
	{
		if(!ply->m_gm)
		{
			//ply->SendSysInfo("????��D??����?T.");
			ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00001));
			return;
		}
	}
	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_GM1SAY);
	if( ply != NULL)
		l_wpk.WriteString(ply->m_chaname[ply->m_currcha].c_str());	//?��?�㨨?��???��?
	else
		{
			l_wpk.WriteString( "" );
		}
	l_wpk.WriteString(l_content);								//?��?���??����Y

	Player *l_plylst[10240];
	short	l_plynum	=0;

	Player	*	l_ply1	=0;char	l_currcha	=0;
	RunChainGetArmor<Player> l(m_plylst);
	while(l_ply1	=m_plylst.GetNextItem())
	{
		if((l_currcha =l_ply1->m_currcha) >=0)
		{
			l_plylst[l_plynum]	=l_ply1;
			l_plynum ++;
		}
	}
	l.unlock();
	SendToClient(l_plylst,l_plynum,l_wpk);
}

//Add by sunny.sun20080804
//Begin
void	GroupServerApp::CP_GM1SAY1(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	auto		l_content	=pk.ReadString();
	int			SetNum = 1;

	if(l_content.empty() ||l_content.size() >500)return;
	if(ply != NULL)
	{
		if(!ply->m_gm)
		{
			ply->SendSysInfo("????��D??����?T.");
			return;
		}
	}
	else
		SetNum = pk.ReadInt64();
	DWORD		color = pk.ReadInt64();

	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_GM1SAY1);
	//l_wpk.WriteString(ply->m_chaname[ply->m_currcha].c_str());	//?��?�㨨?��???��?
	l_wpk.WriteString(l_content);								//?��?���??����Y
	l_wpk.WriteInt64(SetNum);
	l_wpk.WriteInt64(color);
	Player *l_plylst[10240];
	short	l_plynum	=0;

	Player	*	l_ply1	=0;char	l_currcha	=0;
	RunChainGetArmor<Player> l(m_plylst);
	while(l_ply1	=m_plylst.GetNextItem())
	{
		if((l_currcha =l_ply1->m_currcha) >=0)
		{
			l_plylst[l_plynum]	=l_ply1;
			l_plynum ++;
		}
	}
	l.unlock();
	SendToClient(l_plylst,l_plynum,l_wpk);
}
//End
void	GroupServerApp::CP_SAY2TRADE(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	if( ply->IsEstop() )
	{
		//ply->SendSysInfo( "??��??-��?????��???��?o��?����?��?" );
		ply->SendSysInfo( RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00002) );
		return;
	}

	uLong	l_curtick	=GetTickCount();
	if(!ply->m_gm && l_curtick - ply->m_tradetick <const_interval.Trade)
	{
		//ply->SendSysInfo("???e?�̡�������??");
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00003));
		return;
	}
	if(l_curtick - ply->m_tradetick < 5 * 60 * 1000)	//make ticks longer since we removed the fee //< 3 * 60 * 1000)	
	{
		if(ply->m_lTradeChatMoney < 100000)
		{
			ply->m_lTradeChatMoney += std::stoi(m_cfg["chat"]["WorldFeeInterval"]);//1000;
		}
	}
	else
	{
		ply->m_lTradeChatMoney = std::stoi(m_cfg["chat"]["WorldFee"]);//1000;
	}
	ply->m_tradeticktemp = ply->m_tradetick;
	ply->m_tradetick	=l_curtick;

	auto		l_content	=pk.ReadString();
	if(l_content.empty() ||l_content.size() >200)return;
	if(ply) //->m_gm	//to fix for none gm players
	{
		net::WPacket	l_wpk(256);
		l_wpk.WriteCmd(CMD_PC_SAY2TRADE);
		l_wpk.WriteString(ply->m_chaname[ply->m_currcha].c_str());	//?��?�㨨?��???��?
		l_wpk.WriteString(l_content);								//?��?���??����Y
		l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
		Player *l_plylst[10240];
		short	l_plynum	=0;

		Player	*	l_ply1	=0;char	l_currcha	=0;
		RunChainGetArmor<Player> l(m_plylst);
		while(l_ply1	=m_plylst.GetNextItem())
		{
			if((l_currcha =l_ply1->m_currcha) >=0)
			{
				l_plylst[l_plynum]	=l_ply1;
				l_plynum ++;
			}
		}
		l.unlock();
		SendToClient(l_plylst,l_plynum,l_wpk);
		return;
	}
	//maybe disable this later? make fee 0?
	/* 
	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PM_SAY2TRADE);
	l_wpk.WriteInt64(ply->m_chaid[ply->m_currcha]);
	l_wpk.WriteString(l_content);
	l_wpk.WriteInt64(ply->m_lTradeChatMoney);
	SendToClient( ply, l_wpk );
	*/
}
void GroupServerApp::CP_SAY2ALL(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	if( ply->IsEstop() )
	{
		//ply->SendSysInfo( "??��??-��?????��???��?o��?����?��?" );
		ply->SendSysInfo( RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00002) );
		return;
	}

	uLong	l_curtick	=GetTickCount();
	if(!ply->m_gm && l_curtick - ply->m_worldtick <const_interval.World)
	{
		//ply->SendSysInfo("???e?�̡�������??");
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00003));
		return;
	}
	if(l_curtick - ply->m_worldtick < 3 * 60 * 1000)
	{
		if(ply->m_lChatMoney < 100000)
		{
			ply->m_lChatMoney += 1000;
		}
	}
	else
	{
		ply->m_lChatMoney = 1000;
	}
	ply->m_worldticktemp = ply->m_worldtick;
	ply->m_worldtick	=l_curtick;

	auto		l_content	=pk.ReadString();
	if(l_content.empty() ||l_content.size() >200)return;
	if(ply->m_gm)
	{
		net::WPacket	l_wpk(256);
		l_wpk.WriteCmd(CMD_PC_SAY2ALL);
		l_wpk.WriteString(ply->m_chaname[ply->m_currcha].c_str());	//?��?�㨨?��???��?
		l_wpk.WriteString(l_content);								//?��?���??����Y
		l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
		Player *l_plylst[10240];
		short	l_plynum	=0;

		Player	*	l_ply1	=0;char	l_currcha	=0;
		RunChainGetArmor<Player> l(m_plylst);
		while(l_ply1	=m_plylst.GetNextItem())
		{
			if((l_currcha =l_ply1->m_currcha) >=0)
			{
				l_plylst[l_plynum]	=l_ply1;
				l_plynum ++;
			}
		}
		l.unlock();
		SendToClient(l_plylst,l_plynum,l_wpk);
		return;
	}

	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PM_SAY2ALL);
	l_wpk.WriteInt64(ply->m_chaid[ply->m_currcha]);
	l_wpk.WriteString( l_content );
	l_wpk.WriteInt64(ply->m_lChatMoney);
	SendToClient( ply, l_wpk );
}

void GroupServerApp::MP_SAY2TRADE(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	char succ = pk.ReadInt64();
	if(succ == 0)
	{
		ply->m_tradetick = ply->m_tradeticktemp;
		if(ply->m_lChatMoney > 1000)
		{
			ply->m_lChatMoney -= 1000;
		}
		return;
	}
	auto		szName		=pk.ReadString();
	auto		l_content	=pk.ReadString();
	if (l_content.empty() || l_content.size() > 200)return;
	///
	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SAY2TRADE);
	l_wpk.WriteString(szName);	//?��?�㨨?��???��?
	l_wpk.WriteString(l_content);								//?��?���??����Y
	l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
	Player *l_plylst[10240];
	short	l_plynum	=0;

	Player	*	l_ply1	=0;char	l_currcha	=0;
	RunChainGetArmor<Player> l(m_plylst);
	while(l_ply1	=m_plylst.GetNextItem())
	{
		if((l_currcha =l_ply1->m_currcha) >=0)
		{
			l_plylst[l_plynum]	=l_ply1;
			l_plynum ++;
		}
	}
	l.unlock();
	SendToClient(l_plylst,l_plynum,l_wpk);
}

void GroupServerApp::MP_SAY2ALL(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	char succ = pk.ReadInt64();
	if(succ == 0)
	{
		ply->m_worldtick = ply->m_worldticktemp;
		if(ply->m_lChatMoney > 1000)
		{
			ply->m_lChatMoney -= 1000;
		}
		return;
	}

	auto		szName		=pk.ReadString();
	auto		l_content	=pk.ReadString();

	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SAY2ALL);
	l_wpk.WriteString(szName);	//?��?�㨨?��???��?
	l_wpk.WriteString(l_content);								//?��?���??����Y
	l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
	Player *l_plylst[10240];
	short	l_plynum	=0;

	Player	*	l_ply1	=0;char	l_currcha	=0;
	RunChainGetArmor<Player> l(m_plylst);
	while(l_ply1	=m_plylst.GetNextItem())
	{
		if((l_currcha =l_ply1->m_currcha) >=0)
		{
			l_plylst[l_plynum]	=l_ply1;
			l_plynum ++;
		}
	}
	l.unlock();
	SendToClient(l_plylst,l_plynum,l_wpk);
}

void GroupServerApp::MP_GUILDNOTICE(Player *ply, net::TcpClient *client, net::RPacket &pk)
{
	uLong guildID = pk.ReadInt64();
	if (!guildID)
		return;

	auto l_content = pk.ReadString();

	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_GUILDNOTICE); // CMD_PC_GUILDNOTICE
	l_wpk.WriteString(l_content);

	Player *l_plylst[10240];
	short	l_plynum = 0;

	Player* l_ply1 = 0;
	char l_currcha = 0;

	RunChainGetArmor<Player> l(m_plylst);
	while (l_ply1 = (Player*)m_plylst.GetNextItem())
	{
		l_currcha = l_ply1->m_currcha;
		if (l_currcha >= 0)
		{
			Guild* chaGuild = l_ply1->GetGuild();
			if (!chaGuild)
				continue;

			uLong cha_guildID = chaGuild->m_id;
			if (cha_guildID == guildID)
			{
				l_plylst[l_plynum] = l_ply1;
				l_plynum++;
				continue;
			}
		}
	}
	l.unlock();
	SendToClient(l_plylst, l_plynum, l_wpk);
}


void GroupServerApp::MP_CANRECEIVEREQUESTS(net::TcpClient* client, net::RPacket& pk) {
	uLong chaID = pk.ReadInt64();
	bool CanSend = pk.ReadInt64();
	Player* l_player = FindPlayerByChaID(chaID);
	if(l_player)
	l_player->SetCanReceiveRequests(CanSend);
}


void GroupServerApp::CP_SAY2YOU(Player *ply, net::TcpClient *client, net::RPacket &pk)
{
	if (ply->IsEstop())
	{
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00002));
		return;
	}

	uLong	l_curtick = GetTickCount();
	if (!ply->m_gm && l_curtick - ply->m_toyoutick <const_interval.ToYou)
	{
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00003));
		return;
	}
	ply->m_toyoutick = l_curtick;

	auto	l_you = pk.ReadString();
	if (l_you.empty() || l_you.size() >16)return;
	auto	l_msg = pk.ReadString();
	if (l_msg.empty() || l_msg.size() >200)return;

	Player* l_dst = FindPlayerByChaName(l_you.c_str());
	if (!l_dst || l_dst->m_currcha < 0)
	{
		// destination player offline
		char l_buf[500];
		sprintf(l_buf, RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00004), l_you.c_str());
		ply->SendSysInfo(l_buf);
	}
	else if (ply == l_dst)
	{
		// destination and sender is same
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00005));
	}
	else if (l_dst->m_refuse_tome)
	{
		// destination player is blocking pms
		char l_buf[500];
		sprintf(l_buf, RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00006), l_you.c_str());
		ply->SendSysInfo(l_buf);
	}
	else
	{
		net::WPacket l_wpk(256);
		l_wpk.WriteCmd(CMD_PC_SAY2YOU);
		l_wpk.WriteString(ply->m_chaname[ply->m_currcha].c_str());
		l_wpk.WriteString(l_dst->m_chaname[l_dst->m_currcha].c_str());
		l_wpk.WriteString(l_msg);
		l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
		Player* l_dst1[2];
		l_dst1[0] = ply;
		l_dst1[1] = l_dst;
		SendToClient(l_dst1, 2, l_wpk);

		char PM[32];
		sprintf(PM, "PM - %s", l_you.c_str());
	}
}

void	GroupServerApp::CP_SAY2TEM(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	if( ply->IsEstop() )
	{
		//ply->SendSysInfo( "??��??-��?????��???��?o��?����?��?" );
		ply->SendSysInfo( RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00002) );
		return;
	}

	Team	*l_team		=ply->GetTeam();
	if(!l_team)return;
	auto	l_word		=pk.ReadString();
	if(l_word.empty() ||l_word.size() >200)return;

	Player *l_ply1;
	Player *l_plylst[10240];
	short	l_plynum	=0;

	RunChainGetArmor<TeamMember> l(*l_team);
	while(l_ply1 =static_cast<Player*>(l_team->GetNextItem()))
	{
		l_plylst[l_plynum]	=l_ply1;
		l_plynum ++;
	}
	l.unlock();

	net::WPacket l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SAY2TEM);
	l_wpk.WriteInt64(ply->m_chaid[ply->m_currcha]);
	l_wpk.WriteString(l_word);
	l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
	SendToClient(l_plylst,l_plynum,l_wpk);
}

//TODO: Rename to proper name 
void	GroupServerApp::CP_SAY2GUD(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	if (ply->IsEstop())
	{
		//ply->SendSysInfo( "??��??-��?????��???��?o��?����?��?" );
		ply->SendSysInfo( RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00002) );
		return;
	}

	int canSpeak = (ply->m_guildPermission[ply->m_currcha] & emGldPermSpeak);

	if (canSpeak != emGldPermSpeak){
		//ply->SendSysInfo( "??��??-��?????��???��?o��?����?��?" );
		ply->SendSysInfo("You do not have permission to speak in guild.");
		return;
	}

	Guild	*l_guild = ply->GetGuild();
	if(!l_guild)return;
	auto	l_word		=pk.ReadString();
	if(l_word.empty() ||l_word.size() >200)return;

	Player *l_ply1;
	Player *l_plylst[10240];
	short	l_plynum	=0;

	RunChainGetArmor<GuildMember> l(*l_guild);
	while(l_ply1 =static_cast<Player*>(l_guild->GetNextItem()))
	{
		l_plylst[l_plynum]	=l_ply1;
		l_plynum ++;
	}
	l.unlock();


	net::WPacket l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SAY2GUD);
	l_wpk.WriteString(ply->m_chaname[ply->m_currcha].c_str());		//?��?�㨨?
	l_wpk.WriteString(l_word);
	l_wpk.WriteInt64(ply->m_chatColour[ply->m_currcha]);
	SendToClient(l_plylst,l_plynum,l_wpk);

	char guild[32];
	Guild *l_gld = FindGuildByGldID(ply->m_guild[ply->m_currcha]);
	sprintf(guild, "Guild - %s", l_gld->m_name);
}

//======================================================================

inline void sendfailue(Player *ply,GroupServerApp *gsapp,const char *chaname)
{
	if(!chaname)return;
	net::WPacket l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SESS_CREATE);
	l_wpk.WriteInt64(0);
	l_wpk.WriteString(chaname);
	gsapp->SendToClient(ply,l_wpk);
}
void	GroupServerApp::CP_SESS_CREATE(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	uChar	l_chanum	=pk.ReadInt64();
	if(!l_chanum)
	{
		return;
	}
	if(++(ply->m_chatnum) >const_chat.MaxSession)
	{
		--(ply->m_chatnum);
		if(l_chanum ==1){sendfailue(ply,this,pk.ReadString().c_str());}
		//ply->SendSysInfo("??�̡�?���?��?�������?����y��??-��?��??�̨�3��?��?�䨮��??T��?.");
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00007));
		return;
	}
	if(l_chanum >const_chat.MaxPlayer -1)
	{
		--(ply->m_chatnum);
		if(l_chanum ==1){sendfailue(ply,this,pk.ReadString().c_str());}
		//ply->SendSysInfo("?����a���?��?��?���?��??����y1y?��.");
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00008));
		return;
	}
	std::string			l_chaname;
	Chat_Session	*	l_sess			=0;
	int					l_notiplycount	=0;
	Player			*	l_notiply[Player::emMaxSessPlayer];
	Player			*	l_sessply;
	net::WPacket				l_wpk;
	for(uChar i=0;i<l_chanum;i++)
	{
		l_chaname	=pk.ReadString();
		if(l_chaname.empty() ||l_chaname.size() >16)
		{
			continue;
		}
		if(!(l_sessply =FindPlayerByChaName(l_chaname.c_str())))
		{
			//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"?????��2??��??��?.");
			char l_content[500];
			sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00009),l_chaname.c_str());
			ply->SendSysInfo(l_content);
			continue;
		}

		if(l_sessply ==ply)continue;
		if(l_sess)
		{
			Player	*l_ply1 =0;
			RunChainGetArmor<Chat_Player> l(*l_sess);
			while((l_ply1 =l_sess->GetNextPlayer()) &&l_ply1 !=l_sessply){}
			l.unlock();
			if(l_ply1)continue;
		}

		if(l_sessply->m_refuse_sess)
		{
			//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"??�̡�?���|����?��???��?����䨬?.");
			char l_content[500];
			sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00010),l_chaname.c_str());
			ply->SendSysInfo(l_content);
			continue;
		}
		if(++(l_sessply->m_chatnum) >const_chat.MaxSession)
		{
			--(l_sessply->m_chatnum);
			//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"??��?��?�������?����y��??-��?��??�̨�3��?��?�䨮��??T��?.");
			char l_content[500];
			sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00011),l_chaname.c_str());
			ply->SendSysInfo(l_content);
			continue;
		}
		if(!l_sess)
		{
			l_sess	=AddSession();
			l_sess->AddPlayer(ply);

			l_notiply[l_notiplycount]	=ply;
			++l_notiplycount;
		}
		l_sess->AddPlayer(l_sessply);

		l_notiply[l_notiplycount]	=l_sessply;
		++l_notiplycount;
	}
	if(l_notiplycount)
	{
		bool l_isRepeat	=false;
		{
			auto const lock = std::lock_guard{ply->m_mtxChat};
			for (uLong i = 0; i < ply->m_chatarranum; i++)
			{
				Chat_Session* l_sess1 = ply->m_chat[i]->GetSession();
				if (l_sess1 == l_sess)
				{
					continue;
				}
				if (l_sess1->GetTotal() != l_sess->GetTotal())
				{
					continue;
				}
				Player* l_ply1 = 0, *l_ply2 = 0;
				RunChainGetArmor<Chat_Player> l(*l_sess1);
				while (l_ply1 = l_sess1->GetNextPlayer())
				{
					RunChainGetArmor<Chat_Player> l(*l_sess);
					while (l_ply2 = l_sess->GetNextPlayer())
					{
						if (l_ply1 == l_ply2)
						{
							break;
						}
					}
					l.unlock();
					if (!l_ply2)
					{
						break;
					}
				}
				l.unlock();
				if (!l_ply1)
				{
					l_isRepeat = true;
					break;
				}
			}
		}
		if(!l_isRepeat)
		{
			// Формируем пакет с count-first: sessId, count, [участники...]
			l_wpk	= net::WPacket(256);
			l_wpk.WriteCmd(CMD_PC_SESS_CREATE);
			l_wpk.WriteInt64(l_sess->GetID());
			l_wpk.WriteInt64(l_notiplycount);
			for (int ni = 0; ni < l_notiplycount; ++ni)
			{
				Player* p = l_notiply[ni];
				l_wpk.WriteInt64(p->m_chaid[p->m_currcha]);
				l_wpk.WriteString(p->m_chaname[p->m_currcha].c_str());
				l_wpk.WriteString(p->m_motto[p->m_currcha].c_str());
				l_wpk.WriteInt64(p->m_icon[p->m_currcha]);
			}
			SendToClient(l_notiply,l_notiplycount,l_wpk);
		}else
		{
			Player *l_ply3;
			while(l_ply3 =l_sess->GetFirstPlayer())
			{
				l_sess->DelPlayer(l_ply3);
				--(l_ply3->m_chatnum);
			}
			if(l_chanum ==1){sendfailue(ply,this,l_chaname.c_str());}
			//ply->SendSysInfo("��??-��D��????����?3��?����??��?�㨢?.");
			ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00012));

			l_sess->DelPlayer(ply);
			--(ply->m_chatnum);
			DelSession(l_sess);
		}
	}else
	{
		if(l_chanum ==1){sendfailue(ply,this,l_chaname.c_str());}
		--(ply->m_chatnum);
	}
}
void	GroupServerApp::CP_SESS_ADD(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	uLong	l_sessid		=pk.ReadInt64();
	if(!l_sessid)return;
	auto	l_chaname		=pk.ReadString();
	if(l_chaname.empty() ||l_chaname.size() >16)return;
	auto const lock = std::lock_guard{ply->m_mtxChat};
	Chat_Session  *	l_sess	=ply->FindSessByID(l_sessid);
	if(!l_sess)return;

	Player	*l_sessply		=FindPlayerByChaName(l_chaname.c_str());
	if(!l_sessply || l_sessply->m_currcha <0)
	{
		//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"?????��2??��??��??��");************************
		char l_content[500];
		sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00009),l_chaname.c_str());
		ply->SendSysInfo(l_content);
		return;
	}

	if(l_sessply ==ply)return;
	Player	*l_ply0 =0;
	RunChainGetArmor<Chat_Player> l(*l_sess);
	while((l_ply0 =l_sess->GetNextPlayer()) &&l_ply0 !=l_sessply){}
	l.unlock();
	if(l_ply0)
	{
		//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"??��??-?��??��?��?�������?����???.");
		char l_content[500];
		sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00013),l_chaname.c_str());
		ply->SendSysInfo(l_content);
		return;
	}
	if(l_sessply->m_refuse_sess)
	{
		//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"??�̡�?���|����?��???��?����䨬?.");
		char l_content[500];
		sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00010),l_chaname.c_str());
		ply->SendSysInfo(l_content);
		return;
	}

	if(++(l_sessply->m_chatnum) >const_chat.MaxSession)
	{
		--(l_sessply->m_chatnum);
		//ply->SendSysInfo(dstring("��??��??")<<l_chaname<<"??��?��?�������?����y��??-��?��??�̨�3��?��?�䨮��??T��??��");
		char l_content[500];
		sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00011),l_chaname.c_str());
		ply->SendSysInfo(l_content);
		return;
	}
	if(l_sess->AddPlayer(l_sessply) >const_chat.MaxPlayer)
	{
		l_sess->DelPlayer(l_sessply);
		--(l_sessply->m_chatnum);
		//ply->SendSysInfo("?��?���?��??����y��??-��?��??�̨�3��??T��?��?2??��?������?����??��");
		ply->SendSysInfo(RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00014));
		return;
	}
	int		 l_notiplycount	=0;
	Player	*l_notiply[Player::emMaxSessPlayer];
	Player	*l_sessply1;

	// Собираем участников сессии для формирования пакета с count-first
	RunChainGetArmor<Chat_Player> ll(*l_sess);
	while(l_sessply1 =l_sess->GetNextPlayer())
	{
		if(l_sessply1->m_currcha >=0)
		{
			l_notiply[l_notiplycount] =l_sessply1;
			l_notiplycount ++;
		}
	}
	ll.unlock();
	if(l_notiplycount)
	{
		net::WPacket l_toAdded(256);
		l_toAdded.WriteCmd(CMD_PC_SESS_CREATE);
		l_toAdded.WriteInt64(l_sess->GetID());
		l_toAdded.WriteInt64(l_notiplycount);
		for (int ni = 0; ni < l_notiplycount; ++ni)
		{
			Player* p = l_notiply[ni];
			l_toAdded.WriteInt64(p->m_chaid[p->m_currcha]);
			l_toAdded.WriteString(p->m_chaname[p->m_currcha].c_str());
			l_toAdded.WriteString(p->m_motto[p->m_currcha].c_str());
			l_toAdded.WriteInt64(p->m_icon[p->m_currcha]);
		}
		SendToClient(l_sessply,l_toAdded);

		net::WPacket l_wpk(256);
		l_wpk.WriteCmd(CMD_PC_SESS_ADD);
		l_wpk.WriteInt64(l_sess->GetID());
		l_wpk.WriteInt64(l_sessply->m_chaid[l_sessply->m_currcha]);
		l_wpk.WriteString(l_sessply->m_chaname[l_sessply->m_currcha].c_str());
		l_wpk.WriteString(l_sessply->m_motto[l_sessply->m_currcha].c_str());
		l_wpk.WriteInt64(l_sessply->m_icon[l_sessply->m_currcha]);
		SendToClient(l_notiply,l_notiplycount,l_wpk);
	}else
	{
		--(l_sessply->m_chatnum);
	}
}
void	GroupServerApp::CP_SESS_LEAVE(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	uLong	l_sessid		=pk.ReadInt64();
	if(!l_sessid)return;
	auto const lock = std::lock_guard{ply->m_mtxChat};
	Chat_Session  *	l_sess	=ply->FindSessByID(l_sessid);
	if(!l_sess)return;
	long l_num	=l_sess->DelPlayer(ply);
	if(!l_num)return;
	--(ply->m_chatnum);

	int		 l_notiplycount	=0;
	Player	*l_notiply[Player::emMaxSessPlayer];
	Player	*l_sessply;

	net::WPacket l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SESS_LEAVE);
	l_wpk.WriteInt64(l_sessid);
	l_wpk.WriteInt64(ply->m_chaid[ply->m_currcha]);
	if(l_num >1)
	{
		RunChainGetArmor<Chat_Player> l(*l_sess);
		while(l_sessply =l_sess->GetNextPlayer())
		{
			l_notiply[l_notiplycount] =l_sessply;
			++l_notiplycount;
		}
		l.unlock();
	}
	l_notiply[l_notiplycount] =ply;
	++l_notiplycount;

	SendToClient(l_notiply,l_notiplycount,l_wpk);
	if(l_num == 2)
	{
		net::WPacket l_wpk(256);
		l_wpk.WriteInt64(l_sessid);
		net::RPacket rpkt(l_wpk.Data(), l_wpk.GetPacketSize());
		CP_SESS_LEAVE(l_sess->GetFirstPlayer(),client,rpkt);
	}else if(l_num == 1)
	{
		DelSession(l_sess);
	}
}
void	GroupServerApp::CP_SESS_SAY(Player *ply,net::TcpClient *client,net::RPacket &pk)
{
	if( ply->IsEstop() )
	{
		//ply->SendSysInfo( "??��??-��?????��???��?o��?����?��?" );
		ply->SendSysInfo( RES_STRING(GP_GROUPSERVERAPPCHAT_CPP_00002) );
		return;
	}

	uLong	l_sessid		=pk.ReadInt64();
	if(!l_sessid)return;
	auto	l_word			=pk.ReadString();
	if(l_word.empty() ||l_word.size() >200)return;
	Chat_Session  *	l_sess	=ply->FindSessByID(l_sessid);
	if(!l_sess)return;

	int		 l_notiplycount	=0;
	Player	*l_notiply[Player::emMaxSessPlayer];
	Player	*l_sessply;

	net::WPacket	l_wpk(256);
	l_wpk.WriteCmd(CMD_PC_SESS_SAY);
	l_wpk.WriteInt64(l_sess->GetID());
	l_wpk.WriteInt64(ply->m_chaid[ply->m_currcha]);	//?��?�㨨?
	l_wpk.WriteString(l_word);
	RunChainGetArmor<Chat_Player> l(*l_sess);
	while(l_sessply =l_sess->GetNextPlayer())
	{
		l_notiply[l_notiplycount]	=l_sessply;
		++l_notiplycount;
	}
	l.unlock();
	if(l_notiplycount)
	{
		SendToClient(l_notiply,l_notiplycount,l_wpk);
	}
}
