/* Generated by Together */
#include "stdafx.h"
#include <iostream>
#include "IniFile.h"
#include "GroupServerApp.h"
#include "GameCommon.h"
#include "Team.h"
#include "Script.h"
#include "Parser.h"

using namespace std;

_DBC_USING

void InitDBSvrConnect(GroupServerApp &gpapp);
void InitACTSvrConnect(GroupServerApp &gpapp);	//AccountServer连接

void GroupServerApp::Initialize()
{

	//Sleep(20000);

	m_dwCheatCount = 0;
	LogLine l_line(g_LogConnect);
	l_line<<newln<<"begin connect database"<<endln;
	InitDBSvrConnect(*this);
	m_tblguilds->InitAllGuilds(7);
	const std::string l_acct = m_cfg["AccountServer"]["AcctEnable"];
	if(l_acct	!="0")
	{
		l_line<<newln<<"begin init AccountServer connect"<<endln;
		InitACTSvrConnect(*this);
	}

	LG("init", "init Lua Script...\n");
	if( !InitLuaScript() )
	{
		THROW_EXCP(excp, "init LUA script failed!");
	}

	l_line<<newln<<"begin read GroupServer.cfg"<<endln;
	IniSection	&l_is	=m_cfg["Main"];
	const std::string		l_ip = l_is["Listen_IP"];
	uShort		l_port	= std::stoi(l_is["Listen_Port"]);

	const_cha.MaxChaNum			= std::stoi(m_cfg["character"]["MaxCharacterNum"]);
	const_cha.MaxChaNum			=min(const_cha.MaxChaNum,Player::emMaxCharacters);
	const_cha.MaxIconVal		= std::stoi(m_cfg["character"]["MaxValue"]);
	const_cha.MaxLoginUsr		= std::stoi(m_cfg["character"]["MaxPerson"]);


	const_frnd.InvitedMax		= std::stoi(m_cfg["friend"]["MaxInvitedNum"]);
	const_frnd.PendTimeOut		= std::stoi(m_cfg["friend"]["InvitedTime"])*1000;
	const_frnd.FriendMax		= std::stoi(m_cfg["friend"]["MaxFriendNum"]);
	const_frnd.FriendGroupMax	= std::stoi(m_cfg["friend"]["FriendGroupNum"]);


	const_team.InvitedMax = std::stoi(m_cfg["team"]["MaxInvitedNum"]);
	const_team.PendTimeOut = std::stoi(m_cfg["team"]["InvitedTime"]) * 1000;
	const_team.MemberMax = std::stoi(m_cfg["team"]["MaxPersonNum"]);


	const_master.InvitedMax		= 5;
	const_master.PendTimeOut	= 30000;
	const_master.MasterMax		= 1;
	const_master.PrenticeMax	= 4;

	const_chat.MaxSession		= std::stoi(m_cfg["chat"]["MaxChatNumPerPlayer"]);
	const_chat.MaxSession		=min(const_chat.MaxSession,Player::emMaxSessChat);
	const_chat.MaxPlayer		= std::stoi(m_cfg["chat"]["maxPlayerPerChat"]);
	const_chat.MaxPlayer		=min(const_chat.MaxPlayer,Player::emMaxSessPlayer);


	const_interval.World = std::stoi(m_cfg["chat"]["WorldInterval"]) * 1000;
	const_interval.Trade = std::stoi(m_cfg["chat"]["TradeInterval"]) * 1000;
	const_interval.ToYou = std::stoi(m_cfg["chat"]["ToYouInterval"]) * 1000;


	if(!InitMasterRelation())
	{
		THROW_EXCP(excp, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00001));
	}

	l_line<<newln<<"begin load ChaNameFilter.txt"<<endln;
	CTextFilter::LoadFile("ChaNameFilter.txt");
	l_line<<newln<<"begin listen port:"<<l_port<<endln;

	// CorsairsNet: Listen через TcpServer
	if(!m_server.Listen(l_ip, l_port, GATE_MAX))
	{
		char l_content[500];
		sprintf(l_content,RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00002),l_ip.c_str(), l_port, l_port);
		THROW_EXCP(excpSock,l_content);
	}
	l_line<<newln<<"open listen port:"<<l_port<<"success, init is ok"<<endln;
}

void InitDBSvrConnect(GroupServerApp &gpapp)
{
	LG("group_sql", RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00030));
	string	l_errinfo;

	const std::string	l_dsn = gpapp.m_cfg["Database"]["dsnGameDb"];
	gpapp.m_cfg_db.enable_errinfo();

	LG("group_sql", "begin connect database, dsn = [%s]\n", l_dsn.c_str());
	if(!gpapp.m_cfg_db.connect(l_dsn.c_str(), l_errinfo))
	{
		LG("group_sql", "connect database failed, error[%s]\n", l_errinfo.c_str());
		THROW_EXCP(excpDB,l_errinfo.c_str());
	}

	LG("group_sql", "connect database ok, begin init datatable\n");

	gpapp.m_tblaccounts		=new TBLAccounts(&(gpapp.m_cfg_db));
	gpapp.m_tblcharaters	=new TBLCharacters(&(gpapp.m_cfg_db));
	gpapp.m_tblfriends		=new TBLFriends(&(gpapp.m_cfg_db));
	gpapp.m_tblmaster		=new TBLMaster(&(gpapp.m_cfg_db));
	gpapp.m_tblguilds		=new TBLGuilds(&(gpapp.m_cfg_db));
	gpapp.m_tblX1			=new friend_tbl(&(gpapp.m_cfg_db));
	gpapp.m_tbLparam		=new TBLParam(&(gpapp.m_cfg_db));

	LG("group_sql", "begin check table [account] \n");
	if(!gpapp.m_tblaccounts->IsReady())
	{
		LG("group_sql", " check table [account] failed\n");
		THROW_EXCP(excpDB,RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00003));
	}

	LG("group_sql", "begin check table [guild]\n");
	if(!gpapp.m_tblguilds->IsReady())
	{
		LG("group_sql", " check table [guild] failed \n");
		THROW_EXCP(excpDB,RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00004));
	}
	gpapp.m_tblcharaters->ZeroAddr();

	LG("group_sql", "begin check table [param]\n");

	if(gpapp.m_tbLparam->InitParam())
	LG("group_sql", "init database success\n");
}

void InitACTSvrConnect(GroupServerApp &gpapp)
{
	gpapp.m_name		=gpapp.m_cfg["Main"]["Name"];
	IniSection	&l_is	=gpapp.m_cfg["AccountServer"];
	const std::string	l_passwd	=l_is["Password"];
	const std::string	l_ip = l_is["IP"];
	uShort	l_port		=std::stoi(l_is["Port"]);

	char buffer[512];

	while(!g_exit && !gpapp.m_acctClient.IsConnected())
	{
		if(!gpapp.m_acctClient.Connect(l_ip, l_port))
		{
			memset(buffer, 0, sizeof(buffer));
			sprintf(buffer, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00005), l_ip.c_str(), l_port);
			std::cout<<buffer<<std::endl;
			Sleep(5000);
			continue;
		}

		// AsyncCall: CMD_PA_LOGIN → callback обработает ответ
		net::WPacket l_wpk(256);
		l_wpk.WriteCmd(CMD_PA_LOGIN);
		l_wpk.WriteString(gpapp.m_name.c_str());
		l_wpk.WriteString(l_passwd.c_str());

		// Используем блокирующий подход при инициализации:
		// AsyncCall + busy-wait на результат
		volatile bool gotResponse = false;
		volatile bool loginOk = false;

		gpapp.m_acctClient.AsyncCall(l_wpk, 10000, [&](net::RPacket& rpk) {
			if (!rpk) {
				// Таймаут или ошибка
				memset(buffer, 0, sizeof(buffer));
				sprintf(buffer, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00006), l_ip.c_str(), l_port);
				std::cout << buffer << std::endl;
			} else if (rpk.ReadInt64()) {
				// Ненулевой код = ошибка
				memset(buffer, 0, sizeof(buffer));
				sprintf(buffer, RES_STRING(GP_GROUPSERVERAPPINIT_CPP_00007), l_ip.c_str(), l_port);
				std::cout << buffer << std::endl;
			} else {
				loginOk = true;
			}
			gotResponse = true;
		});

		// Ждём ответа (PollPackets вызывает callback)
		while (!gotResponse && gpapp.m_acctClient.IsConnected()) {
			gpapp.m_acctClient.PollPackets(0);
			Sleep(10);
		}

		if (!loginOk) {
			gpapp.m_acctClient.Disconnect(0);
			if (!g_exit) Sleep(5000);
			continue;
		}

		std::cout << "AccountServer login OK" << std::endl;
		break;
	}
}
