/* Generated by Together */
#include "stdafx.h"
#include <time.h>
#include <iostream>
#include <signal.h>

#include "GroupServerApp.h"
#include "GameCommon.h"
#include "Guild.h"
#include "Player.h"
#include "util.h"
#include "Team.h"
#include "Script.h"
#include "Parser.h"

using namespace std;

bool	g_logautobak	=true;

dbc::LogStream			g_LogErrServer("ErrorServer");
dbc::LogStream			g_LogGrpServer("GroupServer");
dbc::LogStream			g_LogGuild("Guild");
dbc::LogStream			g_LogFriend("Friend");
dbc::LogStream			g_LogMaster("Master");
dbc::LogStream			g_LogTeam("Team");
dbc::LogStream			g_LogConnect("Connect");
dbc::LogStream			g_LogDB("Database");
dbc::LogStream			g_LogGarner2("Garner2");

GroupServerApp	*	g_gpsvr	=0;
InterLockedLong		g_exit	=0;
InterLockedLong		g_ref	=0;
GMBBS			*	g_gmbbs	=0;
TimerMgr			g_timermgr;
//=========Timer==============
extern BOOL GetOnlineCount( DWORD& dwLoginNum, DWORD& dwPlayerNum );

class AddStatLog: public Timer
{
public:
	AddStatLog(uLong interval):Timer(interval){}
private:
	void Process()
	{
		RefArmor l(g_ref);
		if(!g_exit)
		{
			static long	l_lastlogin =-1;
			static long	l_lastplay	=-1;
			long l_loginum	=g_gpsvr->m_plylst.GetTotal();
			long l_playnum	=long(g_gpsvr->m_curChaNum);
			long l_wgplaynum = long(g_gpsvr->m_curWGChaNum);

			static short sStatCheatCount = 0;
			if(sStatCheatCount == 0)
			{
				// Счётчик читов
			ToLogService("players", LogLevel::Warning, "current cheat count [{}]", (int)g_gpsvr->m_dwCheatCount);
			}
			sStatCheatCount = (sStatCheatCount + 1) % 60;

			{
				auto const l_lockDB = std::lock_guard{g_gpsvr->m_mtxDB};

				DWORD dwLoginNum = (DWORD)l_loginum;
				DWORD dwPlayerNum = (DWORD)l_playnum;
				if( GetOnlineCount( dwLoginNum, dwPlayerNum ) )
				{
					l_loginum = dwLoginNum;
					l_playnum = dwPlayerNum;
				}

				g_gpsvr->m_tblaccounts->AddStatLog(l_loginum,l_playnum,l_wgplaynum);

				l_lastlogin	=l_loginum;
				l_lastplay	=l_playnum;
			}
		}
	}
};
extern "C"{WINBASEAPI HWND APIENTRY GetConsoleWindow(VOID);}
class DisableCloseButton: public Timer
{
public:
	DisableCloseButton(uLong interval):Timer(interval),m_hMenu(0)
	{
		HWND hWnd	= ::GetConsoleWindow();
		m_hMenu		= GetSystemMenu(hWnd, FALSE);
	}
private:
	~DisableCloseButton()
	{
	}
	void Process()
	{
		RefArmor l(g_ref);
		if (!g_exit && m_hMenu)
		{
			EnableMenuItem(m_hMenu, SC_CLOSE, MF_BYCOMMAND | MF_GRAYED);
		}
	}
	HMENU m_hMenu;
};
GMBBS::GMBBS(uLong interval):Timer(interval),m_dwCount(0)
{
	for(uLong i=0;i<em_words;i++)
	{
		m_queue[i].m_times=0;
	}
	g_gmbbs	=this;
}
GMBBS::~GMBBS(){g_gmbbs	=0;}
bool GMBBS::AddBBS(uLong inter,uLong times,const char *word)
{
	auto const l_lockQue = std::lock_guard{m_mtxque};
	uLong i = 0;
	for(;i<em_words && m_queue[i].m_times;i++);
	if(i==em_words)return false;
	m_queue[i].m_start	=m_dwCount;
	m_queue[i].m_inter	=inter*10;
	m_queue[i].m_times	=times;
	m_queue[i].m_word	=word;
	return true;
}

void GMBBS::Process()
{
	++m_dwCount;
	auto const l_lockQue = std::lock_guard{m_mtxque};
	for(uLong i=0;i<em_words;i++)
	{
		if(m_queue[i].m_times && (m_dwCount -m_queue[i].m_start)%m_queue[i].m_inter ==1)
		{
			net::WPacket l_wpk(256);
			l_wpk.WriteCmd(CMD_MC_SYSINFO);
			l_wpk.WriteString(m_queue[i].m_word);

			Player *l_plylst[10240];
			short	l_plynum	=0;

			Player	*	l_ply1	=0;char	l_currcha	=0;
			RunChainGetArmor<Player> l(g_gpsvr->m_plylst);
			while(l_ply1	=g_gpsvr->m_plylst.GetNextItem())
			{
				if((l_currcha =l_ply1->m_currcha) >=0)
				{
					l_plylst[l_plynum]	=l_ply1;
					l_plynum ++;
				}
			}
			l.unlock();
			g_gpsvr->SendToClient(l_plylst,l_plynum,l_wpk);


			if(!--(m_queue[i].m_times))
			{
				m_queue[i].m_word.clear();
			}
		}
	}
}
void __cdecl ctrlc_dispatch(int sig)
{
	if (sig == SIGINT)
	{
		g_exit	=1;
		signal(SIGINT, ctrlc_dispatch);
	}
}

// AcctClientHandler: при разрыве AccountServer — переподключение
void GroupServerApp::AcctClientHandler::OnDisconnected(int reason) {
	std::cout << "[GroupServer] AccountServer отключён, reason=" << reason << std::endl;
	LogLine l_line(g_LogConnect);
	l_line << newln << "AccountServer disconnected, reason=" << reason << endln;

	if (g_exit) return;

	std::cout << "after 5 seconds reconnect......" << std::endl;
	// Reconnect будет вызван из PollNetwork
}

GroupServerApp::GroupServerApp()
	: m_plyheap(1,1000),
	  m_gldheap(1,100),
	  m_teamheap(1,300),
	  m_gatenum(0),
	  m_tblaccounts(0),
	  m_tblcharaters(0),
	  m_tblfriends(0),
	  m_tblguilds(0),
	  m_tbLparam(0),
	  m_tblX1(0),
	  m_cfg("GroupServer.cfg"),
	  m_curChaNum(0),
	  m_curWGChaNum(0)
{
	g_gpsvr	=this;

	m_server.SetHandler(this);
	m_acctClient.SetHandler(&m_acctHandler);

	m_plyheap.Init();
	m_gldheap.Init();
	m_teamheap.Init();

	srand( (unsigned int)time( NULL ) );
	try
	{
		Initialize();
		g_timermgr.AddTimer(new AddStatLog(10*1000));
		g_timermgr.AddTimer(new DisableCloseButton(200));
		g_timermgr.AddTimer(new GMBBS(1000));
		signal(SIGINT, ctrlc_dispatch);

		m_mapBirthplace["Shaitan City"] = "magicsea";
		m_mapBirthplace["Icicle Castle"] = "darkblue";
		m_mapBirthplace["Argent City"] = "garner";
	}
	catch(excp &e)
	{
		std::cout<<e.what()<<std::endl;
		LogLine l_line(g_LogConnect);
		l_line<<newln<<e.what()<<endln;
		try{GroupServerApp::~GroupServerApp();}catch(...){}
		throw e;
	}
	catch(...)
	{
		std::cout<<"GroupServer init unkonwn exception, please contact developer"<<std::endl;
		try{GroupServerApp::~GroupServerApp();}catch(...){}
		throw;
	}
}

GroupServerApp::~GroupServerApp()
{
	m_exitFlag = true;
	m_server.Shutdown();
	m_acctClient.Disconnect(0);

	auto const l_lock = std::lock_guard{m_mtxDB};
	if(m_tblX1)
	{
		delete m_tblX1;
		m_tblX1	=0;
	}
	if(m_tblguilds)
	{
		delete m_tblguilds;
		m_tblguilds	=0;
	}
	if(m_tblfriends)
	{
		delete m_tblfriends;
		m_tblfriends=0;
	}
	if(m_tblcharaters)
	{
		delete m_tblcharaters;
		m_tblcharaters	=0;
	}
	if(m_tblaccounts)
	{
		delete m_tblaccounts;
		m_tblaccounts	=0;
	}
	if(m_tbLparam)
	{
		delete m_tbLparam;
		m_tbLparam = 0;
	}
	CloseLuaScript();
}

// ── PollNetwork ────────────────────────────────────────────
void GroupServerApp::PollNetwork()
{
	// Обработать GateServer подключения
	m_server.PollAll(50);

	// Обработать AccountServer пакеты (+ RPC callbacks)
	if (m_acctClient.IsConnected()) {
		m_acctClient.PollPackets(50);
	}
}

// ── ITcpServerHandler callbacks ────────────────────────────

bool GroupServerApp::OnAccepted(net::TcpClient* client)
{
	return true;
}

void GroupServerApp::OnPacket(net::TcpClient* client, net::RPacket& pkt)
{
	uint32_t sess = pkt.GetSess();
	if (sess > 0 && !(sess & 0x80000000)) {
		// Incoming RPC (GateServer → GroupServer) — ответить с SESS|FLAG
		HandleServeCall(client, pkt);
	} else {
		// Async пакет
		OnProcessData(client, pkt);
	}
}

void GroupServerApp::OnDisconnected(net::TcpClient* client, int reason)
{
	GateServer* l_gate = (GateServer*)client->GetPointer();
	if (!l_gate) {
		return;
	}
	m_mtxlogin.lock();
	try {
		l_gate->SetClient(nullptr);
	}
	catch (...) {
	}
	m_mtxlogin.unlock();
	LogLine l_line(g_LogConnect);
	l_line << newln << "GateServer:" << client->GetPeerIP() << "," << client->GetPeerPort() <<
		"go ! Socket num:" << m_server.GetConnectionCount() << "reason=(" << reason << ")" << endln;
	std::cout << "GateServer:" << client->GetPeerIP() << "," << client->GetPeerPort() << " go ! Socket num:"
		<< m_server.GetConnectionCount() << " reason=" << reason << std::endl;

	Player* l_ply = 0;
	RunChainGetArmor<Player> l(m_plylst);
	while (l_ply = m_plylst.GetNextItem()) {
		if (l_ply->m_gate == l_gate) {
			net::RPacket l_rpk;
			TP_USER_LOGOUT(l_ply, client, l_rpk);
		}
	}
	l.unlock();
}

void GroupServerApp::SendToAllClients(const net::WPacket& wpk)
{
	auto& player_list = g_gpsvr->m_plylst;
	RunChainGetArmor<Player> l(player_list);

	const auto total = player_list.GetTotal();
	for (auto n = 0; n < total;)
	{
		size_t size{};
		std::array<Player*, 600> players;
		for (auto* player = player_list.GetNextItem(); player; player = player_list.GetNextItem())
		{
			if (player->m_currcha < 0)
			{
				continue;
			}

			players[size] = player;
			if (++size; size >= players.size())
			{
				break;
			}
		}

		if (size == 0)
		{
			break;
		}

		g_gpsvr->SendToClient(players.data(), size, wpk);
		n += size;
	}
}

void GroupServerApp::SendToClient(Player* ply[],short cli_num,const net::WPacket &wpk)
{
	net::WPacket l_wpk2; uShort l_count2;
	for (auto& gate : m_gate)
	{
		if (!gate.IsValid()) {
			continue;
		}
		l_wpk2 = wpk;
		l_count2 = 0;

		for (auto i = 0; i < cli_num; ++i)
		{
			if (ply[i]->m_gate == &gate && ply[i]->m_currcha >= 0)
			{
				l_wpk2.WriteInt64(ToAddress(ply[i]));
				l_wpk2.WriteInt64(ply[i]->m_gtAddr);
				++l_count2;
			}
		}
		if (l_count2)
		{
			l_wpk2.WriteInt64(l_count2);
			gate.SendData(l_wpk2);
		}
	}
}
void GroupServerApp::SendToClient(Player* ply, net::WPacket &wpk)
{
	if(ply && ply->m_gate)
	{
		wpk.WriteInt64(ToAddress(ply));
		wpk.WriteInt64(ply->m_gtAddr);
		wpk.WriteInt64(1);
		ply->m_gate->SendData(wpk);
	}
}

GateServer* GroupServerApp::FindGateSByName(cChar* gatename)
{
	for (auto i = 0; i < m_gatenum; ++i)
	{
		if (m_gate[i].m_name == gatename)
			return &m_gate[i];
	}
	return nullptr;
}

Guild * GroupServerApp::FindGuildByName(cChar * gldname)
{
	Guild	*l_gld	=0;
	RunChainGetArmor<Guild> l(m_gldlst);
	while(l_gld	=m_gldlst.GetNextItem())
	{
		if(!strcmp(l_gld->m_name,gldname))break;
	}
	l.unlock();
	return l_gld;
}
Guild * GroupServerApp::FindGuildByGldID(uLong	gldid)
{
	Guild	*l_gld	=0;
	RunChainGetArmor<Guild> l(m_gldlst);
	while(l_gld	=m_gldlst.GetNextItem())
	{
		if(l_gld->m_id ==gldid)break;
	}
	l.unlock();
	return l_gld;
}
Guild *	GroupServerApp::FindGuildByLeadID(uLong chaid)
{
	Guild	*l_gld	=0;
	RunChainGetArmor<Guild> l(m_gldlst);
	while(l_gld	=m_gldlst.GetNextItem())
	{
		if(l_gld->m_leaderID ==chaid)break;
	}
	l.unlock();
	return l_gld;
}
Player * GroupServerApp::FindPlayerByChaName(cChar * plyname)
{
	Player	*l_ply	=0;char	l_currcha	=0;
	RunChainGetArmor<Player> l(m_plylst);
	while(l_ply	=m_plylst.GetNextItem())
	{
		if(((l_currcha =l_ply->m_currcha) >=0)&&(l_ply->m_chaname[l_currcha] ==plyname))break;
	}
	l.unlock();
	return l_ply;
}
Player * GroupServerApp::FindPlayerByChaID(uLong chaid)
{
	Player	*l_ply	=0;char	l_currcha	=0;
	RunChainGetArmor<Player> l(m_plylst);
	while(l_ply	=m_plylst.GetNextItem())
	{
		if(((l_currcha =l_ply->m_currcha) >=0)&&(l_ply->m_chaid[l_currcha] ==chaid))break;
	}
	l.unlock();
	return l_ply;
}

Player *GroupServerApp::GetPlayerByChaID(uLong chaid)
{
	map<uLong, Player *>::iterator it = m_mapPlayerList.find(chaid);
	if(it != m_mapPlayerList.end())
	{
		return m_mapPlayerList[chaid];
	}
	return NULL;
}

bool GroupServerApp::AddPlayerToList(uLong chaid, Player *pPlayer)
{
	map<uLong, Player *>::iterator it = m_mapPlayerList.find(chaid);
	if(it != m_mapPlayerList.end())
	{
		return false;
	}
	m_mapPlayerList[chaid] = pPlayer;
	return true;
}

bool GroupServerApp::DelPlayerFromList(uLong chaid)
{
	map<uLong, Player *>::iterator it = m_mapPlayerList.find(chaid);
	if(it != m_mapPlayerList.end())
	{
		m_mapPlayerList.erase(it);
		return true;
	}
	return false;
}
