/* Generated by Together */

#ifndef GRPNAMESVR_H
#define GRPNAMESVR_H
#include "Task.h"
#include "PreAlloc.h"
#include "RunCtrlThrd.h"
#include "IniFile.h"
#include "LogStream.h"

#include "CorsairsNet.h"

#include "GateServer.h"
#include "Player.h"
#include "Guild.h"
#include "Team.h"
#include "SessionChat.h"
#include "DBConnect.h"

#include "i18n.h"

// Add by lark.li 20080801 begin
#include "pi_Memory.h"
#include "pi_Alloc.h"
// End
#include <array>

_DBC_USING

class GroupServerApp : public net::ITcpServerHandler {
public:
	GroupServerApp();
	~GroupServerApp();

	uLong	m_dwCheatCount;	//使用外挂次数
public:
	friend void Player::EndPlay(net::TcpClient *client);
	void Initialize();
	void Finalize();

	// net::ITcpServerHandler callbacks
	bool	OnAccepted(net::TcpClient *client) override;
	void	OnPacket(net::TcpClient *client, net::RPacket &pkt) override;
	void	OnDisconnected(net::TcpClient *client, int reason) override;

	// Обработка пакетов (бывший OnProcessData + OnServeCall)
	void	OnProcessData(net::TcpClient *client, net::RPacket &recvbuf);
	void	HandleServeCall(net::TcpClient *client, net::RPacket &pk);

	bool GetCHAsFromDBByPlayer(Player *player, net::WPacket &wpk);
	bool CanCreateBonusChar(Player* player);
	char SendCharData(Player* player, net::WPacket& wpk);
	int  GetChaCount(Player* player);
	void RefreshClients(Player* player, char delChaSlot = -1);

	net::WPacket	TP_REGISTER(net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_LOGIN(net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_USER_LOGIN(net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_USER_LOGOUT(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_BGNPLAY(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_ENDPLAY(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_NEWCHA(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_DELCHA(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_CREATE_PASSWORD2(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_UPDATE_PASSWORD2(Player *ply, net::TcpClient *client, net::RPacket &pk);
	net::WPacket	TP_CHANGEPASS(Player * l_ply, net::TcpClient *client, net::RPacket &pk);


	void	MP_ENTERMAP(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_ONLINE(Player *ply);
	void	MP_SWITCH(Player *ply);
	void	PC_FRND_INIT(Player *ply);
	void	PC_GM_INIT(Player *ply);
	void	PC_GULD_INIT(Player *ply);
	void	PC_MASTER_INIT(Player *ply);

	void	MP_TEAM_CREATE(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	MP_MASTER_CREATE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_MASTER_DEL(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_MASTER_FINISH(Player *ply, net::TcpClient *client, net::RPacket &pk);

	net::WPacket	TP_REQPLYLST(net::TcpClient *client, net::RPacket &pk);
	void	AP_KICKUSER(net::TcpClient *client, net::RPacket &pk);
	void	AP_KICKUSER2(net::TcpClient* client, uLong acctid);
    void    AP_EXPSCALE(net::TcpClient* client, net::RPacket &pk);

	void	TP_DISC(net::TcpClient *client, net::RPacket &pk);
	void	TP_ESTOPUSER_CHECK(net::TcpClient *client, net::RPacket &pk);

	void	CP_TEAM_INVITE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_TEAM_ACCEPT(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_TEAM_REFUSE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_TEAM_LEAVE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_TEAM_KICK(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	CP_FRND_INVITE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_FRND_ACCEPT(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_FRND_REFUSE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_FRND_DELETE(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	CP_FRND_CHANGE_GROUP(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_FRND_REFRESH_INFO(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_CHANGE_PERSONINFO(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	CP_MASTER_INVITE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_MASTER_ACCEPT(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_MASTER_REFUSE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_MASTER_DELETE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_PRENTICE_DELETE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_MASTER_REFRESH_INFO(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_PRENTICE_REFRESH_INFO(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	CP_REFUSETOME(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_GM1SAY(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_GM1SAY1(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	CP_SAY2TRADE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SAY2ALL(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SAY2YOU(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SAY2TEM(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SAY2GUD(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	MP_SAY2ALL(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_SAY2TRADE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILDNOTICE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_CANRECEIVEREQUESTS(net::TcpClient* client, net::RPacket& pk);

	void	CP_SESS_CREATE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SESS_SAY(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SESS_ADD(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	CP_SESS_LEAVE(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	MP_GUILD_APPROVE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILD_CREATE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILD_KICK(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILD_LEAVE(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILD_DISBAND(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILD_MOTTO(Player *ply, net::TcpClient *client, net::RPacket	&pk);
	void	MP_GUILD_CHALLMONEY(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GUILD_CHALL_PRIZEMONEY(Player *ply, net::TcpClient *client, net::RPacket &pk);

	void	MP_GM_BANACCOUNT(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_GM_UNBANACCOUNT(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	MP_MUTE_PLAYER(Player* player, net::TcpClient* client, net::RPacket& pk);

	void	CP_PING(Player* ply, net::TcpClient* client, net::RPacket& pk);
	void	CP_REPORT_WG(Player *ply, net::TcpClient *client, net::RPacket &pk);

	// Add by lark.li 20081119 begin
	net::WPacket	TP_SYNC_PLYLST(net::TcpClient *client, net::RPacket &pk);
	net::WPacket	OS_LOGIN(net::TcpClient *client, net::RPacket &pk);
	void	OS_PING(net::TcpClient *client, net::RPacket &pk);
	// End

	void	MP_GARNER2_UPDATE(Player *ply, net::TcpClient *client, net::RPacket &pk);

	bool	CheckFunction(std::string mapName, std::string funName);

	// Сетевой цикл: вызывать из main loop
	void	PollNetwork();

public:
	void	CP_GARNER2_GETORDER(Player *ply, net::TcpClient *client, net::RPacket &pk);
	void	KickUser(net::TcpClient *client, uLong gpaddr, uLong gtaddr);
	void	SendToAllClients(const net::WPacket& wpk);
	void	SendToClient(Player* ply[], short cli_num, const net::WPacket& wpk);
	void	SendToClient(Player* ply, net::WPacket &wpk);
	GateServer	*	FindGateSByName(cChar *gatename);
	Guild		* 	FindGuildByName(cChar * gldname);
	Guild		* 	FindGuildByGldID(uLong	gldid);
	Guild		*	FindGuildByLeadID(uLong chaid);
	Player		*	FindPlayerByChaName(cChar * plyname);
	Player		*	FindPlayerByChaID(uLong chaid);

	Player *GetPlayerByChaID(uLong chaid);
	bool AddPlayerToList(uLong chaid, Player *pPlayer);
	bool DelPlayerFromList(uLong chaid);


	static constexpr auto GATE_MAX{ 10 };
	std::array<GateServer, GATE_MAX> m_gate;

	// Add by lark.li 20081119 begin
	GroupServerAgent m_groupServerAgent;
	// End

	// Сетевые компоненты (CorsairsNet)
	net::TcpServer	m_server;		// Принимает GateServer подключения
	net::TcpClient	m_acctClient;	// Исходящее подключение к AccountServer

	struct
	{
		std::recursive_mutex			m_mtxlogin;
		std::recursive_mutex			m_mtxSyn;
		short			m_gatenum;
		std::string			m_name;
		// Add by lark.li 20081119 begin
		std::recursive_mutex			m_mtxAgent;
		// End
	};

	//内部数据结构：
	PreAllocHeap<Player>		m_plyheap;
	RunBiDirectChain<Player> 	m_plylst;
	PreAllocHeap<Guild>			m_gldheap;
	RunBiDirectChain<Guild> 	m_gldlst;
	PreAllocHeap<Team>			m_teamheap;
	RunBiDirectChain<Team>		m_teamlst;
	RunCtrlMgr<Invitation>		m_plyproc;

	RunBiDirectChain<Chat_Session>		m_sesslst;
	Chat_Session *AddSession();
	void  DelSession(Chat_Session * sess);

	//数据库连接：
	struct
	{
		std::recursive_mutex			m_mtxDB;
		cfl_db			m_cfg_db;
		TBLAccounts	*	m_tblaccounts;
		TBLCharacters*	m_tblcharaters;
		TBLFriends	*	m_tblfriends;
		TBLMaster	*	m_tblmaster;
		TBLGuilds	*	m_tblguilds;
		TBLParam	*	m_tbLparam;
		friend_tbl	*	m_tblX1;
		IniFile			m_cfg;
		InterLockedLong	m_curChaNum;
		InterLockedLong	m_curWGChaNum;
	};
	struct
	{
		char			MaxChaNum;
		short			MaxIconVal;
		short			MaxLoginUsr;
	} const_cha;
	struct
	{
		char  InvitedMax;		// =5;
		uLong PendTimeOut;		//=30*1000
		char  FriendMax;		//=100
		char  FriendGroupMax;	//=10
	} const_frnd;
	struct
	{
		char  InvitedMax;		// =5
		uLong PendTimeOut;		//=30*1000
		char  MemberMax;		// =5
	} const_team;
	struct
	{
		char  InvitedMax;		// =5;
		uLong PendTimeOut;		//=30*1000
		char  MasterMax;		//=1
		char  PrenticeMax;		//=4
	} const_master;
	struct
	{
		uShort MaxSession;		// =3
		uShort MaxPlayer;		// =30
	} const_chat;
	struct
	{
		uLong  World;
		uLong  Trade;
		uLong  ToYou;
	} const_interval;

	std::atomic<bool> m_exitFlag{false};

private:
	bool InitMasterRelation();
	int GetMasterCount(uLong atorID);
	int GetPrenticeCount(uLong atorID);
	int HasMaster(uLong cha_id1,uLong cha_id2);
	bool AddMaster(uLong cha_id1,uLong cha_id2);
	bool DelMaster(uLong cha_id1,uLong cha_id2);
	bool FinishMaster(uLong atorID);

	std::map<uLong, uLong> m_mapMasterRelation;
	std::map<uLong, Player *> m_mapPlayerList;

	// Add by lark.li 20080702 begin
	std::map<std::string, std::string> m_mapBirthplace;
	// End

	// Внутренний handler для AccountServer
	struct AcctClientHandler : public net::ITcpClientHandler {
		void OnPacket(net::RPacket& packet) override {}
		void OnDisconnected(int reason) override;
	};
	AcctClientHandler m_acctHandler;
};
class GMBBS:public Timer
{
	enum{em_words	=30};
public:
	GMBBS(uLong interval);
	bool AddBBS(uLong inter,uLong times,const char *word);
private:
	~GMBBS();
	void Process();
	struct
	{
		uLong	volatile	m_start;
		uLong	volatile	m_inter;
		uLong	volatile	m_times;
		std::string			 	m_word;
	}	m_queue[em_words];
	std::recursive_mutex	m_mtxque;

	uLong	m_dwCount;
};

extern void InitACTSvrConnect(GroupServerApp &gpapp);	//AccountServer连接
extern GroupServerApp * g_gpsvr;
extern InterLockedLong	g_exit;
extern InterLockedLong	g_ref;
extern LogStream			g_LogGrpServer;
extern LogStream			g_LogErrServer;
extern LogStream			g_LogGuild;
extern LogStream			g_LogFriend;
extern LogStream			g_LogMaster;
extern LogStream			g_LogTeam;
extern LogStream			g_LogConnect;
extern LogStream			g_LogDB;
extern LogStream			g_LogGarner2;
extern GMBBS		*		g_gmbbs;
extern HANDLE				hConsole;

#define C_PRINT(s, ...) \
	SetConsoleTextAttribute(hConsole, 14); \
	printf(s, __VA_ARGS__); \
	SetConsoleTextAttribute(hConsole, 10);

#define C_TITLE(s) \
	char szPID[32]; \
	_snprintf_s(szPID,sizeof(szPID),_TRUNCATE, "%d", GetCurrentProcessId()); \
	std::string strConsoleT; \
	strConsoleT += "[PID:"; \
	strConsoleT += szPID; \
	strConsoleT += "]"; \
	strConsoleT += s; \
	SetConsoleTitle(strConsoleT.c_str());

#endif //GRPNAMESVR_H
