-- Полная миграция gamedb на UTF-8 collation.
-- Шаги: DROP defaults → DROP indexes → ALTER COLUMN → CREATE indexes → CREATE defaults.

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRAN;

PRINT '-- PHASE 1: DROP defaults';
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_skill_state];
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_boat_createtime];
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_boat_isdeleted];
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_map];
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_boat_name];
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_boat_bag];
ALTER TABLE [dbo].[boat] DROP CONSTRAINT [DF_boat_boat_isdie];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_motto];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_job];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_map];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_look];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_kitbag];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_skillbag];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_shortcut_1];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_mission];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_misrecord];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_trigger];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_miscount];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_birth];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_login_cha];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_map_mask];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_main_map];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_skill_state];
ALTER TABLE [dbo].[character] DROP CONSTRAINT [DF_character_bank];
ALTER TABLE [dbo].[character_log] DROP CONSTRAINT [DF_character_log_job];
ALTER TABLE [dbo].[character_log] DROP CONSTRAINT [DF_character_log_map];
ALTER TABLE [dbo].[character_log] DROP CONSTRAINT [DF_character_log_look];
ALTER TABLE [dbo].[guild] DROP CONSTRAINT [DF_guild_guild_name];
ALTER TABLE [dbo].[guild] DROP CONSTRAINT [DF_guild_motto];
ALTER TABLE [dbo].[guild] DROP CONSTRAINT [DF_guild_passwd];
ALTER TABLE [dbo].[guild] DROP CONSTRAINT [DF_guild_bank];
ALTER TABLE [dbo].[guild] DROP CONSTRAINT [DF__guild__banklog__7D0E9093];
ALTER TABLE [dbo].[map_mask] DROP CONSTRAINT [DF_map_mask_content];
ALTER TABLE [dbo].[map_mask] DROP CONSTRAINT [DF_map_mask_content4];
ALTER TABLE [dbo].[map_mask] DROP CONSTRAINT [DF_map_mask_content3];
ALTER TABLE [dbo].[map_mask] DROP CONSTRAINT [DF_map_mask_content2];
ALTER TABLE [dbo].[map_mask] DROP CONSTRAINT [DF_map_mask_content1];
ALTER TABLE [dbo].[master] DROP CONSTRAINT [DF_master_relation];
ALTER TABLE [dbo].[Resource] DROP CONSTRAINT [DF_Recource_content];

PRINT '-- PHASE 2: DROP indexes/PK/UK';
ALTER TABLE [dbo].[character] DROP CONSTRAINT [IX_character];
ALTER TABLE [dbo].[guild] DROP CONSTRAINT [IX_guild_name];
ALTER TABLE [dbo].[StatGender] DROP CONSTRAINT [PK_StatGender];
ALTER TABLE [dbo].[StatJob] DROP CONSTRAINT [PK_StatJob];
ALTER TABLE [dbo].[StatMap] DROP CONSTRAINT [PK_StatMap];

PRINT '-- PHASE 3: ALTER COLUMNS (varchar N*4 + UTF-8 collation)';
ALTER TABLE [dbo].[account] ALTER COLUMN [ato_nome] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[account] ALTER COLUMN [ator_ids] varchar(320) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[account] ALTER COLUMN [last_ip] varchar(64) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[account] ALTER COLUMN [disc_reason] varchar(512) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[account] ALTER COLUMN [password] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[AmphitheaterTeam] ALTER COLUMN [member] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [boat_name] varchar(68) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [boat_bag] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [boat_isdead] varchar(4) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [skill_state] varchar(1600) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [boat_createtime] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [boat_isdeleted] varchar(4) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[boat] ALTER COLUMN [map] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [atorNome] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [motto] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [job] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [map] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [olhe] varchar(8000) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [kitbag] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [skillbag] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [shortcut] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [mission] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [misrecord] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [mistrigger] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [miscount] varchar(2048) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [birth] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [login_cha] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [map_mask] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [main_map] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [skill_state] varchar(4096) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [bank] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character] ALTER COLUMN [extend] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character_log] ALTER COLUMN [atorNome] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character_log] ALTER COLUMN [job] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character_log] ALTER COLUMN [map] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[character_log] ALTER COLUMN [olhe] varchar(320) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[friends] ALTER COLUMN [relation] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[guild] ALTER COLUMN [guild_name] varchar(64) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[guild] ALTER COLUMN [motto] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[guild] ALTER COLUMN [passwd] varchar(80) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[guild] ALTER COLUMN [bank] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[guild] ALTER COLUMN [banklog] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[LotterySetting] ALTER COLUMN [itemno] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[map_mask] ALTER COLUMN [content1] varchar(2400) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[map_mask] ALTER COLUMN [content2] varchar(2400) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[map_mask] ALTER COLUMN [content3] varchar(2400) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[map_mask] ALTER COLUMN [content4] varchar(2400) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[map_mask] ALTER COLUMN [content5] varchar(2400) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[master] ALTER COLUMN [relation] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [motto] varchar(160) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [sex] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [name] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [animal_zodiac] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [blood_type] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [state] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [city] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [constellation] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[personinfo] ALTER COLUMN [career] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[property] ALTER COLUMN [context] varchar(1020) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[Resource] ALTER COLUMN [content] varchar(MAX) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[StatGender] ALTER COLUMN [gender] varchar(32) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[StatJob] ALTER COLUMN [job] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[StatMap] ALTER COLUMN [map] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[test_odbc_table] ALTER COLUMN [name] varchar(400) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[Ticket] ALTER COLUMN [itemno] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[Trade_Log] ALTER COLUMN [GameServer] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[Trade_Log] ALTER COLUMN [Action] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[Trade_Log] ALTER COLUMN [From] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[Trade_Log] ALTER COLUMN [To] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[Trade_Log] ALTER COLUMN [Memo] varchar(4000) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[weekreport] ALTER COLUMN [ato_nome] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[weekreport] ALTER COLUMN [atorNome] varchar(200) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NULL;
ALTER TABLE [dbo].[weekreport] ALTER COLUMN [ip] varchar(80) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[weekreport] ALTER COLUMN [Guild_Name] varchar(64) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;
ALTER TABLE [dbo].[WinTicket] ALTER COLUMN [itemno] varchar(40) COLLATE Latin1_General_100_CI_AS_SC_UTF8 NOT NULL;

PRINT '-- PHASE 4: CREATE indexes/PK/UK';
ALTER TABLE [dbo].[character] ADD CONSTRAINT [IX_character] UNIQUE NONCLUSTERED ([atorNome]);
ALTER TABLE [dbo].[guild] ADD CONSTRAINT [IX_guild_name] UNIQUE NONCLUSTERED ([guild_name]);
ALTER TABLE [dbo].[StatGender] ADD CONSTRAINT [PK_StatGender] PRIMARY KEY CLUSTERED ([gender]);
ALTER TABLE [dbo].[StatJob] ADD CONSTRAINT [PK_StatJob] PRIMARY KEY CLUSTERED ([job]);
ALTER TABLE [dbo].[StatMap] ADD CONSTRAINT [PK_StatMap] PRIMARY KEY CLUSTERED ([map]);

PRINT '-- PHASE 5: CREATE defaults';
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_skill_state] DEFAULT ('') FOR [skill_state];
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_boat_createtime] DEFAULT ('') FOR [boat_createtime];
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_boat_isdeleted] DEFAULT ((0)) FOR [boat_isdeleted];
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_map] DEFAULT ('') FOR [map];
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_boat_name] DEFAULT ('') FOR [boat_name];
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_boat_bag] DEFAULT ('') FOR [boat_bag];
ALTER TABLE [dbo].[boat] ADD CONSTRAINT [DF_boat_boat_isdie] DEFAULT ((0)) FOR [boat_isdead];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_motto] DEFAULT ('') FOR [motto];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_job] DEFAULT ('??') FOR [job];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_map] DEFAULT ('') FOR [map];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_look] DEFAULT ('') FOR [olhe];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_kitbag] DEFAULT ('') FOR [kitbag];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_skillbag] DEFAULT ('') FOR [skillbag];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_shortcut_1] DEFAULT ('') FOR [shortcut];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_mission] DEFAULT ('') FOR [mission];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_misrecord] DEFAULT ('') FOR [misrecord];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_trigger] DEFAULT ('') FOR [mistrigger];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_miscount] DEFAULT ('') FOR [miscount];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_birth] DEFAULT ('???') FOR [birth];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_login_cha] DEFAULT ((0)) FOR [login_cha];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_map_mask] DEFAULT ((0)) FOR [map_mask];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_main_map] DEFAULT ('') FOR [main_map];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_skill_state] DEFAULT ('') FOR [skill_state];
ALTER TABLE [dbo].[character] ADD CONSTRAINT [DF_character_bank] DEFAULT ('') FOR [bank];
ALTER TABLE [dbo].[character_log] ADD CONSTRAINT [DF_character_log_job] DEFAULT ((0)) FOR [job];
ALTER TABLE [dbo].[character_log] ADD CONSTRAINT [DF_character_log_map] DEFAULT ('') FOR [map];
ALTER TABLE [dbo].[character_log] ADD CONSTRAINT [DF_character_log_look] DEFAULT ('') FOR [olhe];
ALTER TABLE [dbo].[guild] ADD CONSTRAINT [DF_guild_guild_name] DEFAULT ('') FOR [guild_name];
ALTER TABLE [dbo].[guild] ADD CONSTRAINT [DF_guild_motto] DEFAULT ('') FOR [motto];
ALTER TABLE [dbo].[guild] ADD CONSTRAINT [DF_guild_passwd] DEFAULT ('') FOR [passwd];
ALTER TABLE [dbo].[guild] ADD CONSTRAINT [DF_guild_bank] DEFAULT ('') FOR [bank];
ALTER TABLE [dbo].[guild] ADD CONSTRAINT [DF__guild__banklog__7D0E9093] DEFAULT ('') FOR [banklog];
ALTER TABLE [dbo].[map_mask] ADD CONSTRAINT [DF_map_mask_content] DEFAULT ((0)) FOR [content1];
ALTER TABLE [dbo].[map_mask] ADD CONSTRAINT [DF_map_mask_content4] DEFAULT ((0)) FOR [content2];
ALTER TABLE [dbo].[map_mask] ADD CONSTRAINT [DF_map_mask_content3] DEFAULT ((0)) FOR [content3];
ALTER TABLE [dbo].[map_mask] ADD CONSTRAINT [DF_map_mask_content2] DEFAULT ((0)) FOR [content4];
ALTER TABLE [dbo].[map_mask] ADD CONSTRAINT [DF_map_mask_content1] DEFAULT ((0)) FOR [content5];
ALTER TABLE [dbo].[master] ADD CONSTRAINT [DF_master_relation] DEFAULT ('teacher') FOR [relation];
ALTER TABLE [dbo].[Resource] ADD CONSTRAINT [DF_Recource_content] DEFAULT ('') FOR [content];

COMMIT;
PRINT 'DONE';
