-- Filtered username words
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("�O")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("GM")
UI_AddFilterTextToNameTable	("gm")
UI_AddFilterTextToNameTable	("Gm")
UI_AddFilterTextToNameTable	("gM")
UI_AddFilterTextToNameTable	("CS")
UI_AddFilterTextToNameTable	("cs")
UI_AddFilterTextToNameTable	("Cs")
UI_AddFilterTextToNameTable	("cS")
UI_AddFilterTextToNameTable	("Customer Service")
UI_AddFilterTextToNameTable	("MIS")
UI_AddFilterTextToNameTable	("Newbie Guide")
UI_AddFilterTextToNameTable	("Test")
UI_AddFilterTextToNameTable	("TEST")
UI_AddFilterTextToNameTable	("test")
UI_AddFilterTextToNameTable	("Newbie Assistant")
UI_AddFilterTextToNameTable	("�ǣ�")
UI_AddFilterTextToNameTable	("GM")
UI_AddFilterTextToNameTable	("gm")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("Equipment Display")
UI_AddFilterTextToNameTable	("Equipment display")
UI_AddFilterTextToNameTable	("System Notice")
UI_AddFilterTextToNameTable	("Administrator")
UI_AddFilterTextToNameTable	("Game Management")
UI_AddFilterTextToNameTable	("System Management")
UI_AddFilterTextToNameTable	("System Test")
UI_AddFilterTextToNameTable	("Event Management")
UI_AddFilterTextToNameTable	("Customer Service")
UI_AddFilterTextToNameTable	("Event Commissioner")
UI_AddFilterTextToNameTable	("Pirate King Technology")
UI_AddFilterTextToNameTable	("Events")
UI_AddFilterTextToNameTable	("Game System")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Game Management")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fuCK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fUCk")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("1989-6-4")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fucK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fuCk")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words ")
UI_AddFilterTextToNameTable	("fUck")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("World Trial Hero")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("FLG")
UI_AddFilterTextToNameTable	("F.L.G")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("bitch")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("falundafa")
UI_AddFilterTextToNameTable	("falun")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("sex")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("FUcK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("tmd")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("SB")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("Fuck")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("SHIT")
UI_AddFilterTextToNameTable	("Shit")
UI_AddFilterTextToNameTable	("shit")
UI_AddFilterTextToNameTable	("BITCH")
UI_AddFilterTextToNameTable	("bitch")
UI_AddFilterTextToNameTable	("Fuck You")
UI_AddFilterTextToNameTable	("fuck you")
UI_AddFilterTextToNameTable	("FUCK YOU")
UI_AddFilterTextToNameTable	("ɵB")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("SB")
UI_AddFilterTextToNameTable	("sb")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("FUCk")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("FucK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("FuCk")
UI_AddFilterTextToNameTable	("FUck")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("F U C K")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("f u c k")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fUCK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fUcK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("System")
UI_AddFilterTextToNameTable	("Notice")
UI_AddFilterTextToNameTable	("Pirate King")
UI_AddFilterTextToNameTable	("Official")
UI_AddFilterTextToNameTable	("Prize Notice")
UI_AddFilterTextToNameTable	("System")
UI_AddFilterTextToNameTable	("Information")
UI_AddFilterTextToNameTable	(" Forbidden words")
UI_AddFilterTextToNameTable	("Promote")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Sales")
UI_AddFilterTextToNameTable	("Promotion")
UI_AddFilterTextToNameTable	("RMB")
UI_AddFilterTextToNameTable	("Lets find treasure together  ")
UI_AddFilterTextToNameTable	("65487074")
UI_AddFilterTextToNameTable	("8008-409-653")
UI_AddFilterTextToNameTable	("Remit")
UI_AddFilterTextToNameTable	("Whole nation lowest")
UI_AddFilterTextToNameTable	("Nation lowest")
UI_AddFilterTextToNameTable	("201192")
UI_AddFilterTextToNameTable	("188835357")
UI_AddFilterTextToNameTable	("5323488")
UI_AddFilterTextToNameTable	("Dragon Studio")
UI_AddFilterTextToNameTable	("Pirate Wraith")
UI_AddFilterTextToNameTable	("Offline")
UI_AddFilterTextToNameTable	("Bots")
UI_AddFilterTextToNameTable	("www.wmsjff.com")
UI_AddFilterTextToNameTable	("www.wmsjff.com")
UI_AddFilterTextToNameTable	("ufo")
UI_AddFilterTextToNameTable	("u f o")
UI_AddFilterTextToNameTable	("\"Pirate Angel\"")
UI_AddFilterTextToNameTable	("Cornucopia")
UI_AddFilterTextToNameTable	("game.jupay.com")
UI_AddFilterTextToNameTable	("Fuck")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����˼")
UI_AddFilterTextToNameTable	("����˹")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ҫ��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�¼ұ�")
UI_AddFilterTextToNameTable	("fUCk")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����Ȫ")
UI_AddFilterTextToNameTable	("�ŵ½�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("���g��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("СȪ")
UI_AddFilterTextToNameTable	("����ķ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("̨��")
UI_AddFilterTextToNameTable	("̨�����")
UI_AddFilterTextToNameTable	("�ֲ�����")
UI_AddFilterTextToNameTable	("���㵺")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ƨ")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("ƨ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("�ּ�")
UI_AddFilterTextToNameTable	("�д�")
UI_AddFilterTextToNameTable	("��Ժ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��Ů")
UI_AddFilterTextToNameTable	("�ο�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��Ƥ")
UI_AddFilterTextToNameTable	("�¾�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("���յ�")
UI_AddFilterTextToNameTable	("���˵�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�Ҹ�")
UI_AddFilterTextToNameTable	("��С˺��")
UI_AddFilterTextToNameTable	("�ܴ��ﲪ")
UI_AddFilterTextToNameTable	("�Ծ�����")
UI_AddFilterTextToNameTable	("shit")
UI_AddFilterTextToNameTable	("fuc")
UI_AddFilterTextToNameTable	("fvc")
--UI_AddFilterTextToNameTable	("fu("")
--UI_AddFilterTextToNameTable	("fv("")
UI_AddFilterTextToNameTable	("dick")
UI_AddFilterTextToNameTable	("asshole")
UI_AddFilterTextToNameTable	("piss")
UI_AddFilterTextToNameTable	("cunt")
UI_AddFilterTextToNameTable	("damn")
UI_AddFilterTextToNameTable	("damm")
UI_AddFilterTextToNameTable	("bitch")
UI_AddFilterTextToNameTable	("bastard")
UI_AddFilterTextToNameTable	("butthole")
UI_AddFilterTextToNameTable	("butthead")
UI_AddFilterTextToNameTable	("fag")
UI_AddFilterTextToNameTable	("phuc")
UI_AddFilterTextToNameTable	("fuk")
UI_AddFilterTextToNameTable	("wtf")
UI_AddFilterTextToNameTable	("shyt")
UI_AddFilterTextToNameTable	("sh!t")
UI_AddFilterTextToNameTable	("@sshole")
UI_AddFilterTextToNameTable	("a$$hole")
UI_AddFilterTextToNameTable	("as$hole")
UI_AddFilterTextToNameTable	("a$shole")
UI_AddFilterTextToNameTable	("Fuck")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("Suck")
UI_AddFilterTextToNameTable	("suck")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("SUCK")
UI_AddFilterTextToNameTable	("��GM")
UI_AddFilterTextToNameTable	("��GM")
UI_AddFilterTextToNameTable	("��GD")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�Ɋ���")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�ي���")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�ي���")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�Ɋ���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������ĸ")
UI_AddFilterTextToNameTable	("�Ɋ���ĸ")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������ĸ")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("���㹫")
UI_AddFilterTextToNameTable	("����ĸ")
UI_AddFilterTextToNameTable	("������ʦ")
UI_AddFilterTextToNameTable	("ʻ����ĸ")
UI_AddFilterTextToNameTable	("ʻ����")
UI_AddFilterTextToNameTable	("ʻ���")
UI_AddFilterTextToNameTable	("ʻ��ĸ")
UI_AddFilterTextToNameTable	("ʻ�㹫")
UI_AddFilterTextToNameTable	("ʻ����ʦ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("�ي�����")
UI_AddFilterTextToNameTable	("���߰�")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�ي�")
UI_AddFilterTextToNameTable	("����ĸ��")
UI_AddFilterTextToNameTable	("�Ҋ��ϰ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�")
UI_AddFilterTextToNameTable	("�ͽ�")
UI_AddFilterTextToNameTable	("�ݼҲ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("ʳ��ʺ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ĸ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�Ŋ�")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��7")
UI_AddFilterTextToNameTable	("�ʺ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("ʳʺ")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("ɵ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("ɵ��")
UI_AddFilterTextToNameTable	("�����ү")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�������װ")
UI_AddFilterTextToNameTable	("װ����")
UI_AddFilterTextToNameTable	("װ����")
UI_AddFilterTextToNameTable	("����������")
UI_AddFilterTextToNameTable	("����������")
UI_AddFilterTextToNameTable	("�����ѵ�")
UI_AddFilterTextToNameTable	("����Ϊ��װ�ƾ���ƭ��")
UI_AddFilterTextToNameTable	("����Ϊ��װ�¾���ƭ��")
UI_AddFilterTextToNameTable	("��ѽ�ļ��ͳ����˰�")
UI_AddFilterTextToNameTable	("����Ϊ����̫���Ҿ�����")
UI_AddFilterTextToNameTable	("Ѿͷ����")
UI_AddFilterTextToNameTable	("��ȫ��")
UI_AddFilterTextToNameTable	("kingofdeath")
UI_AddFilterTextToNameTable	("KINGOFDEATH")
UI_AddFilterTextToNameTable	("KingofDeath")
UI_AddFilterTextToNameTable	("K I N G O F D E A T H")
UI_AddFilterTextToNameTable	("kingofdeath")
UI_AddFilterTextToNameTable	("KINGOFDEATH")
UI_AddFilterTextToNameTable	("KingOf")
UI_AddFilterTextToNameTable	("KINGof")
UI_AddFilterTextToNameTable	("�����ȫ��")
UI_AddFilterTextToNameTable	("̫��")
UI_AddFilterTextToNameTable	("����ȫ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("װ��")
UI_AddFilterTextToNameTable	("װ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("ɵB")
UI_AddFilterTextToNameTable	("��core")
UI_AddFilterTextToNameTable	("���Ļ�")
UI_AddFilterTextToNameTable	("���Ļ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("��B")
UI_AddFilterTextToNameTable	("��ѪB")
UI_AddFilterTextToNameTable	("������ƨ")
UI_AddFilterTextToNameTable	("������ƨ")
UI_AddFilterTextToNameTable	("�������B")
UI_AddFilterTextToNameTable	("���������")
UI_AddFilterTextToNameTable	("dick")
UI_AddFilterTextToNameTable	("Dick")
UI_AddFilterTextToNameTable	("DICK")
UI_AddFilterTextToNameTable	("��B")
UI_AddFilterTextToNameTable	("�ñ�")
UI_AddFilterTextToNameTable	("�Ì�")
UI_AddFilterTextToNameTable	("�Ì�")
UI_AddFilterTextToNameTable	("���ò���")
UI_AddFilterTextToNameTable	("�ȵ�")
UI_AddFilterTextToNameTable	("�٨�����ĸ")
UI_AddFilterTextToNameTable	("�٨����")
UI_AddFilterTextToNameTable	("�٨�����")
UI_AddFilterTextToNameTable	("�٨��㹫")
UI_AddFilterTextToNameTable	("�٨�����ʦ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�а�")
UI_AddFilterTextToNameTable	("�а�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���R")
UI_AddFilterTextToNameTable	("Dick")
UI_AddFilterTextToNameTable	("DICK")
UI_AddFilterTextToNameTable	("��B")
UI_AddFilterTextToNameTable	("�Ì�")
UI_AddFilterTextToNameTable	("�ñ�")
UI_AddFilterTextToNameTable	("�Ì�")
UI_AddFilterTextToNameTable	("Administrator")
UI_AddFilterTextToNameTable	("����T")
UI_AddFilterTextToNameTable	("B��ʿ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Bots")
UI_AddFilterTextToNameTable	("˽��")
UI_AddFilterTextToNameTable	("4f")
UI_AddFilterTextToNameTable	("sf")
UI_AddFilterTextToNameTable	("GAMEMASTER")
UI_AddFilterTextToNameTable	("GameMaster")
UI_AddFilterTextToNameTable	("ͫ")
UI_AddFilterTextToNameTable	("Fag")
UI_AddFilterTextToNameTable	("bitch")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Bots")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("BnB")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("shengda")
UI_AddFilterTextToNameTable	("Fuck")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("Suck")
UI_AddFilterTextToNameTable	("suck")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("SUCK")
UI_AddFilterTextToNameTable	("�Ǩ�")
UI_AddFilterTextToNameTable	("���Ǩ�")
UI_AddFilterTextToNameTable	("���ǵ�")
UI_AddFilterTextToNameTable	("��GM")
UI_AddFilterTextToNameTable	("��GM")
UI_AddFilterTextToNameTable	("��GD")
UI_AddFilterTextToNameTable	("��GD")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�ض�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("@sshole")
UI_AddFilterTextToNameTable	("a$$hole")
UI_AddFilterTextToNameTable	("a$shole")
UI_AddFilterTextToNameTable	("Admin")
UI_AddFilterTextToNameTable	("as$hole")
UI_AddFilterTextToNameTable	("asshole")
UI_AddFilterTextToNameTable	("bastard")
UI_AddFilterTextToNameTable	("bitch")
UI_AddFilterTextToNameTable	("Bitch")
UI_AddFilterTextToNameTable	("bt")
UI_AddFilterTextToNameTable	("butthead")
UI_AddFilterTextToNameTable	("butthole")
UI_AddFilterTextToNameTable	("B��ʿ")
UI_AddFilterTextToNameTable	("cao")
UI_AddFilterTextToNameTable	("cs")
UI_AddFilterTextToNameTable	("cunt")
UI_AddFilterTextToNameTable	("damm")
UI_AddFilterTextToNameTable	("damn")
UI_AddFilterTextToNameTable	("dick")
UI_AddFilterTextToNameTable	("DICK")
UI_AddFilterTextToNameTable	("Dick")
UI_AddFilterTextToNameTable	("fosaon")
--UI_AddFilterTextToNameTable	("fu("")
UI_AddFilterTextToNameTable	("fuc")
UI_AddFilterTextToNameTable	("Fuck")
UI_AddFilterTextToNameTable	("FUCK")
UI_AddFilterTextToNameTable	("fuck")
UI_AddFilterTextToNameTable	("cctv")
UI_AddFilterTextToNameTable	("fuk")
--UI_AddFilterTextToNameTable	("fv("")
UI_AddFilterTextToNameTable	("ȥ��")
UI_AddFilterTextToNameTable	("ȳ�Ȱ�")
UI_AddFilterTextToNameTable	("�˵�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�����ձ�")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("ɵ��")
UI_AddFilterTextToNameTable	("ɵ��")
UI_AddFilterTextToNameTable	("fvc")
UI_AddFilterTextToNameTable	("GameMaster")
UI_AddFilterTextToNameTable	("GAMEMASTER")
UI_AddFilterTextToNameTable	("gm")
UI_AddFilterTextToNameTable	("GM")
UI_AddFilterTextToNameTable	("kao")
UI_AddFilterTextToNameTable	("K��")
UI_AddFilterTextToNameTable	("K����")
UI_AddFilterTextToNameTable	("NMD")
UI_AddFilterTextToNameTable	("nnd")
UI_AddFilterTextToNameTable	("orgasmus")
UI_AddFilterTextToNameTable	("penis")
UI_AddFilterTextToNameTable	("phuc")
UI_AddFilterTextToNameTable	("piss")
UI_AddFilterTextToNameTable	("ri")
UI_AddFilterTextToNameTable	("sb")
UI_AddFilterTextToNameTable	("screw")
UI_AddFilterTextToNameTable	("sega")
UI_AddFilterTextToNameTable	("sex")
UI_AddFilterTextToNameTable	("sf")
UI_AddFilterTextToNameTable	("sh!t")
UI_AddFilterTextToNameTable	("shengda")
UI_AddFilterTextToNameTable	("SHIT")
UI_AddFilterTextToNameTable	("shit")
UI_AddFilterTextToNameTable	("shyt")
UI_AddFilterTextToNameTable	("SM")
UI_AddFilterTextToNameTable	("snatch")
UI_AddFilterTextToNameTable	("SUCK")
UI_AddFilterTextToNameTable	("Suck")
UI_AddFilterTextToNameTable	("suck")
UI_AddFilterTextToNameTable	("���²�")
UI_AddFilterTextToNameTable	("����ը��")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("�ձ�")
UI_AddFilterTextToNameTable	("�ձ�RING")
UI_AddFilterTextToNameTable	("�ձ�����")
UI_AddFilterTextToNameTable	("ʳ��ʺ")
UI_AddFilterTextToNameTable	("ʳʺ")
UI_AddFilterTextToNameTable	("TMD")
UI_AddFilterTextToNameTable	("tnnd")
UI_AddFilterTextToNameTable	("WG")
UI_AddFilterTextToNameTable	("wtf")
UI_AddFilterTextToNameTable	("�а�")
UI_AddFilterTextToNameTable	("�а�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�٨����")
UI_AddFilterTextToNameTable	("�٨��㹫")
UI_AddFilterTextToNameTable	("�٨�����ĸ")
UI_AddFilterTextToNameTable	("�٨�����ʦ")
UI_AddFilterTextToNameTable	("�٨���ĸ")
UI_AddFilterTextToNameTable	("�٨�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����ͪ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ȫ��")
UI_AddFilterTextToNameTable	("��ȫ���")
UI_AddFilterTextToNameTable	("��ȫ���»�")
UI_AddFilterTextToNameTable	("�չ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�칫��")
UI_AddFilterTextToNameTable	("��Ƥ")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��GD")
UI_AddFilterTextToNameTable	("��GD")
UI_AddFilterTextToNameTable	("�¾�")
UI_AddFilterTextToNameTable	("�緹")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����ά")
UI_AddFilterTextToNameTable	("�ŵ½�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("֤���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("ָ��Ա")
UI_AddFilterTextToNameTable	("�ʼ��")
UI_AddFilterTextToNameTable	("�»ü�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�й�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("fuCK")
UI_AddFilterTextToNameTable	("�п�Ժ")
UI_AddFilterTextToNameTable	("���Ϻ�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�������̨")
UI_AddFilterTextToNameTable	("�������ξ�")
UI_AddFilterTextToNameTable	("��ҽҩ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����ķ")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("���㹫")
UI_AddFilterTextToNameTable	("������ĸ")
UI_AddFilterTextToNameTable	("������ʦ")
UI_AddFilterTextToNameTable	("����ĸ")
UI_AddFilterTextToNameTable	("̨�����")
UI_AddFilterTextToNameTable	("̫��")
UI_AddFilterTextToNameTable	("�ض�")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�ي�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�������")
UI_AddFilterTextToNameTable	("�ִܸ�")
UI_AddFilterTextToNameTable	("CCTV")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("���ܾ�")
UI_AddFilterTextToNameTable	("�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ͽ")
UI_AddFilterTextToNameTable	("��?����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("��ʲ")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ȥ����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("ɫ��")
UI_AddFilterTextToNameTable	("�⽻��")
UI_AddFilterTextToNameTable	("��ר��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("���g��")
UI_AddFilterTextToNameTable	("��ϯ")
UI_AddFilterTextToNameTable	("ת����")
UI_AddFilterTextToNameTable	("װ��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("װ��")
UI_AddFilterTextToNameTable	("��ȫ��")
UI_AddFilterTextToNameTable	("�Է�")
UI_AddFilterTextToNameTable	("���λ���")
UI_AddFilterTextToNameTable	("�ڽ�")
UI_AddFilterTextToNameTable	("�ܾ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�劅")
UI_AddFilterTextToNameTable	("��Ȩ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("��ˮ��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�������")
UI_AddFilterTextToNameTable	("����ҩ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("ɱ��")
UI_AddFilterTextToNameTable	("ɱ�˷�")
UI_AddFilterTextToNameTable	("ɱ��")
UI_AddFilterTextToNameTable	("ɵB")
UI_AddFilterTextToNameTable	("ɵ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��B")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������֬")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("��ѪB")
UI_AddFilterTextToNameTable	("�������")
UI_AddFilterTextToNameTable	("����ϯ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("���Է�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("�ܴ��ﲪ")
UI_AddFilterTextToNameTable	("�۹�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��7")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("�Ŋ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���㵺")
UI_AddFilterTextToNameTable	("����̨")
UI_AddFilterTextToNameTable	("����Ӣ��")
UI_AddFilterTextToNameTable	("��ͻ")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("СȪ")
UI_AddFilterTextToNameTable	("СȪ��һ��")
UI_AddFilterTextToNameTable	("С�ձ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�»���")
UI_AddFilterTextToNameTable	("���Ű�")
UI_AddFilterTextToNameTable	("���ų���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���ǲ���")
UI_AddFilterTextToNameTable	("���Ļ�")
UI_AddFilterTextToNameTable	("���Ļ�")
UI_AddFilterTextToNameTable	("����˹")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���һ�����")
UI_AddFilterTextToNameTable	("����ί")
UI_AddFilterTextToNameTable	("��չ�о�����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����˹")
UI_AddFilterTextToNameTable	("��Ժ")
UI_AddFilterTextToNameTable	("���ư�")
UI_AddFilterTextToNameTable	("����ίԱ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�Ɋ�")
UI_AddFilterTextToNameTable	("�Ɋ���ĸ")
UI_AddFilterTextToNameTable	("�Ɋ���")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�̲ݾ�")
UI_AddFilterTextToNameTable	("ҡͷ��")
UI_AddFilterTextToNameTable	("ҡͷ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Jesus")
UI_AddFilterTextToNameTable	("Ҷ��Ӣ")
UI_AddFilterTextToNameTable	("ҹ��")
UI_AddFilterTextToNameTable	("��������˹̹һ���")
UI_AddFilterTextToNameTable	("������b")
UI_AddFilterTextToNameTable	("�������")
UI_AddFilterTextToNameTable	("���߰�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�۰İ�")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("غ")
UI_AddFilterTextToNameTable	("��ҩ��")
UI_AddFilterTextToNameTable	("����Ժ")
UI_AddFilterTextToNameTable	("���̾�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ƨ")
UI_AddFilterTextToNameTable	("���յ�")
UI_AddFilterTextToNameTable	("JB")
UI_AddFilterTextToNameTable	("sb")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������Ա")
UI_AddFilterTextToNameTable	("Administrator")
UI_AddFilterTextToNameTable	("�����ձ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����ƹ�ί")
UI_AddFilterTextToNameTable	("��С˺��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�ϊ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�籣�����")
UI_AddFilterTextToNameTable	("�������")
UI_AddFilterTextToNameTable	("���Ժ")
UI_AddFilterTextToNameTable	("�񾭲�")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��ѻƬ")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Sacred War")
UI_AddFilterTextToNameTable	("��ë��")
UI_AddFilterTextToNameTable	("��ĸ")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("���־")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����ӳ")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���Ϲ�")
UI_AddFilterTextToNameTable	("���Ϲ����")
UI_AddFilterTextToNameTable	("��ʳ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�ֱ�")
UI_AddFilterTextToNameTable	("��ҵ��")
UI_AddFilterTextToNameTable	("��  �")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("ʻ���")
UI_AddFilterTextToNameTable	("ʻ�㹫")
UI_AddFilterTextToNameTable	("ʻ����ĸ")
UI_AddFilterTextToNameTable	("ʻ����ʦ")
UI_AddFilterTextToNameTable	("ʻ��ĸ")
UI_AddFilterTextToNameTable	("ʻ����")
UI_AddFilterTextToNameTable	("ʾ��")
UI_AddFilterTextToNameTable	("ˮ����")
UI_AddFilterTextToNameTable	("ˮȥ����")
UI_AddFilterTextToNameTable	("˰���ܾ�")
UI_AddFilterTextToNameTable	("˾����")
UI_AddFilterTextToNameTable	("˹����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("���ճ�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����������»�")
UI_AddFilterTextToNameTable	("�������»�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�")
UI_AddFilterTextToNameTable	("�ʺ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����ίԱ��")
UI_AddFilterTextToNameTable	("��ί")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�Ƽ���")
UI_AddFilterTextToNameTable	("�ɴ���")
UI_AddFilterTextToNameTable	("�˴���")
UI_AddFilterTextToNameTable	("��GM")
UI_AddFilterTextToNameTable	("��GM")
UI_AddFilterTextToNameTable	("��ȫ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����Ӣ")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("̨��")
UI_AddFilterTextToNameTable	("̨��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�ͻ�������Ա")
UI_AddFilterTextToNameTable	("�ֲ�����")
UI_AddFilterTextToNameTable	("�ֲ�����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("�����ȫ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("ë��ϯ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�ɹŴ���")
UI_AddFilterTextToNameTable	("Head Secretary")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�񺽾�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�˴����")
UI_AddFilterTextToNameTable	("�Ƽ��")
UI_AddFilterTextToNameTable	("�����ܾ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�찲���¼�")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("ͳ�ƾ�")
UI_AddFilterTextToNameTable	("�й����»�")
UI_AddFilterTextToNameTable	("��  ��")
UI_AddFilterTextToNameTable	("Bots")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�Ì�")
UI_AddFilterTextToNameTable	("�ñ�")
UI_AddFilterTextToNameTable	("�Ì�")
UI_AddFilterTextToNameTable	("�Ͷ����Ͼ�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������֯")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Christian")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����ί")
UI_AddFilterTextToNameTable	("��Ů")
UI_AddFilterTextToNameTable	("��Ժ")
UI_AddFilterTextToNameTable	("fUCk")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��첿")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("�˴�")
UI_AddFilterTextToNameTable	("���˵�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����Ȫ")
UI_AddFilterTextToNameTable	("���׹�")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�¼ұ�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�Ļ���")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����ϯ")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ͨ��")
UI_AddFilterTextToNameTable	("�д�")
UI_AddFilterTextToNameTable	("�̹�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�Ȱ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ɫ")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("��ķ˹�ƶ���")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�Ҹ�")
UI_AddFilterTextToNameTable	("�Ҋ��ϰ�")
UI_AddFilterTextToNameTable	("��  ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("���ض���")
UI_AddFilterTextToNameTable	("ϣ����")
UI_AddFilterTextToNameTable	("ϣ����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����˼")
UI_AddFilterTextToNameTable	("������ƨ")
UI_AddFilterTextToNameTable	("��Ӣ��")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("��ȼ�")
UI_AddFilterTextToNameTable	("���Ƭ")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("���ܾ�")
UI_AddFilterTextToNameTable	("���ʷ�Ժ")
UI_AddFilterTextToNameTable	("������ί")
UI_AddFilterTextToNameTable	("������Ҫ��ί")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("������Դ��")
UI_AddFilterTextToNameTable	("����Ժ")
UI_AddFilterTextToNameTable	("��ܾ�")
UI_AddFilterTextToNameTable	("���Ժ")
UI_AddFilterTextToNameTable	("���貿")
UI_AddFilterTextToNameTable	("��core")
UI_AddFilterTextToNameTable	("��ɱ")
UI_AddFilterTextToNameTable	("���ų�������")
UI_AddFilterTextToNameTable	("�ŷþ�")
UI_AddFilterTextToNameTable	("��Ϣ��ҵ��")
UI_AddFilterTextToNameTable	("Incitant")
UI_AddFilterTextToNameTable	("�Խ�")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("ѧ��")
UI_AddFilterTextToNameTable	("Ѿ��")
UI_AddFilterTextToNameTable	("Ѿͷ����")
UI_AddFilterTextToNameTable	("ѻƬ")
UI_AddFilterTextToNameTable	("ѻƬҺ")
UI_AddFilterTextToNameTable	("ѻƬ��")
UI_AddFilterTextToNameTable	("��ҫ��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����ܾ�")
UI_AddFilterTextToNameTable	("��  ��")
UI_AddFilterTextToNameTable	("forbidden word")
UI_AddFilterTextToNameTable	("�ػ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��B")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����ɽ")
UI_AddFilterTextToNameTable	("��ʦ")
UI_AddFilterTextToNameTable	("Ӣ�ۼ��")
UI_AddFilterTextToNameTable	("��ɱ")
UI_AddFilterTextToNameTable	("�˴�")
UI_AddFilterTextToNameTable	("�˴���")
UI_AddFilterTextToNameTable	("�˴����")
UI_AddFilterTextToNameTable	("һ������")
UI_AddFilterTextToNameTable	("һҹ��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�Ծ��ƶ�")
UI_AddFilterTextToNameTable	("���Ƽ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("��ë")
UI_AddFilterTextToNameTable	("Ű��")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�ο�")
UI_AddFilterTextToNameTable	("�ƻ�")
UI_AddFilterTextToNameTable	("�ͽ�")
UI_AddFilterTextToNameTable	("�վ�")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("ǿ�鷸")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("���ξ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�� ��")
UI_AddFilterTextToNameTable	("���")
UI_AddFilterTextToNameTable	("������ƨ")
UI_AddFilterTextToNameTable	("������ƨ")
UI_AddFilterTextToNameTable	("Customer Service")
UI_AddFilterTextToNameTable	("����㳡")
UI_AddFilterTextToNameTable	("��Ϸ����Ա")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("ԭ���ܻ���")
UI_AddFilterTextToNameTable	("Բ��")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("����ĸ��")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����")
UI_AddFilterTextToNameTable	("�����ѵ�")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("��")
UI_AddFilterTextToNameTable	("ũҵ��")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("����ί")
UI_AddFilterTextToNameTable	("��������")
UI_AddFilterTextToNameTable	("������")
UI_AddFilterTextToNameTable	("�����")
UI_AddFilterTextToNameTable	("�ع�ǿ")
UI_AddFilterTextToNameTable	("���ֵ�")
UI_AddFilterTextToNameTable	("Forbidden words")
UI_AddFilterTextToNameTable	("�ɿ�Ҷ")
UI_AddFilterTextToNameTable	("�ɿ���")
UI_AddFilterTextToNameTable	("���ֶ�")
UI_AddFilterTextToNameTable	("Jesus")
UI_AddFilterTextToNameTable	("�x ")
UI_AddFilterTextToNameTable	("��ͻ")


-- Filtered chat dialog words
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fuCK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fUCk")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("1989-6-4")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fucK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fuCk")
--UI_AddFilterTextToDialogTable	("ufo")
--UI_AddFilterTextToDialogTable	("u f o")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words ")
UI_AddFilterTextToDialogTable	("fUck")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("World Trial Hero")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fuck")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("fuck")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("FLG")
UI_AddFilterTextToDialogTable	("F.L.G")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fuck")
UI_AddFilterTextToDialogTable	("bitch")
UI_AddFilterTextToDialogTable	("FUCK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("falundafa")
UI_AddFilterTextToDialogTable	("falun")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("sex")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("FUcK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("tmd")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("SB")
UI_AddFilterTextToDialogTable	("FUCK")
UI_AddFilterTextToDialogTable	("Fuck")
UI_AddFilterTextToDialogTable	("fuck")
UI_AddFilterTextToDialogTable	("SHIT")
UI_AddFilterTextToDialogTable	("Shit")
UI_AddFilterTextToDialogTable	("shit")
UI_AddFilterTextToDialogTable	("BITCH")
UI_AddFilterTextToDialogTable	("bitch")
UI_AddFilterTextToDialogTable	("Fuck You")
UI_AddFilterTextToDialogTable	("fuck you")
UI_AddFilterTextToDialogTable	("FUCK YOU")
UI_AddFilterTextToDialogTable	("ɵB")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("SB")
--UI_AddFilterTextToDialogTable	("sb")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("forbidden word")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("FUCk")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("FucK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("FuCk")
UI_AddFilterTextToDialogTable	("FUck")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("F U C K")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("FUCK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("f u c k")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fUCK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("fUcK")
UI_AddFilterTextToDialogTable	("Forbidden words")
UI_AddFilterTextToDialogTable	("Web")           	
UI_AddFilterTextToDialogTable	("17zb")          
UI_AddFilterTextToDialogTable	("17ZB")          
UI_AddFilterTextToDialogTable	("Prize Notice")       
--UI_AddFilterTextToDialogTable	("System")           
--UI_AddFilterTextToDialogTable	("Information")           
UI_AddFilterTextToDialogTable	(" Forbidden words")         
--UI_AddFilterTextToDialogTable	("Promote")           
UI_AddFilterTextToDialogTable	("Forbidden words")           
--UI_AddFilterTextToDialogTable	("Sales")           
--UI_AddFilterTextToDialogTable	("Promotion")           
UI_AddFilterTextToDialogTable	("RMB")         
UI_AddFilterTextToDialogTable	("Lets find treasure together  ")       
UI_AddFilterTextToDialogTable	("65487074")      
UI_AddFilterTextToDialogTable	("8008-409-653")  
UI_AddFilterTextToDialogTable	("Remit")           
UI_AddFilterTextToDialogTable	("Whole nation lowest")     
UI_AddFilterTextToDialogTable	("Nation lowest")     
UI_AddFilterTextToDialogTable	("201192")        
UI_AddFilterTextToDialogTable	("188835357")     
UI_AddFilterTextToDialogTable	("5323488")  
UI_AddFilterTextToDialogTable	("Dragon Studio")
UI_AddFilterTextToDialogTable	("Pirate Wraith")
--UI_AddFilterTextToDialogTable	("Offline")
--UI_AddFilterTextToDialogTable	("Bots")
UI_AddFilterTextToDialogTable	("www.wmsjff.com")
UI_AddFilterTextToDialogTable	("www.wmsjff.com")
UI_AddFilterTextToDialogTable	("\"Pirate Angel\"")
UI_AddFilterTextToDialogTable	("Cornucopia")
UI_AddFilterTextToDialogTable	("game.jupay.com")
UI_AddFilterTextToDialogTable	("dungeonsea")
UI_AddFilterTextToDialogTable	("dunge0nsea")
UI_AddFilterTextToDialogTable	("DUNGEONSEA")
UI_AddFilterTextToDialogTable	("DUNGE0NSEA")
UI_AddFilterTextToDialogTable	("d u n g e o n s e a")
UI_AddFilterTextToDialogTable	("d u n g e 0 n s e a")
UI_AddFilterTextToDialogTable	("mmovo")
UI_AddFilterTextToDialogTable	("Mmov")
UI_AddFilterTextToDialogTable	("MMov")
UI_AddFilterTextToDialogTable	("MMOv")
UI_AddFilterTextToDialogTable	("MMOV")
UI_AddFilterTextToDialogTable	("MMOV")
UI_AddFilterTextToDialogTable	("mMOV")
UI_AddFilterTextToDialogTable	("mmOV")
UI_AddFilterTextToDialogTable	("mMoV")
UI_AddFilterTextToDialogTable	("MovO")
UI_AddFilterTextToDialogTable	("gameci")
UI_AddFilterTextToDialogTable	("GAMECI")
UI_AddFilterTextToDialogTable	("Gameci")
UI_AddFilterTextToDialogTable	("GAMEci")
UI_AddFilterTextToDialogTable	("gameCI")
UI_AddFilterTextToDialogTable	("GAmeci")
UI_AddFilterTextToDialogTable	("GamecI")
UI_AddFilterTextToDialogTable	("noob")
UI_AddFilterTextToDialogTable	("n o o b")
UI_AddFilterTextToDialogTable	("NOOB")
UI_AddFilterTextToDialogTable	("nub")
UI_AddFilterTextToDialogTable	("NooB")
UI_AddFilterTextToDialogTable	("fuc")
UI_AddFilterTextToDialogTable	("FUK")
UI_AddFilterTextToDialogTable	("FUC")
UI_AddFilterTextToDialogTable	("Cunt")
UI_AddFilterTextToDialogTable	("cunt")
UI_AddFilterTextToDialogTable	("slut")
UI_AddFilterTextToDialogTable	("whore")
UI_AddFilterTextToDialogTable	("SLUT")
UI_AddFilterTextToDialogTable	("WHORE")
UI_AddFilterTextToDialogTable	("kingofdeath")
UI_AddFilterTextToDialogTable	("KINGOFDEATH")
UI_AddFilterTextToDialogTable	("KingofDeath")
UI_AddFilterTextToDialogTable	("K I N G O F D E A T H")
UI_AddFilterTextToDialogTable	("kingofdeath")
UI_AddFilterTextToDialogTable	("KINGOFDEATH")
UI_AddFilterTextToDialogTable	("KingOf")
UI_AddFilterTextToDialogTable	("KINGof")
--UI_AddFilterTextToDialogTable	("king of death")
UI_AddFilterTextToDialogTable ("oosale")
UI_AddFilterTextToDialogTable ("Oosale")
UI_AddFilterTextToDialogTable ("o o s a l e")
UI_AddFilterTextToDialogTable ("g a m e c i")
UI_AddFilterTextToDialogTable ("m m o v o")
UI_AddFilterTextToDialogTable ("M M O V O")
UI_AddFilterTextToDialogTable ("G A M E C I")
UI_AddFilterTextToDialogTable ("OOSALE")
UI_AddFilterTextToDialogTable ("O O S A L E")
UI_AddFilterTextToDialogTable ("G a m e c i")
UI_AddFilterTextToDialogTable ("M m o v o")